### ISSUE TITLE
MongoDB entities created using the repository pattern with a nested array throw an error for any find query

### ISSUE THREAD

**Issue by Ionaru** [typeorm/typeorm#10391]
### Issue description

A query for a MongoDB entity that contains a nested array, will cause an error in a find query when the entity was created using the repository patten.

### Expected Behavior

No error should happen and I am able to query the created objects with nested arrays.

### Actual Behavior

`Repository.find({})` throws an error:
```
TypeError: document[embedded.prefix].map is not a function
 at C:\Users\Jeroen\Projects\typeorm\src\query-builder\transformer\DocumentToEntityTransformer.ts:115:23
 at Array.forEach (<anonymous>)
 at addEmbeddedValuesRecursively (src\query-builder\transformer\DocumentToEntityTransformer.ts:109:23)
 at DocumentToEntityTransformer.transform (src\query-builder\transformer\DocumentToEntityTransformer.ts:164:9)
 at C:\Users\Jeroen\Projects\typeorm\src\query-builder\transformer\DocumentToEntityTransformer.ts:26:49
 at Array.map (<anonymous>)
 at DocumentToEntityTransformer.transformAll (src\query-builder\transformer\DocumentToEntityTransformer.ts:26:26)
 at C:\Users\Jeroen\Projects\typeorm\src\entity-manager\MongoEntityManager.ts:1034:50
 at processTicksAndRejections (node:internal/process/task_queues:95:5)
 at Context.<anonymous> (test\github-issues\9049\issue-9049.ts:59:27)

```

The result of this "broken" entity existing in the database means any `.find()` query will fail until the document is removed.

### Steps to reproduce

Given 2 entities:

```ts
@Entity()
export class Post {
    @ObjectIdColumn()
    _id?: ObjectId

    @Column(() => Comment)
    comments!: Comment[]
}
```

```ts
export class Comment {
    @Column({ type: 'string' })
    content!: string;
}
```

```ts
const dataSource = new DataSource({
    type: 'mongodb',
    entities: [Post]
});

await dataSource.initialize();
console.log('Connected!');

const repo = dataSource.getMongoRepository(Post);
await repo.clear();
await repo.find({}).then((posts) => console.log(posts));

const entityPost = new Post();
const entityComment = new Comment();
entityComment.content = "Meow";
entityPost.comments = [entityComment];
await repo.save(entityPost);
await repo.find({}).then((posts) => console.log(posts));

const repoPost = repo.create({
    comments: [{
        content: 'Moo'
    }]
});
await repo.save(repoPost);
await repo.find({}).then((posts) => console.log(posts));

// Any .find() after this point fails.

await dataSource.destroy();
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Windows 11     |
| Node.js version     | v18.17.1  |
| Typescript version  | 4.9.5 & 5.1.6  |
| TypeORM version     | 0.3.17  |
| MongoDB version     | 5 & 6  |

### Additional Context

Possibly related to https://github.com/typeorm/typeorm/issues/9049

Looking inside the database, it looks like the entity pattern (top) creates documents in a different format than the repository pattern (bottom)
![image](https://github.com/typeorm/typeorm/assets/3472373/5ebdd63b-81d5-44a4-a116-6681e63b9e4c)

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [X] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by Ionaru** [comment]
I've created a PR containing failing tests to demonstrate this issue: https://github.com/typeorm/typeorm/pull/10392

**Comment by Ionaru** [comment]
I'll need to re-test this with the latest versions of the lib, but I think it is still a problem.

**Comment by gioboa** [comment]
Thanks for the feedback, let me know if it's solved with the latest release. Thanks.

**Comment by Ionaru** [comment]
I'm sorry this took so long.

I've ran a new test and I can still reproduce the issue with TypeORM v0.3.28.
The tests from https://github.com/typeorm/typeorm/pull/10392 are still valid too.

Here is the updated stacktrace:

```
TypeError: document[embedded.prefix].map is not a function
    at C:\Users\Jeroen\Projects\typeorm-test\node_modules\typeorm\query-builder\transformer\DocumentToEntityTransformer.js:91:79
    at Array.forEach (<anonymous>)
    at addEmbeddedValuesRecursively (C:\Users\Jeroen\Projects\typeorm-test\node_modules\typeorm\query-builder\transformer\DocumentToEntityTransformer.js:87:23)
    at DocumentToEntityTransformer.transform (C:\Users\Jeroen\Projects\typeorm-test\node_modules\typeorm\query-builder\transformer\DocumentToEntityTransformer.js:124:9)
    at C:\Users\Jeroen\Projects\typeorm-test\node_modules\typeorm\query-builder\transformer\DocumentToEntityTransformer.js:23:49
    at Array.map (<anonymous>)
    at DocumentToEntityTransformer.transformAll (C:\Users\Jeroen\Projects\typeorm-test\node_modules\typeorm\query-builder\transformer\DocumentToEntityTransformer.js:23:26)
    at C:\Users\Jeroen\Projects\typeorm-test\node_modules\typeorm\entity-manager\MongoEntityManager.js:558:42
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

**Comment by alumni** [comment]
Probably fixed by https://github.com/typeorm/typeorm/pull/10940

**Comment by gioboa** [comment]
@Ionaru can you try the [preview release](https://github.com/typeorm/typeorm/pull/10940#issuecomment-3709542197) of that PR please?
So I'm closing this, but let us know if it's still an issue for you.

**Comment by Ionaru** [comment]
I have re-tested with the preview version `https://pkg.pr.new/typeorm/typeorm@10940` and still have the same error.

The full reproduction code is in the zip file below.

[10391.zip](https://github.com/user-attachments/files/24452100/10391.zip)

To run:
1. Unzip
2. Run mongodb (`docker compose up mongodb -d`)
3. Install dependencies (`npm ci`)
4. Run the script (`npm start`)

**Comment by gioboa** [comment]
Thanks @Ionaru  for your check.
