### ISSUE TITLE
find with relations not working, correct syntax causes type error

### ISSUE THREAD

**Issue by mrkmg** [typeorm/typeorm#1055]
Given the following entities:

```
@Entity()
class Parent {
  @PrimaryGeneratedColumn()
   public id: number;

   @Column()
   name: string;

  @OneToMany(target => Child, child => child.parent)
  children: Child[];
}

@Entity()
class Child {
  @PrimaryGeneratedColumn()
  public id: number;

  @Column()
  name: string
  
  @ManyToOne(target => Parent, parent => parent.id)
  parent: Parent;
}
```

When trying to perform a find model by a relation:

```
const parent = await Parent.findById(1);
const children = await Child.find({parent});
```

In this example, I get a runtime error: `TypeError: Cannot read property '0' of undefined`.

I was able to perform the lookup by doing:

```
const parent = await Parent.findById(1);
const children = await Child.find({parent: parent.id});
```

In this example, I get a build-time error: "TS2345: Argument of type '{ parent: number; }' is not assignable to parameter of type 'DeepPartial<Parent>'."

*I am aware that I can do `await parent.children`, but that is not working either. It appears in general, the 0.1 release broke a lot of relation stuff.*

**Comment by pleerock** [comment]
> It appears in general, the 0.1 release broke a lot of relation stuff.

the only notable things 0.1.0 release broke are cascades and inheritance patterns support, which Im planning to fix in next version. I don't think 0.1 broke things in relations, but I don't rule out the possibility of bugs for sure.

> const parent = await Parent.findById(1);
const children = await Child.find({parent});

I'll check it

> const parent = await Parent.findById(1);
const children = await Child.find({parent: parent.id});

right, its now supported anymore. Previously it worked only because it was accidentally working, it wasn't by design.

**Comment by pleerock** [comment]
Im looking at your tests and it looks like you are using lazy relations there, but here you were talking about non-lazy relations.

**Comment by pleerock** [comment]
I should understand all consequences using lazy relations. They are very specific in node.js.

There were both your and typeorm issues in your code. In this c3dab948334b83dbbd7a7e645f71c92c5beb4a90 commit I fixed your test and was able to execute only one test case out of 3. Actual fix is:

```ts
@ManyToOne(target => Parent, parent => parent.id, { lazy: true })
public parent: Promise<Parent>|Parent|number;
```

If you want to query by parent you this way: `find({ parent: 1 })` you need to change your parent signature to `Promise<Parent>|number` to indicate that parent can be not only object but also a number. This change force you to manually mark relation as lazy since typescript cannot inter Promise in refelection since parent type is a mixed object.

Other test cases I decided to fix in `next` brunch since fix was needed in serious changes which were already made in `next` branch.

I think this issue can be closed now, please let me know if you have questions.

**Comment by osmanzeki** [comment]
For reference I was still getting these issues, it seems like TypeScript gets confused as to which of "FindManyOptions" vs "FindConditions" we are sending to the `find` method. Doing the following calms the type errors down:

```typescript
// Get the 10 largest donations
const options: FindManyOptions = {
    relations: ["user"],
    order: {
        amount: "DESC"
    },
    take: 10
};

const donations = await this.donationRepository.find(options);
```

**Comment by DevelGitH** [comment]
@osmanzeki I got the same behaviour. Thanks for your solution to calm down the typescript compiler.
