### ISSUE TITLE
QueryFailedError: read ECONNRESET

### ISSUE THREAD

**Issue by asijoumi** [typeorm/typeorm#10872]
### Issue description

The communication between the server and mysql is reseting

### Expected Behavior

Hi ! 

I have a very strange issue. Sometimes, my connections are reseting. I don't really now if its an typeorm issue or something missing on mysql.

### Actual Behavior

```
QueryFailedError: read ECONNRESET
    at Query.onResult (/usr/src/app/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at PoolConnection._notifyError (/usr/src/app/node_modules/mysql2/lib/connection.js:228:21)
    at PoolConnection._handleFatalError (/usr/src/app/node_modules/mysql2/lib/connection.js:183:10)
    at PoolConnection._handleNetworkError (/usr/src/app/node_modules/mysql2/lib/connection.js:196:10)
    at Socket.emit (node:events:517:28)
    at Socket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### Steps to reproduce

Don't know

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 18.20.2  |
| Typescript version  | 5.1.3  |
| TypeORM version     | 0.3.20  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by Ginden** [comment]
As you can see in stack trace, it's likely a MySQL issue, not TypeORM one.

I can see few relatively new issues on mysql2 repo, regarding `ECONNRESET` - https://github.com/sidorares/node-mysql2/issues/2599

Are you using version `3.3.2` or newer of `mysql2`?

**Comment by niels-van-den-broeck** [comment]
@asijoumi  I created the issue on mysql2, would be nice if you could check if version 3.3.1 of mysql2 still has this issue so we can get some traction over there.

**Comment by asijoumi** [comment]
@niels-van-den-broeck, I will test it on my dev environment. I will keep you informed as soon as possible.

PS : I don't have this issue for my local environment, only for my dev/staging/prod ...

**Comment by niels-van-den-broeck** [comment]
Could you comment on the mysql2 issue that you are facing the same issue perhaps? Could help identify the issue

**Comment by asijoumi** [comment]
Done !

Thank you, I close this issue 👍

**Comment by hellohejinyu** [comment]
@asijoumi Hi, did you get everything working properly after using the bugfix version of mysql2? I still have this problem even if I use the latest mysql2, but everything works fine if I use `3.3.1`.

**Comment by asijoumi** [comment]
Hi @hellohejinyu , I use this version `"[mysql2](https://npmjs.com/package/mysql2)": "[^3.3.1](https://npmjs.com/package/mysql2)",` and everything works fine 😄 

In my package-lock.json : 

```json
"node_modules/mysql2": {
      "version": "3.3.1",
      "resolved": "https://registry.npmjs.org/mysql2/-/mysql2-3.3.1.tgz",
      "integrity": "sha512-UD84/AvLwO5qmSABEsBTZ7y7JKv3sM8JzWGhuL4tDkJwVsClVVAcelNSR5Unyhxj6/KHBAkjS7qe5/c+gEmNvA==",
      "dependencies": {
        "denque": "^2.1.0",
        "generate-function": "^2.3.1",
        "iconv-lite": "^0.6.3",
        "long": "^5.2.1",
        "lru-cache": "^8.0.0",
        "named-placeholders": "^1.1.3",
        "seq-queue": "^0.0.5",
        "sqlstring": "^2.3.2"
      },
      "engines": {
        "node": ">= 8.0"
      }
    },
```

**Comment by niels-van-den-broeck** [comment]
You can update to latest if you pass `maxIdle: 0` to your pool.
