### ISSUE TITLE
Single table inheritance

### ISSUE THREAD

**Issue by TylerDev6** [typeorm/typeorm#116]
Hi @pleerock, I'm trying to implement single-table and getting the ER_DUP_KEY problem...

I've stripped everything out and this is what I've got left:

```typescript
@Table("game_event")
@TableInheritance("single-table")
@DiscriminatorColumn({ name: "type", type: "string" })
export class GameEventEntity extends EntityTable {
	@Column("simple_array")
	public onIce: PlayerEntity[];
	@ManyToOne(type => GameEntity, gameEntity => gameEntity.events)
	public game: GameEntity;
}
```

then my child table class is like so....

```typescript
@SingleTableChild()
@DiscriminatorValue("player")
export class PlayerEventEntity extends GameEventEntity {
	@OneToOne(type => PlayerEntity)
	@JoinColumn()
	public player: PlayerEntity;
}
```

**Comment by TylerDev6** [comment]
EntityTable is an abstract table with id and creation date columns

**Comment by TylerDev6** [comment]
ER_DUP_KEY: Can't write; duplicate key in table '#sql-2c1e_458'

**Comment by pleerock** [comment]
only simple cases of single/class table inheritance is supported right now. If your single/class table class inheritance extends something or there are something between them extending - such cases were not developed yet. single/class table inheritance is a complicated feature, and any works in this direction requires much efforts. I'll left this issue for the future.

**Comment by TylerDev6** [comment]
Does the error provide any hint or suggestion as to what may be wrong with it?

**Comment by eduardoweiland** [comment]
I had a problem with single table inheritance recently (#111). I've seen the error reported by @TylerDev6 but it only happens when creating the schema (if enabled by `autoSchemaSync: true`). The above code should be working if the database is already created and autoSchemaSync is disabled.

I am also using an abstract table as parent for my models with single table inheritance and it works. In fact, I am using two level of abstract tables without problems :)

```js
@AbstractTable()
export abstract class BaseModel {
    // ...
}

@AbstractTable()
export abstract class CompanyAware extends BaseModel {
    // ...
}

@Table('devices')
@TableInheritance('single-table')
@DiscriminatorColumn({ name: 'type', type: 'string' })
export abstract class Device extends CompanyAware {
    // ...
}

@SingleTableChild()
@DiscriminatorValue('ChargeDetector')
export class ChargeDetector extends Device {
    // ...
}
```

**Comment by TylerDev6** [comment]
Thanks @eduardoweiland! I'll try it out :)

**Comment by TylerDev6** [comment]
@eduardoweiland my build script drops the DB beforehand so I know it doesn't already exist. I've tried playing with "autoSchemaSync" and "dropSchemaOnConnection" and I still can't get it to work.

**Comment by TylerDev6** [comment]
@eduardoweiland can I see your connection script?

**Comment by eduardoweiland** [comment]
There is nothing special.

```typescript
import 'reflect-metadata';
import 'es6-shim';

import * as config from 'config';
import * as _ from 'lodash';
import { createConnection as databaseConnect, ConnectionOptions } from 'typeorm';

export class Application {
  // ... other code that runs connectDatabase()

  public connectDatabase(): Promise<void> {
    const dbConfig: ConnectionOptions = config.get<ConnectionOptions>('database');

    let defaultOptions = {
      logging: {
        logger: databaseLogger
      }
    }

    return databaseConnect(_.merge<ConnectionOptions>({}, dbConfig, defaultOptions));
  }
}
```

I use [config](https://www.npmjs.com/package/config) to load database configuration. My config file looks like this:

```yaml
database:
  driver:
    type: mysql
    host: 127.0.0.1
    port: 3306
    username: theusername
    password: thepassword
    database: thedatabase
    extra:
      timezone: utc
  entities:
    - build/entity/*.js
  logging:
    logFailedQueryError: true
    logQueries: true
    logSchemaCreation: true
```

I use migrations to manage my database, so I don't need `autoSchemaSync`.

**Comment by TylerDev6** [comment]
ok, thanks for that input. I'll see if I can figure out where mine is going wrong....

**Comment by eduardoweiland** [comment]
Seems like TypeORM tries to create the schema for all single table children, and then somehow it tries to create an index with a duplicated name... need to test further to find the problem. :confused:

**Comment by pleerock** [comment]
This issue is obsolete and lot of changes has been made, most of STI works in `0.2.0-alpha.11`. Please create a new issue with problem reproduction in newest versions.
