### ISSUE TITLE
Manually apply decorators

### ISSUE THREAD

**Issue by SamuelMarks** [typeorm/typeorm#1219]
I have these kind of [decorators](http://typeorm.io/#/listeners-and-subscribers):
```typescript
@Entity('user_tbl')
export class User {
    @BeforeInsert()
    hashPassword() {}
```

Combining this with the `save` method, and no errors are made on unique inserts.

To fix this, I refer to your previous solution to my https://github.com/typeorm/typeorm/issues/1159

Which suggests `insert`; but that doesn't run my decorator. Is there a helper function or param to do this for `insert`?

**Comment by pleerock** [comment]
usually people don't need to use `insert` method - `save` is what you must use in 95% of cases in ordinary work with orm. Can you tell me why do you use insert instead of save? (don't refer to my suggestion it was based on your strange request)

**Comment by SamuelMarks** [comment]
@pleerock So with this model I have a `/api/user` route for folks to POST to.

It's expected that this creates a new database user; or throws a unique violation error if it exists.

However, it doesn't error at all. Given the same primary key value, it always succeeds. E.g.: changing the password field and happens without error. So if this goes live, anyone can change anyones passwords!

**Comment by pleerock** [comment]
I guess you need something like this:

```ts
export class UserController {

    @Post("/user")
    save(@Body() newUser: User) {
           if (newUser.id)
                  throw new HttpError(`You can save only a new user!`);

           return getRepository(User).save(newUser);
    }

}
```

**Comment by SamuelMarks** [comment]
But how do I know if that user hasn't already been inserted?

Do I need to run a `find` query now also?!

`.id` would only work if we're talking about a single javascript object. When we're talking about database things get different

**Comment by pleerock** [comment]
Usually if id is generated having an id in user object means its not a new object. For something more complex you need to use find and thats totally fine in your case

**Comment by SamuelMarks** [comment]
Updated my scaffold. Here is my [model](https://github.com/SamuelMarks/restify-orm-scaffold/blob/master/api/user/models.ts) and [route](https://github.com/SamuelMarks/restify-orm-scaffold/blob/master/api/user/sdk.ts).

It seems like a common use-case to:

  0. POST data to a route
  1. That is prepared with `beforeInsert()` decorators called
  2. Unique violation error is possible on insert into database

Current behaviour is unexpected (`.save`):

  0. POST data to a route
  1. Prepare with `beforeInsert` decorators then overwrite whatever was in database with same primary key

XOR with `.insert`:

  0. POST data to a route
  1. Throw unique violation error on double-insert; but don't run `beforeInsert` decorators

**Comment by pleerock** [comment]
Please provide a simplified example without async and other dependencies

**Comment by SamuelMarks** [comment]
Model:
```typescript
@Entity('user_tbl')
export class User {
    @PrimaryColumn({ type: 'varchar' })
    public username: string;

    @Column({ type: 'varchar', nullable: false, select: false })
    public password: string;
}
```

Run this code twice:
```typescript
const user = new User();
user.username = 'foo';
user.password = Math.random();
connection.manager
          .getRepository(User)
          .save(user)
          .then(() => console.info('inserted:', user, ';'))
          .catch(console.error.bind(console));
```

Now the password will be set to the latest value of `Math.random()`; instead of throwing a unique violation error.

**Comment by pleerock** [comment]
I already told you its expected behaviour since `save` updates your model next time you save it. You need to execute a find and throw exception before save and everything will work as you want.

**Comment by SamuelMarks** [comment]
@pleerock So now I need to do two queries for every insert? - Do I need to wrap it in a transaction also, in case a user is deleted in between when an insert is attempted?

Seems rather heavy-handed to replicate normal insert functionality.

and if I use `.insert` then I miss out on the `@BeforeInsert` decorators 👎

**Comment by SamuelMarks** [comment]
@pleerock So how do I manually call the decorators; thus producing a new row object with everything parsed and ready to be `.insert`ed?

Looking through your codebase I found:
```typescript
async broadcastBeforeInsertEvent(manager: EntityManager, subject: Subject): Promise<void> {

    const listeners = subject.metadata.listeners
        .filter(listener => listener.type === EventListenerTypes.BEFORE_INSERT && listener.isAllowed(subject.entity))
        .map(entityListener => subject.entity[entityListener.propertyName]()); // getValue() ?

    const subscribers = this.connection.subscribers
        .filter(subscriber => this.isAllowedSubscriber(subscriber, subject.entityTarget!) && subscriber.beforeInsert)
        .map(subscriber => subscriber.beforeInsert!({
            manager: manager,
            entity: subject.entity
        }));

    await Promise.all(listeners.concat(subscribers));
}
```

But it's not immediately clear to me how I can manually subscribe to it. Looking for a syntax like:

```typescript
const user = new User();
user.username = 'foo';
user.password = 'bar';
User
  .subscribe((f_event: beforeInsertEvent) =>  f_event(user))
  .subscribe((f_event: beforeUpdateEvent) => f_event(user))
```

Or even just some way of getting all the functions that have that decoration. Then I can do this manually.

Hmm, will read into reflect-metadata and the typescript compiler API and see if I can't parse it out myself

**Comment by pleerock** [comment]
Looks like the issue was resolved. Reopen if have something to add.

**Comment by SamuelMarks** [comment]
@pleerock No, the issue isn't resolve. I still can't see an easy way of manually applying decorators.
