### ISSUE TITLE
`getRepository(T).save(TItems[])` not returning actual saved values on upsert

### ISSUE THREAD

**Issue by ps2goat** [typeorm/typeorm#1732]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.1.14` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I have Entity A, with a Many-to-One relationship with Entity B.  Basically, every entity has a status id, that relates to a status object.  I do not have the reverse One-to-Many relation, as that would just be huge.

This is on my base entity, and things load as expected:
```@ManyToOne(type => Status, status => status.id)
    public status: Status;
```
When I use `let x: myType[] = await getRepository(myType).save(myItemArray);`, the items returned do have the updated values, but the child status records are not updated.  I have cascade disabled on this property so it doesn't update in the database (as expected), but the items returned will still have new values in them that don't exist in the database.

For example, I pass in the following item to be updated.  `status.name` is currently and remains "Inactive" in the db:

            ```{
                "name": "Item",
                "description": "updated desc...",
                "id": 4,
                "status": {
                    "id": 2,
                    "name": "updated"
                }
            }```

But the same object gets returned.  I would expect the actual db value to return from the call to `save()`, OR don't return any items from the call so I know I have to select them (like the call to `insert()`).  

My expected return value would have been:


            ```{
                "name": "Item",
                "description": "updated desc...",
                "id": 4,
                "status": {
                    "id": 2,
                    "name": "Inactive"
                }
            }```

**Comment by pleerock** [comment]
If cascades are not set then it should not behave this way. But anyway, can you please check your issue on `next`? (npm i typeorm@next) - cascades mechanizm was completely refactored in there and lot of bugs were fixed

**Comment by ps2goat** [comment]
It appears to still happen under `next`: `"typeorm": "^0.2.0-alpha.28"`

**Comment by pleerock** [comment]
then I'll ask a minimal reproduction repo or better a PR with a failing test which confirms this behaviour.

**Comment by ps2goat** [comment]
I have a unit test ready, but I'm unable to push my branch.  Do I need to fork it?

**Comment by ps2goat** [comment]
For sake of speed, I'll just include it here.

Assumes the same file structure as other github issues.
> test/github-issues/1732
>  /Entity/

Status Entity:
```import {Entity} from "../../../../src/decorator/entity/Entity";
import {Column} from "../../../../src/decorator/columns/Column";
import {PrimaryGeneratedColumn} from "../../../../src/decorator/columns/PrimaryGeneratedColumn";

@Entity()
export class Status {
    @PrimaryGeneratedColumn()
    public id: number;

    @Column()
    public name: string;

    @Column()
    public description: string;
}
```

Person Entity:
```import {Entity} from "../../../../src/decorator/entity/Entity";
import {Column} from "../../../../src/decorator/columns/Column";
import {PrimaryGeneratedColumn} from "../../../../src/decorator/columns/PrimaryGeneratedColumn";
import {ManyToOne} from "../../../../src/decorator/relations/ManyToOne";

import { Status } from './Status';

@Entity()
export class Person {
    @PrimaryGeneratedColumn()
    public id: number;

    @Column()
    public name: string;

    @Column()
    public description: string;

    @ManyToOne(type => Status, status => status.id, {eager: true})
    public status: Status;
}
```

Unit Test:

```import "reflect-metadata";
import {closeTestingConnections, createTestingConnections} from "../../utils/test-utils";
import {reloadTestingDatabases} from "../../utils/test-utils";
import {Connection} from "../../../src/connection/Connection";
import {Person} from "./entity/Person";
import {expect} from "chai";
import {Status} from "./entity/Status";

describe("github issues > #1732 getRespository().save() returns the wrong data for nested values when relation is read-only", () => {

    let connections: Connection[];
    before(async () => connections = await createTestingConnections({
        entities: [__dirname + "/entity/*{.js,.ts}"],
        schemaCreate: true,
        dropSchema: true
    }));
    beforeEach(() => reloadTestingDatabases(connections));
    after(() => closeTestingConnections(connections));

    it("should persist successfully and return persisted entity", () => Promise.all(connections.map(async connection => {

        // create objects to save
        const activeStatus = new Status();
        activeStatus.name = "Active";
        activeStatus.description = "The record is active.";

        const disabledStatus = new Status();
        disabledStatus.name = "Disabled";
        disabledStatus.description = "The record is not active.";
        
        // save statuses before creating people.
        await connection.manager.save([activeStatus, disabledStatus]);

        const person = new Person();
        person.name = "John";
        person.description = "Developer";
        person.status = activeStatus;
        
        await connection.manager.save(person);


        // check that all persisted objects exist
        const loadedPerson = await connection.manager.getRepository(Person).findOneById(1);

        expect(loadedPerson).not.null;
        const personStatus = loadedPerson!.status;
        expect(personStatus).not.null;
        expect(personStatus!).not.to.be.empty;
        personStatus!.id.should.equal(1);
        personStatus!.name.should.equal(activeStatus.name);
        personStatus!.description.should.equal(activeStatus.description);


        const loadedStatuses = await connection.manager
            .createQueryBuilder(Status, "status")
            .orderBy({id: "ASC"})
            .getMany();

        expect(loadedStatuses.length).to.equal(2);

        const loadedStatus1 = await loadedStatuses[0];
        expect(loadedStatus1!).not.to.be.empty;
        loadedStatus1!.id.should.equal(1);
        loadedStatus1!.name.should.equal(activeStatus.name);
        loadedStatus1!.description.should.equal(activeStatus.description);

        const loadedStatus2 = await loadedStatuses[1];
        expect(loadedStatus2!).not.to.be.empty;
        loadedStatus2!.id.should.equal(2);
        loadedStatus2!.name.should.equal(disabledStatus.name);
        loadedStatus2!.description.should.equal(disabledStatus.description);
        
        // all schema and data created properly. Now test updating. 
        
        // make the person now have an updated status of 'disabled', with an invalid name for the status.
        loadedPerson!.name = "Jake";
        loadedPerson!.status = disabledStatus;
        loadedPerson!.status.name = "garbage";
        
        const personSaveResult: Person | undefined = await connection.manager.save(loadedPerson);

        console.log('saved result: %o', personSaveResult);

        expect(personSaveResult).not.undefined;
        expect(personSaveResult!.status).not.undefined;


        // try reloading the status to verify that the name was not updated in the db.
        const statuses = await connection.manager.getRepository(Status).find() || [];

        expect(statuses.length).equals(2);

        expect(statuses[0]!.name).not.equals("garbage");
        expect(statuses[1]!.name).not.equals("garbage");


        // reload the person entity DIRECTLY from the database.
        const reloadedPerson: Person | undefined = await connection.manager.getRepository(Person).findOneById(1);

        expect(reloadedPerson).not.undefined;
        expect(reloadedPerson!.status).not.undefined;
        expect(reloadedPerson!.status!.name).not.equals("garbage");
        expect(reloadedPerson!.status!.name).equals("Disabled");  

        // This is where it blows up-- the name returned is the invalid name that was not committed to the database.
        expect(personSaveResult!.status!.name).equals("Disabled", "The status object should not have been updated, only the person's status id.");     
    })));

});
```

**Comment by pleerock** [comment]
For sake of speed to me please create a PR with a failing test. I see issues in your code like `status => status.id` is a wrong since second parameter of relation must be inverse side. If you don't have inverse side you simply don't specify it. 

Please create a PR against `next` branch and let's continue discussion there if you do it.

**Comment by may215** [comment]
I am having the same issue, I am using the latest version: 0.2.7
What should I do, I can't save objects and get the real values out of it

**Comment by ps2goat** [comment]
@may215 I switched to using [Objection.js](https://github.com/Vincit/objection.js) since they have support for updating via graphs.  My original issue with TypeORM was in version 0.1.x, and a new project I started was using 0.2.x-- the 0.2.x has a lot of issues with it that weren't worth waiting for (we can't wait with this project).  The most notable issue that made it a deal-breaker for me was typeORM didn't expect new objects when updating an existing parent object, and it blew up.  There are (were?) other issues such as extended updates also performing insert statements, which also made it blow up for me.

I like TypeORM and its ease of configuration, and would like it to succeed, but it was lacking what I consider to be basic ORM functionality.

**Comment by pleerock** [comment]
@ps2goat Im sorry you got such a bad experience working with typeorm. That happens in software development. Im sure if you got it a bit different way you would never switch to something else.

**Comment by ps2goat** [comment]
@pleerock I'm interested in it, still! I'll keep checking in from time-to-time :)  We still use a lot of your other tools -- routing-controllers, class-validator, etc.

**Comment by pleerock** [comment]
refer to github issues you are talking about.

**Comment by mxs42** [comment]
This is just dumb that I can't work with entity fields after triggering save.

**Comment by darkyelox** [comment]
I was expecting the same behavior, lucky i use RXJs and after a save i have to do a findOne and eager:true in the relations, it's a shame and i think this issue must be reopened because the save method return a promise of the entity and for everyone is a fact expecting the updated entity from the db (a select after the update when the entity already exists)

**Comment by pleerock** [comment]
Issue was closed because no-one provided a reproduction - PR with a failing test with minimal reproduction code. If somebody face this issue - please provide a reproduction.
