### ISSUE TITLE
datetime column showing changed on every schema:sync run

### ISSUE THREAD

**Issue by ktwbc** [typeorm/typeorm#2333]
**Issue type:**

[ ] question
[ X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ X] `0.2.6` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
1. Create new entity file:

```
import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';


@Entity('test')
export class Test {

  @PrimaryGeneratedColumn()
  id: number;

  @Column({type: 'datetime', nullable: true, default: null})
  publish_date: Date;

}

```
2. Run command schema:sync
Initial run of command shows:
```
CREATE TABLE `test` (`id` int NOT NULL AUTO_INCREMENT, `publish_date` datetime NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB
```
3. Confirm table has been created
4. Run schema:sync again

Run will show an alter table erroneously (and will repeat on every run)
```
ALTER TABLE `test` CHANGE `publish_date` `publish_date` datetime NULL
```
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql` 5.6.36 on Mac (installed with homebrew)
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by iamwindy** [comment]
try using
`
@Column({ precision: 6,type: "timestamp", nullable: true })
  public deletedAt?: Date;
`
for the meantime, it will not fetch changes for now

**Comment by ktwbc** [comment]
still doing it, just different statement when it runs each time but is updating it over and over, even though the db actually updated on the first sync

columns changed in "applicants". updating: publish_date
query: ALTER TABLE `applicants` CHANGE `publish_date` `publish_date` timestamp(6) NULL

**Comment by ktwbc** [comment]
```
{precision: 6, type: 'timestamp', nullable: true}
```
worked without default:null on this variation.

**Comment by iamwindy** [comment]
i know, thats why i told you to use that :D

**Comment by ManuelMolina97** [comment]
Got the same problem but a bit different:

``` typescript
    @Column({
        name: "datefield",
        type: "timestamp",
        default: () => "CURRENT_TIMESTAMP",
        precision: 6,
    })
    private datefield: Date;
```

**Typeorm version: 0.2.7**
**Database driver: mysql / mariadb**


Any ideas what can be changed?

**Comment by gregwym** [comment]
I think this is related to https://github.com/typeorm/typeorm/issues/2737. The issue is related to  `findChangedColumns`.

**Comment by gregwym** [comment]
These two work for me. 
```
@Column('timestamp', { precision: 6, nullable: true })
@Column('timestamp', { precision: 6, default: () => 'CURRENT_TIMESTAMP(6)' })
```

You can also make it not nullable and without default, but you have to turn on `explicit_defaults_for_timestamp` in MySQL variables.

**Comment by ivan-kleshnin** [comment]
Dunno if it's related but for me:

```
@Column("boolean", {
    default: "false",
  })
```

causes

```
query: ALTER TABLE "card" ALTER COLUMN "done" SET DEFAULT 'false'
```

each time I start an app.

**Comment by gregwym** [comment]
@ivan-kleshnin try 
```
@Column("boolean", { default: () => "false" })
```

**Comment by ooptimum** [comment]
`@Column({ precision: 6, type: "timestamp", nullable: true })` fixes the issue for me.
However, if such a field has an index, this index is recreated every time the database scheme is synchronized.

**Comment by mathewmeconry** [comment]
`@Column({ precision: 6, type: "timestamp", nullable: true })` fixed the issue for me too.
I used before `@UpdateDateColumn()` which cause the infinte update too.

Additionally I was able to reproduce the error with `@Column('datetime')` which has the same workaround as the timestamp field `@Column('datetime', { precision: 6 })`

**Comment by jordancue** [comment]
This is occurring for me on AWS Aurora running MySQL 5.7, but NOT on my local which is running MySQL 8 -- hopefully this will help narrow down the issue.

Occurred with Typeorm 0.2.12, haven't tested with 0.2.16 yet.

**Comment by AlexMesser** [comment]
I've added a test and it looks like this issue was already fixed. Please reopen it if you face this error again.

**Comment by lazaroofarrill** [comment]
I'm still facing the same issue, I've tried all approaches described before in this thread.

mysql  Ver 8.0.26-0ubuntu0.21.04.3 for Linux on x86_64 ((Ubuntu))
typeorm: 0.2.35

**Comment by imnotjames** [comment]
Please open a new issue if you're seeing this.
