### ISSUE TITLE
Typeorm singleton with serverless-offline

### ISSUE THREAD

**Issue by ktwbc** [typeorm/typeorm#2623]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Crossposting https://github.com/dherault/serverless-offline/issues/468 hoping someone might have some insight. Using TypeOrm with the Serverless.com framework and serverless-offline to develop my lambda functions locally. On the actual deploy code, the singleton works fine but serverless-offline causes issues with this. 

Since I'm using Typeorm, serverless, serverless-typescript and serverless-offline this is just trying to make all these packages work together, hoping someone has run into this before and knows the secret.

**Comment by otbe** [comment]
Same issue here. 

At the moment I work around this issue by using a different (random) connection name for each invocation of the Lambda which works somehow, but after some time I get "too many connections" by MySQL. Is there a better workaround?

--skipCacheInvalidation (mentioned in the linked serverless-offline issue) works but then it stops refreshing my code on changes. 😭

**Comment by Kononnable** [comment]
> too many connections

Do you close connection when you finish? Some folks had similar errors with lambda and often they just forgot to close connection with database.

**Comment by otbe** [comment]
At the moment I dont manage connections by myself.  I create the connection outside of my lambda handler function and set `callbackWaitsForEmptyEventLoop` explicitly to false which allows that API Gateway finishs the request and keep the connection (pool) inside the lambda container alive as long as the container itself is alive (aka warm lambda). This may limit the number of concurrent invoked lambdas (due to max connection settings) but it keeps latency down for subsequent requests.

**Comment by Kononnable** [comment]
I'm not very familiar with lambdas but what happens when container is going to be destroyed? If connection isn't closed when that happens mysql might think that it is still alive and keep it for some time. The solution would be to capture an event of stopping container(if there is any) and closing connection to database before container is stopped.

**Comment by otbe** [comment]
Thats a good question. In my expectation the container is destroyed by the lambda runtime and the db connection is stalled. After a specific time mysql (aurora in my usecase) closes the connection. 

In order to solve the issue related to serverless-offline I tried to add a global `process.on('exit', ...)` but it wont be called while using offline mode nor in the lambda environment.
I followed this https://github.com/aws-samples/aws-lambda-manage-rds-connections and set the connection pool size to one and hoped the DBMS will handle it properly.

**Comment by Kononnable** [comment]
You can also check if there is a server configuration option specifying timeout before connection is closed. It could lower number of stalled connections.

`process.on('exit', ...)` can only make synchronous calls, so it might be to late to talk with db. Try `process.on('SIGTERM', ...)`. According to [docker documentation](https://docs.docker.com/engine/reference/commandline/stop/#extended-description) before stopping a container SIGTERM is send.

**Comment by ktwbc** [comment]
> Thats a good question. In my expectation the container is destroyed by the lambda runtime and the db connection is stalled. After a specific time mysql (aurora in my usecase) closes the connection.
>
Yes that's my experience too. The connection basically goes to sleep (you can see Sleep as a status in "show processlist") and is eventually closed when the timeout rolls around. 

For serverless-offline I eventually solved this with some code I found about making your own container Id with a timestamp. In an actual lambda container deployed, we're setting it outside the handler therefore it will survive and reuse the connection. Locally I cheat and just keep creating connections, but I'm just one person on a dev machine and my timeout is fairly short locally so I don't really care if every time I run it it creates 10 connections because they fall off pretty  quickly anyway.

```

let containerId = Date.now().toString().slice(-6);
let runLocal = false;

export default class Database {

  private credentials: DatabaseCredentials;
  private dbConnection: Connection|undefined;

  constructor() {
    if (process.env.IS_OFFLINE) {
      const currentDate = moment();
      containerId = 'L' + currentDate.valueOf() + Math.random();
      runLocal = true;
    }
    this.credentials = new DatabaseCredentials();
  }

  async getDb(): Promise<Connection> {

    if (this.dbConnection) {
      try {
        return getConnection(containerId);
      } catch (e) {
        console.log('got error finding connection');
        this.dbConnection = undefined;
      }
    }

    let creds: ConnectionOptions = await this.credentials.get();
    this.dbConnection = await createConnection(creds);

    return this.dbConnection;
  }

}
```

**Comment by otbe** [comment]
@Kononnable good idea, I configured my local mysql with a `wait_timeout` of 60s which solves my initial issue. Thanks 👍

@ktwbc I do something very similar for my local devlopment. Thanks too!

**Comment by DennisKo** [comment]
So I am having similiar problems. I am using this db manager class to handle connections:

```
import {
  Connection,
  ConnectionManager,
  ConnectionOptions,
  createConnection,
  getConnectionManager
} from "typeorm";
import User from "./entity/User";


export default class Database {
  private connectionManager: ConnectionManager;

  constructor() {
    this.connectionManager = getConnectionManager();
  }

  public async getConnection(): Promise<Connection> {
    const CONNECTION_NAME = `default`;
    try {
      let connection: Connection;
      if (this.connectionManager.has(CONNECTION_NAME)) {
        connection = await this.connectionManager.get(CONNECTION_NAME);
        if (!connection.isConnected) {
          connection = await connection.connect();
        }
      } else {
        const connectionOptions: ConnectionOptions = {
          // ...options
          entities: [User]
        };

        connection = await createConnection(connectionOptions);
      }
      return connection;
    } catch (error) {
      console.log("DB CONNECTION ERROR: ", error);
      throw new Error();
    }
  }
}
```

Every first DB call after `serverless offline start` succeeds but when I do another call I get:

```
{ RepositoryNotFoundError: No repository for "User" was found. Looks like this entity is not registered in current "default" connection?
    at new RepositoryNotFoundError (/home/dennis/omagram-api/src/error/RepositoryNotFoundError.ts:10:9)
    at EntityManager.getRepository (/home/dennis/omagram-api/src/entity-manager/EntityManager.ts:730:19)
    at Connection.getRepository (/home/dennis/omagram-api/src/connection/Connection.ts:325:29)
    at Function.BaseEntity.getRepository (/home/dennis/omagram-api/src/repository/BaseEntity.ts:85:27)
    at Function.BaseEntity.create (/home/dennis/omagram-api/src/repository/BaseEntity.ts:140:30)
    at Object.<anonymous> (/home/dennis/omagram-api/.webpack/service/src/webpack:/src/resolvers.ts:34:33)
    at Generator.next (<anonymous>)
    at fulfilled (/home/dennis/omagram-api/.webpack/service/src/api.js:328:58)
  name: 'RepositoryNotFoundError',
  message:
   'No repository for "User" was found. Looks like this entity is not registered in current "default" connection?' }
```

I think I am pretty close to solving this without any dirty hacks but how could I proceed from here?

**Comment by evayde** [comment]
@DennisKo I had the very same Problem and this fixed my Issue:

https://github.com/dherault/serverless-offline/issues/468

Basically start sls offline with `--skipCacheInvalidation` option.

**Comment by rlehrke** [comment]
This solution below from @pueue (from https://github.com/typeorm/typeorm/issues/2598) fixed this for me.

I'm now able to successfully re-use open connections in Lambda functions (both serverless-offline and "live").

```
export const connectDatabase = async (callback: Function = () => {}) => {
  try {
    const connectionManager = getConnectionManager()
    let connection: Connection;

    if (connectionManager.has('default')) {
      console.log('use a connection already connected')
      connection = injectConnectionOptions(connectionManager.get(), connectionOptions)
    } else {
      connection = connectionManager.create(connectionOptions)
      await connection.connect()
    }

    await callback();
    return connection;
  } catch (e) {
    console.log(e);
    throw e;
  }
};

export const injectConnectionOptions = (connection: Connection, connectionOptions: ConnectionOptions) => {
  /**
   * from Connection constructor()
   */

  // @ts-ignore
  connection.options = connectionOptions
  // @ts-ignore
  connection.manager = connection.createEntityManager();
  // @ts-ignore
  connection.namingStrategy = connection.options.namingStrategy || new DefaultNamingStrategy();
  // @ts-ignore
  connection.relationLoader = new RelationLoader(connection);
  // @ts-ignore
  connection.relationIdLoader = new RelationIdLoader(connection);

  /**
   * from Connection connect()
   */
  // @ts-ignore
  connection.buildMetadatas();

  return connection;
}
```

**Comment by JNaeemGitonga** [comment]
`"serverless offline --skipCacheInvalidation` in your npm scripts worked for me

**Comment by jamesmorgan** [comment]
`--skipCacheInvalidation` adding this fixed a very similar issue - worth giving it a go

**Comment by marekm1844** [comment]
In my case "No repository for...." error on Serverless Aurora was caused by `serverless-plugin-optimize` in yml file. After removing this plugin, Lambda was able to connect.  

Any ideas how to use optimize plugin in this case ?

**Comment by Shubhanshu1201** [comment]
We are also facing the same use where i am using typeorm 0.2.18 and postgres aws Aurora RDS with pg version 7.11.0. During connection create for 1st time the query is executing successfully but later at random generating the following error :

`
{ "errorType": "Error", "errorMessage": "Connection terminated unexpectedly", "stack": [ "Error: Connection terminated unexpectedly", " at Connection.con.once (/var/task/node_modules/pg/lib/client.js:252:9)", " at Object.onceWrapper (events.js:286:20)", " at Connection.emit (events.js:198:13)", " at Connection.EventEmitter.emit (domain.js:448:20)", " at Socket.<anonymous> (/var/task/node_modules/pg/lib/connection.js:77:10)", " at Socket.emit (events.js:198:13)", " at Socket.EventEmitter.emit (domain.js:448:20)", " at TCP._handle.close (net.js:607:12)" ] } or Client has encountered a connection error and is not queryable.`

The issue start appearing suddenly after running successfully for a while.

Any help is greatly appreciated.

**Comment by Aminramin8886** [comment]
I 'm using the dbManager to create connections and reuse them and it worked with "serverless offline --skipCacheInvalidation " on my local machine but when I deploy to aws it throws the same error that I was getting before using "--skipCacheInvalidation " and it is because it tries to create connection again and doesnt reuse it. could you please help on this why this is not working on aws lambda free tier , I also enabled the cach option for the apigateway but still it doesnt work and throws below exeption 

**"errorMessage": "Error: Schema must contain uniquely named types but contains multiple types named \"e\".",**

**Database.ts**
`export class Database {
    private connectionManager: ConnectionManager

    constructor() {
        this.connectionManager = getConnectionManager()
    }

    public async getConnection(): Promise<Connection> {
        
        const CONNECTION_NAME = `default`

        let connection: Connection

        if (this.connectionManager.has(CONNECTION_NAME)) {
            console.log(`Database.getConnection()-using existing connection ...`);
            connection = await this.connectionManager.get(CONNECTION_NAME)

            if (!connection.isConnected) {
                connection = await connection.connect()
            }
        }
        else {
            console.log(`Database.getConnection()-creating connection ...`);

            const connectionOptions: ConnectionOptions = {
                "type": "postgres",
                "host": "",
                "port": 5432,
                "database": "postgres",
                "username":"postgres",
                "password":"",
                "synchronize": true,
                "logging": false,
                "name": `default`,
                entities: [ Book
                ]
            }

           
            
            connection = await createConnection(connectionOptions)
        }

        return connection
    }
}`


Index.ts
`require('source-map-support').install();
import 'reflect-metadata';
import { ApolloServer } from 'apollo-server-lambda';
import { typeDefs, resolvers, schemaDirectives } from './definitions';
import * as eventData from './data/eventData';
import * as bookData from './data/bookData';
import * as authorData from './data/authorData';
import * as providerData from './data/providerData';

import { createConnection, Connection } from 'typeorm';
import { buildSchema } from 'type-graphql';
import { BookResolver } from './resolvers/BookResolver';
import { Database } from './Database';

export interface Context {
    eventData: typeof eventData;
    bookData: typeof bookData;
    authorData: typeof authorData;
    providerData: typeof providerData;
    user?: object;
}

const context: Context = {
    eventData,
    bookData,
    providerData,
    authorData,
};

const database = new Database();
let dbConn: Connection;
let counter = 0;

let server = null;

const createHandler = async () => {
    if (!dbConn) dbConn = await database.getConnection();

    if (!server) {
        const schema = await buildSchema({ resolvers: [BookResolver] });
         server = new ApolloServer({
            schema,
            introspection: true,
            playground: true,
        });
    }

    console.log('Server has started!');
    return server.createHandler({
        cors: {
            origin: '*',
            credentials: true,
        },
    });
};

exports.graphqlHandler = (event, context, callback) => {
    context.callbackWaitsForEmptyEventLoop = false;
    createHandler().then(handler => handler(event, context, callback));
};
`


**serverless.yml**

`service: valet-api

plugins:
  - serverless-webpack  
  - serverless-offline
  - serverless-domain-manager


custom:
  webpack:
    webpackConfig: 'Webpack.config.js'
    packager: yarn
    includeModules: true

  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}

  customDomain:
    domainName: 'api.vdev.docudatasoft.com'
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true


provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  stage: ${self:custom.currentStage}

functions:
  graphql:
    handler: src/index.graphqlHandler
    environment:
      SLS_DEBUG: true
    events:
      - http:
          path: graphql
          method: POST
          cors: true
          integration: lambda-proxy
      - http:
          path: graphql
          method: GET
          cors: true
          integration: lambda-proxy
     



`

**Comment by Industrial** [comment]
```
const connectionManager = getConnectionManager()

let _connection: Connection
export async function getConnection(): Promise<Connection> {
  _connection =
    _connection ||
    (connectionManager.has('default') && connectionManager.get('default')) ||
    (await createConnection())

  return _connection
}
```

**Comment by baclv** [comment]
```js
if (config.environment == 'development') {
    try {
        const manager = getConnectionManager();

        if (manager.has(DEFAULT_CONNECTION_NAME)) {
            const connection = manager.get(DEFAULT_CONNECTION_NAME);

            if (connection.isConnected) {
                await connection.close();
                logger.info('Closed connection in development environment');
            }
        }
    } catch (error) {
        logger.error(error);
    }
}
```

**Comment by baclv** [comment]
Same issue here. And I closed existed connection :rofl: 
```js
private static async getDBConnect(retry: number): Promise<Connection> {
    if (config.environment == 'development') {
      try {
        const manager = getConnectionManager();

        if (manager.has(DEFAULT_CONNECTION_NAME)) {
          const connection = manager.get(DEFAULT_CONNECTION_NAME);

          if (connection.isConnected) {
            await connection.close();
            logger.info('Closed connection in development environment');
          }
        }
      } catch (error) {
        logger.error(error);
      }
    }

    try {
      const connection = await createConnection({
        type: 'postgres',
        url: process.env.DATABASE_URL,
        entities: Object.values(entities),
        migrations: Object.values(migrations),
        logging: ['query', 'error'],
      });
      return connection;
    } catch (error) {
      logger.info('ERROR DB connection');
      logger.info(error);

      if (retry < 3) {
        logger.info('Retry DB connection times:', retry++);
        return Database.getDBConnect(retry);
      }

      logger.info('UNHANDLED ERROR DB connection after 3 times');
    }
  }
```

**Comment by imnotjames** [comment]
There are a lot of great solutions here and it seems like more or less this has been resolved.

As such, I'm gonna close this out.  Cheers!

**Comment by ymoran00** [comment]
Just for future generations: `skipCacheInvalidation` doesn't exist anymore in new sls offline. Instead use `--allowCache`.

**Comment by bart** [comment]
@ymoran00 Tried it with `--allowCache` but still getting the `Looks like this entity is not registered in current "default" connection?` error when trying to handle two axios requests in parallel. I'm using the simple singleton solution provided by @Industrial. Any idea?

**Comment by JesusCamaRay** [comment]
I use the nodemon solution from @larrybotha to allowCache in order to use the same connection in every database query and nodemon to reload if there's a file change.

After installing nodemon with npm. 

`npm install --save-dev nodemon`

I wrote these commands in my package.json.

```
"scripts": {
    "nodemon": "nodemon -e js,ts,jsx,tsx --exec \"npm run dev\"",
    "dev": "sls offline start --stage dev --httpPort 5000 --allowCache"
}
```
Finally, i started  my app with

`npm run nodemon`
