### ISSUE TITLE
MSSQL 2017 + Pagination (Limit + Skip) not working

### ISSUE THREAD

**Issue by victorschinaider** [typeorm/typeorm#2858]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

My version of MSSQL:

```
Microsoft SQL Server 2017 (RTM-CU8) (KB4338363) - 14.0.3029.16 (X64) 
	Jun 13 2018 13:35:56 
	Copyright (C) 2017 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 16.04.4 LTS)
```

Find a entity with `skip` and `limit` in MSSQL server is not working.

```
SELECT MesCompetencia, AnoCompetencia FROM "auxilio-saude-v2"."ComprovanteAuxilioSaude" "ComprovanteAuxilioSaudeEntity" OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY
query failed: SELECT MesCompetencia, AnoCompetencia FROM "auxilio-saude-v2"."ComprovanteAuxilioSaude" "ComprovanteAuxilioSaudeEntity" OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY
error: { RequestError: Invalid usage of the option NEXT in the FETCH statement.
    at handleError (/home/schinaider/Documentos/rh-api-v2/node_modules/mssql/lib/tedious.js:546:15)
    at Connection.emit (events.js:182:13)
    at Connection.EventEmitter.emit (domain.js:442:20)
    at Parser.<anonymous> (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/lib/connection.js:611:16)
    at Parser.emit (events.js:182:13)
    at Parser.EventEmitter.emit (domain.js:442:20)
    at Parser.<anonymous> (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/lib/token/token-stream-parser.js:54:15)
    at Parser.emit (events.js:182:13)
    at Parser.EventEmitter.emit (domain.js:442:20)
    at addChunk (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:291:12)
  code: 'EREQUEST',
  number: 153,
  lineNumber: 1,
  state: 2,
  class: 15,
  serverName: 'fc48076461e6',
  procName: '',
  originalError:
   { Error: Invalid usage of the option NEXT in the FETCH statement.
       at handleError (/home/schinaider/Documentos/rh-api-v2/node_modules/mssql/lib/tedious.js:544:19)
       at Connection.emit (events.js:182:13)
       at Connection.EventEmitter.emit (domain.js:442:20)
       at Parser.<anonymous> (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/lib/connection.js:611:16)
       at Parser.emit (events.js:182:13)
       at Parser.EventEmitter.emit (domain.js:442:20)
       at Parser.<anonymous> (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/lib/token/token-stream-parser.js:54:15)
       at Parser.emit (events.js:182:13)
       at Parser.EventEmitter.emit (domain.js:442:20)
       at addChunk (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:291:12)
     info:
      { number: 153,
        state: 2,
        class: 15,
        message: 'Invalid usage of the option NEXT in the FETCH statement.',
        serverName: 'fc48076461e6',
        procName: '',
        lineNumber: 1,
        name: 'ERROR',
        event: 'errorMessage' } },
  name: 'RequestError',
  precedingErrors:
   [ { RequestError: Incorrect syntax near 'OFFSET'.
         at handleError (/home/schinaider/Documentos/rh-api-v2/node_modules/mssql/lib/tedious.js:546:15)
         at Connection.emit (events.js:182:13)
         at Connection.EventEmitter.emit (domain.js:442:20)
         at Parser.<anonymous> (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/lib/connection.js:611:16)
         at Parser.emit (events.js:182:13)
         at Parser.EventEmitter.emit (domain.js:442:20)
         at Parser.<anonymous> (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/lib/token/token-stream-parser.js:54:15)
         at Parser.emit (events.js:182:13)
         at Parser.EventEmitter.emit (domain.js:442:20)
         at addChunk (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:291:12)
       code: 'EREQUEST',
       number: 102,
       lineNumber: 1,
       state: 1,
       class: 15,
       serverName: 'fc48076461e6',
       procName: '',
       originalError: [Error],
       name: 'RequestError' } ] }
```
The result query:

```
query: SELECT MesCompetencia, AnoCompetencia FROM "auxilio-saude-v2"."ComprovanteAuxilioSaude" "ComprovanteAuxilioSaudeEntity" OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY
query failed: SELECT MesCompetencia, AnoCompetencia FROM "auxilio-saude-v2"."ComprovanteAuxilioSaude" "ComprovanteAuxilioSaudeEntity" OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY
```

Piece of code:

```
return await this.repository.find({ take: 2, skip: 0 });
```

**Comment by victorschinaider** [comment]
To use NEXT FETCH, 'ORDER' clause is required. I think Typeorm should raise an exception, or define a default 'ORDER'.

https://stackoverflow.com/questions/19756839/why-cant-i-query-offset-fetch-query-on-my-sql-server

**Comment by vlapo** [comment]
This should be fixed by https://github.com/typeorm/typeorm/pull/3162. Feel free to reopen if there is any problem.

**Comment by eaverdeja** [comment]
I'm still having this problem with SQL Server 2008. Despite changing the Tedious version to the correct one fro SQL Server 2008 (7_3_A), the syntax didn't change. Is there some way SQL Server 2008 can be supported?

**Comment by wrod7** [comment]
im having the same issue with mssql 2008 with typeorm 0.2.14. what version of tedious should I be using?

**Comment by vlapo** [comment]
@eaverdeja @wrod7 https://github.com/typeorm/typeorm/issues/4038#issuecomment-499644935

**Comment by wrod7** [comment]
@vlapo thanks for the note.

**Comment by OliverLeighC** [comment]
I am having an issue with this with mssql 2017, and I'm using the order by clause. 

my typeorm query:

```
results = await personsRepository
        .createQueryBuilder("persons")
        .leftJoinAndSelect("persons.workExperience", "workExperience")
        .leftJoinAndSelect("persons.education", "education")
        .leftJoinAndSelect("persons.employment", "employment")
        .orderBy("persons.createDate", "DESC")
        .where(
          `persons.createDate < ${this.formatDate(cursor, EDateType.Datetime)}`
        )
        .offset(0)
        .limit(limit)
        .getMany();
```

the sql output
```
WHERE \"persons\".\"CreateDate\" < 2020-01-27 01:01:42 ORDER BY \"persons\".\"CreateDate\" DESC OFFSET 0 ROWS FETCH NEXT 20 ROWS ONLY"
```

error: 

"Error: Invalid usage of the option NEXT in the FETCH statement."

**Comment by Metazhoa** [comment]
i have the same problem using `SQL Server 2018 R2` and i used below method to solve it:

please note i created query for the data that i'd like to find, then i encapsulate it with another query for limiting the data.
for example, i want to query user id, username and password from table `users`:
then my statement would be like:
`SELECT 
     users.id, users.username, 
     users.password 
FROM users 
WHERE users.username = 'mikey'`
then to use skip and limit for these statement i add `ROW_NUMBER()` function from SQL Server.
so the statement would look like this:
`SELECT 
     users.id,
     users.username, 
     users.password, 
  -->ROW_NUMBER() OVER (ORDER BY users.id) AS Seq,
FROM users`
running these statement will output like this:
`id | username  | password   | Seq |
--------------------------------------
 1 | crow           | somepass1 | 1
 3 | mike           | somepass2 | 2
 5 | jason          | somepass3 | 3
 4 | allison        | somepass4 | 4
 7 | brewr          | somepass5 | 5
 6 | reqeui         | somepass6 | 6`
now to create skip and limit outputs from sql, i just query the result of the pevious query like:
`SELECT 
     users.id, 
     users.username, 
     users.password 
FROM(
	// Real Query Begin //
	SELECT 
	     users.id,
	     users.username, 
	     users.password, 
  		 ROW_NUMBER() OVER (ORDER BY users.id) AS Seq
  	// Real Query End //
	)users
WHERE Seq BETWEEN 1 AND 8`

now to run these query and complete data presentation using typeORM:
`var query = ""
    let tableName = Users.getRepository().metadata.tableName
    if(filterUser != undefined) {
      var query = \`${tableName}.name LIKE "%${filterUser}%"\`
      if(filterGroup != undefined) {
        query = query + \` AND ${tableName}.groupId = ${filterGroup}\`
      }
    } else {
      if(filterGroup != undefined) {
        query = \`${tableName}.groupId = ${filterGroup}\`
      }
    }
    let connection = getConnection()
    // Supporting Raw Query
    if(connection.options.type == "mssql") {
      take = take + skip
      skip = skip + 1
      if(query.length > 2) query = " WHERE " + query
      let users = await Users.query(\`SELECT 
      "Users"."id", 
      "Users"."name", 
      "Users"."username",
      "Users"."password", 
      "Users"."groupId", 
      "Users__group_id", 
      "Users__group_name"
      FROM (
        SELECT 
        "Users"."id", 
        "Users"."name",
        "users"."username", 
        "Users"."password", 
        "Users"."groupId", 
        "Users__group"."id" AS "Users__group_id", 
        "Users__group"."name" AS "Users__group_name",
        ROW_NUMBER() OVER (ORDER BY "users"."id") AS Seq
        FROM "users" "Users"
        LEFT JOIN "user_groups" "Users__group" 
        ON "Users__group"."id" = "Users"."groupId"
        ${query}
      )"Users"
      WHERE Seq BETWEEN ${skip} AND ${take}\`)
      users = await users.map((user:any) => {
        return {
          id:user.id , 
          name:user.name,
          username:user.username,
          password:user.password,
          groupId: user.groupId,
          group: {
            id: user.Users__group_id,
            name:user.Users__group_name,
          }
        }
      })
      return await Users.getRepository().create(users)
    } else {
      return await Users.find({where:query, relations: ["group"]});
    }`
i think they can create a method to solve this problem.

**Comment by Metazhoa** [comment]
i have the same problem using `SQL Server 2018 R2` and i used below method to solve it

please note i created query for the data that i'd like to find, then i encapsulate it with another query for limiting the data.
for example, i want to query user id, username and password from table `users`
then my statement would be like
```
SELECT 
     users.id, users.username, 
     users.password 
FROM users 
WHERE users.username = 'mikey'
```
then to use skip and limit for these statement i add `ROW_NUMBER()` function from SQL Server.
so the statement would look like this
```
SELECT 
     users.id,
     users.username, 
     users.password, 
  -->ROW_NUMBER() OVER (ORDER BY users.id) AS Seq,
FROM users
```
running these statement will output like this
```
id | username  | password   | Seq |
--------------------------------------
 1 | crow           | somepass1 | 1
 3 | mike           | somepass2 | 2
 5 | jason          | somepass3 | 3
 4 | allison        | somepass4 | 4
 7 | brewr          | somepass5 | 5
 6 | reqeui         | somepass6 | 6
```
now to create skip and limit outputs from sql, i just query the result of the pevious query like
```
SELECT 
     users.id, 
     users.username, 
     users.password 
FROM(
	// Real Query Begin //
	SELECT 
	     users.id,
	     users.username, 
	     users.password, 
  		 ROW_NUMBER() OVER (ORDER BY users.id) AS Seq
  	// Real Query End //
	)users
WHERE Seq BETWEEN 1 AND 8
```

now to run these query and complete data presentation using typeORM
```
    var query = ""
    let tableName = Users.getRepository().metadata.tableName
    if(filterUser != undefined) {
      var query = `${tableName}.name LIKE "%${filterUser}%"`
      if(filterGroup != undefined) {
        query = query + ` AND ${tableName}.groupId = ${filterGroup}`
      }
    } else {
      if(filterGroup != undefined) {
        query = `${tableName}.groupId = ${filterGroup}`
      }
    }
    let connection = getConnection()
    // Supporting Raw Query
    if(connection.options.type == "mssql") {
      take = take + skip
      skip = skip + 1
      if(query.length > 2) query = " WHERE " + query
      let users = await Users.query(`SELECT 
      "Users"."id", 
      "Users"."name", 
      "Users"."username",
      "Users"."password", 
      "Users"."groupId", 
      "Users__group_id", 
      "Users__group_name"
      FROM (
        SELECT 
        "Users"."id", 
        "Users"."name",
        "users"."username", 
        "Users"."password", 
        "Users"."groupId", 
        "Users__group"."id" AS "Users__group_id", 
        "Users__group"."name" AS "Users__group_name",
        ROW_NUMBER() OVER (ORDER BY "users"."id") AS Seq
        FROM "users" "Users"
        LEFT JOIN "user_groups" "Users__group" 
        ON "Users__group"."id" = "Users"."groupId"
        ${query}
      )"Users"
      WHERE Seq BETWEEN ${skip} AND ${take}`)
      users = await users.map((user:any) => {
        return {
          id:user.id , 
          name:user.name,
          username:user.username,
          password:user.password,
          groupId: user.groupId,
          group: {
            id: user.Users__group_id,
            name:user.Users__group_name,
          }
        }
      })
      return await Users.getRepository().create(users)
    } else {
      return await Users.find({where:query, relations: ["group"]});
    }
```
i think they can create a method to solve this problem.

**Comment by Metazhoa** [comment]
i have the same problem using `SQL Server 2018 R2` and i used below method to solve it

please note i created query for the data that i'd like to find, then i encapsulate it with another query for limiting the data.
for example, i want to query user id, username and password from table `users`
then my statement would be like
```
SELECT 
     users.id, users.username, 
     users.password 
FROM users 
WHERE users.username = 'mikey'
```
then to use skip and limit for these statement i add `ROW_NUMBER()` function from SQL Server.
so the statement would look like this
```
SELECT 
     users.id,
     users.username, 
     users.password, 
  -->ROW_NUMBER() OVER (ORDER BY users.id) AS Seq,
FROM users
```
running these statement will output like this
```
id | username  | password   | Seq |
--------------------------------------
 1 | crow           | somepass1 | 1
 3 | mike           | somepass2 | 2
 5 | jason          | somepass3 | 3
 4 | allison        | somepass4 | 4
 7 | brewr          | somepass5 | 5
 6 | reqeui         | somepass6 | 6
```
now to create skip and limit outputs from sql, i just query the result of the pevious query like
```
SELECT 
     users.id, 
     users.username, 
     users.password 
FROM(
	// (Main Query) Real Query Begin //
	SELECT 
	     users.id,
	     users.username, 
	     users.password, 
  		 ROW_NUMBER() OVER (ORDER BY users.id) AS Seq
  	// (Main Query) Real Query End //
	)users
WHERE Seq BETWEEN 1 AND 8
```

now to run these query and complete data presentation using typeORM
code below is using `JOIN` you can also use any Operation inside Main Query
```
    var query = ""
    let tableName = Users.getRepository().metadata.tableName
    if(filterUser != undefined) {
      var query = `${tableName}.name LIKE "%${filterUser}%"`
      if(filterGroup != undefined) {
        query = query + ` AND ${tableName}.groupId = ${filterGroup}`
      }
    } else {
      if(filterGroup != undefined) {
        query = `${tableName}.groupId = ${filterGroup}`
      }
    }
    let connection = getConnection()
    // Supporting Raw Query
    if(connection.options.type == "mssql") {
      take = take + skip
      skip = skip + 1
      if(query.length > 2) query = " WHERE " + query
      let users = await Users.query(`SELECT 
      "Users"."id", 
      "Users"."name", 
      "Users"."username",
      "Users"."password", 
      "Users"."groupId", 
      "Users__group_id", 
      "Users__group_name"
      FROM (
        SELECT 
        "Users"."id", 
        "Users"."name",
        "users"."username", 
        "Users"."password", 
        "Users"."groupId", 
        "Users__group"."id" AS "Users__group_id", 
        "Users__group"."name" AS "Users__group_name",
        ROW_NUMBER() OVER (ORDER BY "users"."id") AS Seq
        FROM "users" "Users"
        LEFT JOIN "user_groups" "Users__group" 
        ON "Users__group"."id" = "Users"."groupId"
        ${query}
      )"Users"
      WHERE Seq BETWEEN ${skip} AND ${take}`)
      users = await users.map((user:any) => {
        return {
          id:user.id , 
          name:user.name,
          username:user.username,
          password:user.password,
          groupId: user.groupId,
          group: {
            id: user.Users__group_id,
            name:user.Users__group_name,
          }
        }
      })
      return await Users.getRepository().create(users)
    } else {
      return await Users.find({where:query, relations: ["group"]});
    }
```
i think they can create a method to solve this problem.
