### ISSUE TITLE
EntityMetadataNotFound: No metadata for "User" was found.

### ISSUE THREAD

**Issue by Konrad008** [typeorm/typeorm#2882]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. create project by typeorm init
2. npm install
3. edit ormconfig.json with your data
4. tsc
5. enter the build dir
6. node index.js

then im getting error:
```
{ EntityMetadataNotFound: No metadata for "User" was found.
    at new EntityMetadataNotFoundError (C:\Users\Konrad\Desktop\dev\asd\node_modules\typeorm\error\EntityMetadataNotFoundError.js:19:28)
    at Connection.getMetadata (C:\Users\Konrad\Desktop\dev\asd\node_modules\typeorm\connection\Connection.js:351:19)
    at C:\Users\Konrad\Desktop\dev\asd\node_modules\typeorm\persistence\EntityPersistExecutor.js:105:80
    at Array.forEach (<anonymous>)
    at EntityPersistExecutor.<anonymous> (C:\Users\Konrad\Desktop\dev\asd\node_modules\typeorm\persistence\EntityPersistExecutor.js:100:54)
    at step (C:\Users\Konrad\Desktop\dev\asd\node_modules\typeorm\persistence\EntityPersistExecutor.js:32:23)
    at Object.next (C:\Users\Konrad\Desktop\dev\asd\node_modules\typeorm\persistence\EntityPersistExecutor.js:13:53)
    at C:\Users\Konrad\Desktop\dev\asd\node_modules\typeorm\persistence\EntityPersistExecutor.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Konrad\Desktop\dev\asd\node_modules\typeorm\persistence\EntityPersistExecutor.js:3:12)
  name: 'EntityMetadataNotFound',
  message: 'No metadata for "User" was found.' }
```

Tested on Windows 10, Ubuntu 16.04 with MySql 8, Mysql 5.7 Postgres 10 no matter what always the same error output. Am i missing something or this is a bug? BTW. npm start works just fine ...

**Comment by Konrad008** [comment]
When i ommit the step 5 and run `node build/index.js` the problem persists.
I read all issues with metadata not found and applyed the solutions but nothing worked.
@pleerock could you be so kind and tell me what is causing this error to pop from library perspective so i can debug it further?

**Comment by DylanSp** [comment]
I'm having a similar issue; I get an EntityMetadataNotFound error when trying to run the compiled code with `node`, but `ts-node` (using the default `npm start` script) works fine.

**Comment by DylanSp** [comment]
Fixed my issue; I just needed to be in the correct directory to make the relative paths in `ormconfig.json` work.

**Comment by Kononnable** [comment]
@Konrad008 did this solution fixed your issue too?

**Comment by Konrad008** [comment]
Im afraid not. Im in the main folder of this default project and trying to npm init right beside ormconfig.json the error persists :(

**Comment by Konrad008** [comment]
After days of research i can confirm that wheel was reinvented again. 

**For any future reader:**
`EntityMetadataNotFound` error is displayed when TypeORM cant find your entities. Often this is caused by wrong/misspelled entry in your ormconfig file. If you think that there is everything fine with you paths **CHECK AGAIN**!!

In my case error was hidden in ENV variables the paths included there have priority over the ormconfig.json file so the paths was overwritten by wrong ones.

@Kononnable  thank you, the solution has been found.

**Comment by wtravO** [comment]
Sharing my experience to see if it helps anyone else!

If you replaced old files and - like myself - are building to JS and then serving up the server... make sure you delete your dist directory first or else it'll try to read your old compiled files that weren't overwritten. ;) Sneaky!

**Comment by feather-jmalone** [comment]
interesting. possibly related, i've noticed i get this error when restarting the debug session in VS Code. stopping and then starting works with no error, but for some reason the 'restart' operation results in the error. (this never used to happen, seems to have started somewhere in the last couple of releases)

**Comment by armanfatahi** [comment]
In my case, I was saving an instance of User, which was "user = new User()" but instead of passing user to "connection.manager.save(user);" I was passing the entity itself "connection.manager.save(User);".

**Comment by tayoogunbiyi** [comment]
In my case, I omitted the "User" model from my db connection entities.
I simply added the model to the array of entities passed to createConnection

**Comment by FranCOder** [comment]
if I run ts-node src/db/index.ts inside a folder where locate ormconfig.json it's work, but if I run inside /src/db/ ts-node index.ts doesn't work

**Comment by captaincole** [comment]
Just wanted to add my two cents as to how I fixed this in my project. I'm running this in a serverless application (serverless offline to test) and was seeing this exact error occured. In order to fix it, I had to adjust two things.

First, in my database config


`
			const connectionOptions: ConnectionOptions = {
				name: `default`,
				type: `postgres`,
				port: 5432,
				synchronize: true,
				logging: true,
				...
				entities: [ __dirname + '/../../src/entity/*.js' ]
			};
`
This is becuase my database class was in a file located in /src/db/type-database.ts & because serverless offline transpiles typescript into javascript. Modify that path name to be similar to your path. 

Second, I had to use a string of my classname instead of importing it directly.

`
		const users = await connection.manager.find('User');
`

This is because when it is transpilied into JS, the class name becomes User_1 which does not match the actually database table name. 

Hope this helps someone.

**Comment by craigcartmell** [comment]
@captaincole - Same issue here, which is fixed by using the string as you say, however I'm having the same issue with custom repositories and can't seem to find a workaround.

```
import { EntityRepository, Repository } from 'typeorm'
import { AccountEntity } from '../entities/account-entity'
import { UserEntity } from '../entities/user-entity'
import AccountType from '../enums/account-type'

@EntityRepository(AccountEntity)
export default class AccountRepository extends Repository<AccountEntity> {
  public async findUserByCognitoId(
    id: string,
  ): Promise<UserEntity | undefined | null> {
    const account = await this.findOne(
      {
        externalId: id,
        accountType: AccountType.Cognito,
      },
      { relations: ['user'] },
    )

    return account && account.user
  }
}
```

```
   const connection = await context.connectors.database.getConnection()
      const accountRepository = connection.getCustomRepository(
        AccountRepository
      )
```

This throws an `No metadata for \"AccountEntity\" was found.` error and supplying 'AccountEntity' doesn't work.

Anyone had this?

**Comment by craigcartmell** [comment]
For anyone having the same issue above, https://github.com/typeorm/typeorm/issues/3427#issuecomment-504134702 fixes it.

**Comment by darian7** [comment]
Solución 100%

entities: [join(__dirname, '..', 'modules', '**', '*.entity{.ts,.js}')]

**Comment by undeinf** [comment]
Another working  solution:
entities: [__dirname + '/../../**/*.entity.{js,ts}']

**Comment by JunfengHan** [comment]
Maybe you forget add @Entity() to your entity

**Comment by radihuq** [comment]
Similar to the other comments, the path I was providing was incorrect. For reference, I'm running the app using `serverless offline` on a windows machine

Originally the entities value was:
`                entities: [__dirname + '/entity/*.js'],
`

But after console.log'ing the result, it seemed like it was returning the directory incorrectly:
`
\.build\src/entity
`

So I changed it to this:
`
entities: [__dirname + '\\entity\\*.js'],
`

The result was this (and it seems to work):
`
\.build\src\entity
`

**Comment by ruqayy9** [comment]
> Maybe you forget add @entity() to your entity

I can't believe that was actually it ! Thank you

**Comment by paulohenry** [comment]
was with the way
"entities": [
        "src / model / ** / *. ts"
     ],
I switch to
"entities": [
        "src / models / ** / *. ts"
     ],

to stay the same in the project folder

**Comment by avalladaresm** [comment]
This did it for me.

> @undeinf
>  
> undeinf commented on Feb 15, 2020
> Another working solution:
> entities: [__dirname + '/../../**/*.entity.{js,ts}']

In my case, I changed `entities: [__dirname + /entity/**/*.ts]` to `entities: [__dirname} +entity/**/*.{js,ts}]`.

On the local environment it doesn't really matter if you only have `.ts` files, keep in mind that when transpiled, the build/dist directory only has js files to read from, so I believe having both file types to read from is the better option.

**Comment by hallex-abreu** [comment]
No meu ormconfig adicionei o caminho do entities

{
    "type" : "postgres",
    "host" : "localhost",
    "port": 5432,
    "username" : "docker",
    "password" : "docker",
    "database" : "grupopp",
    "migrations" : ["./src/database/migrations/**.ts"],
    "entities" : ["./src/entities/**.ts"],
    "cli": {
        "migrationsDir" : "./src/database/migrations"
    }
}

**Comment by hallex-abreu** [comment]
{
    "type" : "postgres",
    "host" : "localhost",
    "port": port,
    "username" : "user",
    "password" : "password",
    "database" : "nomedoBanco",
    "migrations" : ["./src/database/migrations/**.ts"],
    "entities" : ["./src/entities/**.ts"], 
    "cli": {
        "migrationsDir" : "./src/database/migrations"
    }
}

**Comment by hallex-abreu** [comment]
No meu ormconfig adicionei o caminho do entities, conforme código abaixo:

{
"type" : "postgres",
"host" : "localhost",
"port": port,
"username" : "user",
"password" : "password",
"database" : "nomedoBanco",
"migrations" : ["./src/database/migrations/.ts"],
"entities" : ["./src/entities/.ts"],
"cli": {
"migrationsDir" : "./src/database/migrations"
}
}

**Comment by geeofree** [comment]
For those using Babel 7 with [@babel/plugin-proposal-decorators](https://babeljs.io/docs/en/babel-plugin-proposal-decorators), set the legacy option to `true`.

**Comment by Henriquedevb** [comment]
> Após dias de pesquisa, posso confirmar que a roda foi reinventada novamente.
> 
> **Para qualquer leitor futuro: o**
> `EntityMetadataNotFound` erro é exibido quando TypeORM não consegue encontrar suas entidades. Freqüentemente, isso é causado por uma entrada incorreta / incorreta no arquivo ormconfig. Se você acha que está tudo bem com seus caminhos **VERIFIQUE DE NOVO** !!
> 
> No meu caso, o erro foi escondido nas variáveis ​​ENV, os caminhos incluídos lá têm prioridade sobre o arquivo ormconfig.json, então os caminhos foram substituídos por caminhos errados.
> 
> @Kononnable obrigado, a solução foi encontrada.

Exatamente isso, jurei que estava tudo certo com meu arquivo de configuração mas na verdade tinha uma letra incorreta do caminho e me causou esse erro, obrigado.

**Comment by rishil321** [comment]
> For those using Babel 7 with [@babel/plugin-proposal-decorators](https://babeljs.io/docs/en/babel-plugin-proposal-decorators), set the legacy option to `true`.

Yes thank you! This was it.

`{
    "presets": [
        ["@babel/preset-env"]
    ],
    "plugins": [
        ["@babel/plugin-proposal-decorators",{"legacy":true}],
        "@babel/plugin-proposal-class-properties"
        ]
}`

**Comment by ks4na** [comment]
For me, I forgot to call `appDataSource.initialize()` before using `appDataSource.getRepository()` in express route handler.

**Comment by iambpn** [comment]
if anyone came here from nestjs then make sure you have added `autoLoadEntities:true` like this when importing typeorm in your module.
```
TypeOrmModule.forRoot({
   ...,
   autoLoadEntities:true
})
```

**Comment by ranielisilveira** [comment]
I was having the same problem. In clean arch entities are what surrounds your application and models are just table references, something that is not part of the business rule.

said that: If you need to work with both (.entity and .model) you need to put them in the entities paths in your database config

```
"type": "mysql",
"host": "xxx",
"port": xxx,
"username": "xxxx",
"password": "xxxx",
"database": "xxxx",
**"entities": ["dist/**/*.entity{.ts,.js}", "dist/**/*.model{.ts,.js}"]**
```
