### ISSUE TITLE
column.clone is not a function

### ISSUE THREAD

**Issue by zveljkovic** [typeorm/typeorm#2973]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[x] `0.2.8` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```
import {MigrationInterface, QueryRunner, TableColumn} from 'typeorm';

export class AddEmailToAppUser1539900193892 implements MigrationInterface {

	public async up(queryRunner: QueryRunner): Promise<any> {
		// This works:  await queryRunner.query(`ALTER TABLE "AppUser" ADD COLUMN "email" varchar(255)`);
		await queryRunner.addColumn('AppUser', new TableColumn({
			name: 'email',
			type: 'varchar',
			length: '255',
			isNullable: true,
		}));
	}

	public async down(queryRunner: QueryRunner): Promise<any> {
		await queryRunner.dropColumn('AppUser', 'email');
	}
}
```
Error is
```
query: ROLLBACK
Error during migration run:
TypeError: column.clone is not a function
    at _____\node_modules\typeorm\schema-builder\table\Table.js:79:73
    at Array.map (<anonymous>)
    at Table.clone (_____\node_modules\typeorm\schema-builder\table\Table.js:79:35)
    at PostgresQueryRunner.<anonymous> (_____\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:647:45)
    at step (_____\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:42:23)
    at Object.next (_____\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:23:53)
    at fulfilled (_____\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:14:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by devdemi** [comment]
I have the same problem. @zveljkovic Do you find any solution of this problem?

**Comment by zveljkovic** [comment]
I have started using plain SQL queries for migrations. There were the other issue of not being able to set index names, which is also overcome with plain SQL migrations.

**Comment by imnotjames** [comment]
Should be fixed in latest release.

**Comment by Xunjin** [comment]
Sorry for reopening it @imnotjames is this fixed? Still got this problem :/ how should I proceed about it? Ty

**Comment by kejvi-doko** [comment]
it is still happening, 

`“TypeError: column.clone is not a function\n”,“stream”:“stderr”,“time”:“2022-07-19T21:39:25.276597657Z”}`
