### ISSUE TITLE
"could not determine data type of parameter $1" in createQueryBuilder insert

### ISSUE THREAD

**Issue by trunglh88** [typeorm/typeorm#3016]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.8` (or put your version here)

I am trying to create an insertQuery with sql function in Nestjs framework like this :
```
const result = await this.userRepository
      .createQueryBuilder()
      .insert()
      .into(User)
      .values({
        column_1: () => `nextval('table_id_seq')`,
        column_2: user.column_2,
        column_3: user.column_3,
        column_4: user.column_4,
        created_at: user.created_at,
      })
      .printSql()
      .execute();
```
The error : 

```
error: { error: could not determine data type of parameter $1
    at Connection.parseE (C:\Users\trung\code\ims\exchange-nest\node_modules\pg\lib\connection.js:554:11)
    at Connection.parseMessage (C:\Users\trung\code\ims\exchange-nest\node_modules\pg\lib\connection.js:379:19)
    at Socket.<anonymous> (C:\Users\trung\code\ims\exchange-nest\node_modules\pg\lib\connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
  name: 'error',
  length: 111,
  severity: 'ERROR',
  code: '42P18',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1350',
  routine: 'exec_parse_message' }
```
Is insertQuery not support param like **column_1: () => `nextval('table_id_seq')`,**  like updateQuery in [#465](https://github.com/typeorm/typeorm/issues/465)

**Comment by Vocal** [comment]
i remove **.printSql()** and query is execute success.

**Comment by ruandao** [comment]
i get a simlar problem
if use getSql on queryBuilder,  and then execute, it will cause this problem
`ownerUpdateKP: QueryFailedError: could not determine data type of parameter $1
`
and success after remove `getSql`

**Comment by 1valdis** [comment]
@trunglh88 could you please reopen the issue? I just stumbled upon this and clearly that's a bug. I want to use both `printSql` and `values`.

**Comment by simon-a-j** [comment]
Looks like there's a bug with parameter numbering on `InsertQueryBuilder` when the query and parameters are accessed more than once (which happens if you call `printSql`). I've proposed a fix in #7375 and hope I've not missed any context on why things are they way they are currently.

**Comment by imnotjames** [comment]
This should be resolved by #7821

**Comment by sanosuke-s74** [comment]
updated typeorm to 0.2.34 and am still seeing this behavior when using update.

**Comment by imnotjames** [comment]
That PR hasn't been released yet.  It should be in 0.2.35
