### ISSUE TITLE
Webpack support is limited.

### ISSUE THREAD

**Issue by itonics-tbeauvais** [typeorm/typeorm#3152]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.9` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

All I did here was us the `typeorm init` to create create a new project that works well. Adding a simple webpack is where problems arise.

The problem seems to be with webpack. I have seen a few of these as I have been sifting through your closed and open issues.

Using a pretty basic `webpack.config.js`
```
const path = require('path');

module.exports = {
    entry: './src/index.ts',
    mode: 'development',
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                use: 'ts-loader',
                exclude: /node_modules/
            }
        ]
    },
    resolve: {
        extensions: ['.tsx', '.ts', '.js','.json']
    },
    // added as a result of the available node libraries
    externals: {
        fs: '{}',
        tls: '{}',
        net: '{}',
        dns: '{}',
        readline: '{}'
    },
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist')
    }
};
```

Running this..
```
node dist/bundle.js
```

Results in the following runing error.
```
{ Error: Cannot find module '/node_modules/app-root-path'
    at webpackEmptyContext (webpack:///./node_modules/typeorm/platform_sync?:2:10)
    at Function.PlatformTools.load (webpack:///./node_modules/typeorm/platform/PlatformTools.js?:136:93)
    at ConnectionOptionsReader.get [as baseDirectory] (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:247:50)
    at ConnectionOptionsReader.get [as baseFilePath] (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:235:25)
    at ConnectionOptionsReader.eval (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:130:50)
    at step (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:32:23)
    at Object.eval [as next] (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:13:53)
    at eval (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:7:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:3:12) code: 'MODULE_NOT_FOUND' }
```

It seems that the problem stems from this PlatformTools library that dynamic attempts to load libraries. For me, even manually installing `app-root-path` and adding `require('app-root-path')` in my application doesn't help.

Now, I know that webpack is just a pain to support. It seems the dynamic nature of the `PlatformTools` loading dependencies doesn't mesh well. Any insight or examples would be nice.

**Comment by alfaproject** [comment]
I've fixed that particular import in this PR which was just merged https://github.com/typeorm/typeorm/pull/3082

**Comment by pleerock** [comment]
latest changed are available via `npm i typeorm@0.2.10-rc.1`

**Comment by itonics-tbeauvais** [comment]
Thanks for the quick update. I have installed and got a few false hopes when I manually include `app-root-path` and yet still have problems from a 'clean' project.

```
$ npm i -g typeorm@0.2.10-rc.1
$ typeorm init --database postgres --name donkey2
$ cd donkey2
$ npm install
$ cp ../donkey/webpack.config.js
$ npm i -D webpack webpack-cli ts-loader
$ node ./node_modules/.bin/webpack
$ node dist/bundle.js
```

With the following output: 
```
{ Error: Cannot find module '/Users/thomas.beauvais/Code/donkey2/donkey2/node_modules/app-root-path'
    at webpackEmptyContext (webpack:///./node_modules/typeorm/platform_sync?:2:10)
    at Function.PlatformTools.load (webpack:///./node_modules/typeorm/platform/PlatformTools.js?:138:93)
    at ConnectionOptionsReader.get [as baseDirectory] (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:247:50)
    at ConnectionOptionsReader.get [as baseFilePath] (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:235:25)
    at ConnectionOptionsReader.eval (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:130:50)
    at step (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:32:23)
    at Object.eval [as next] (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:13:53)
    at eval (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:7:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:3:12) code: 'MODULE_NOT_FOUND' }
```

The new webpack (I had forgot the `target: 'node'` is here):
```
const path = require('path');

module.exports = {
    entry: './src/index.ts',
    mode: 'development',
    target: 'node',
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                use: 'ts-loader'
            }
        ]
    },
    resolve: {
        extensions: ['.tsx', '.ts', '.js','.json']
    },
    externals: {
        'pg-native': {}
    },
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist')
    }
};
```

Adding `const arp = require ('app-root-path');` this to play around and force the import renders this following (most likely the next error in the chain):
```
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.dirname (path.js:1349:5)
    at resolve (webpack:///./node_modules/app-root-path/lib/resolve.js?:68:22)
    at module.exports (webpack:///./node_modules/app-root-path/lib/app-root-path.js?:6:20)
    at Object.eval (webpack:///./node_modules/app-root-path/index.js?:4:18)
    at eval (webpack:///./node_modules/app-root-path/index.js?:5:30)
    at Object../node_modules/app-root-path/index.js (/Users/thomas.beauvais/Code/donkey2/donkey2/dist/bundle.js:109:1)
    at __webpack_require__ (/Users/thomas.beauvais/Code/donkey2/donkey2/dist/bundle.js:20:30)
    at eval (webpack:///./src/index.ts?:42:11)
    at Object../src/index.ts (/Users/thomas.beauvais/Code/donkey2/donkey2/dist/bundle.js:6022:1)
```

I feel like we are really close and would like to start our services on your great library, it's just hard to debug this ourselves.

**Comment by alfaproject** [comment]
For the `Path must be a string.` issue, you can tell Webpack to set this environment variable to `.` or whatever path you prefer: https://github.com/inxilpro/node-app-root-path/blob/master/lib/resolve.js#L24

You can use a define plugin or whatever other means you usually use to set environment variables.

P.S.: It kind of sucks, but it worked for me. I could probably do a PR to make that module compatible with a Webpack build but have a hard deadline for the project I'm working on, so I'm happy enough with that workaround.

**Comment by itonics-tbeauvais** [comment]
Thanks for the response during your deadline. Your workaround works. Also, somehow not setting it works now. I am puzzled by this.

Even with that, I still received an error here:

```
{ Error: Cannot find module '/Users/thomas.beauvais/Code/test-typeorm/ormconfig.json'
    at webpackEmptyContext (webpack:///./node_modules/typeorm/platform_sync?:2:10)
    at Function.PlatformTools.load (webpack:///./node_modules/typeorm/platform/PlatformTools.js?:133:97)
    at ConnectionOptionsReader.eval (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:158:75)
    at step (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:32:23)
    at Object.eval [as next] (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:13:53)
    at eval (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:7:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:3:12)
    at ConnectionOptionsReader.load (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:122:16)
    at ConnectionOptionsReader.eval (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:64:55) code: 'MODULE_NOT_FOUND' }
```

And a simple (and most likely better way) is to just to declare this in the code using the `ConnectionOptions` and manually setting the entity classes like this:
```
"entities": [
        User
     ]
```

If you have a better way, as I would like to take the default configuration using the path scan `"src/entity/**/*.ts"` then I am eager to hear. When I use this path, I get this error:

```
{ Error: Cannot find module '/Users/thomas.beauvais/Code/test-typeorm/node_modules/glob'
    at webpackEmptyContext (webpack:///./node_modules/typeorm/platform_sync?:2:10)
    at Function.PlatformTools.load (webpack:///./node_modules/typeorm/platform/PlatformTools.js?:138:93)
    at eval (webpack:///./node_modules/typeorm/util/DirectoryExportedClassesLoader.js?:23:61)
    at Array.reduce (<anonymous>)
    at Object.importClassesFromDirectories (webpack:///./node_modules/typeorm/util/DirectoryExportedClassesLoader.js?:22:32)
    at ConnectionMetadataBuilder.buildEntityMetadatas (webpack:///./node_modules/typeorm/connection/ConnectionMetadataBuilder.js?:69:89)
    at Connection.buildMetadatas (webpack:///./node_modules/typeorm/connection/Connection.js?:510:57)
    at Connection.eval (webpack:///./node_modules/typeorm/connection/Connection.js?:163:30)
    at step (webpack:///./node_modules/typeorm/connection/Connection.js?:32:23)
    at Object.eval [as next] (webpack:///./node_modules/typeorm/connection/Connection.js?:13:53) code: 'MODULE_NOT_FOUND' }
```

**Comment by alfaproject** [comment]
Because we are using Webpack, we can't do that. Those entities need to be bundled, so you need to declare them explicitly.

There is an alternative, which is to copy those entities to where your bundle are and then you can do that. That requires you to downlevel them in separate and keep the same folder structure. I opted to be explicit in my project tho.

**Comment by XaeroDegreaz** [comment]
Has there been any movement on this issue? I'm using the Serverless Framework for my AWS Lambda functions, and they are using Webpack. I've scoured around and have landed here, and several other issues on this repo that seem to point to Webpack and TypeORM not playing well together.

**Comment by eltonio450** [comment]
hi @XaeroDegreaz 

We're struggling with the same issue, did you find a final solution ? We have exactly the same setup (serverless + lambda)

What is this APP_ROOT_PATH you set up ? Is it for webpack ? 

Thank you :) !

**Comment by XaeroDegreaz** [comment]
@eltonio450 

It was a global environment variable I set up in my `serverless.yml` file.

**Comment by eltonio450** [comment]
thanks i ll try :)

**Comment by marcoso** [comment]
I have been struggling with this for a couple days too when trying to run an Angular Universal/Node app with TypeORM, first I was not being able to load the options from the ormconfig.json/js so I had to go with the approach of include it when creating the connection.
Then I had problems with the Entities and generating/running the Migrations. I ended up compiling to generate the Entities then from those I generate the Migrations, compiling again to be able to run the Migrations. 

Adding the environmental variable worked for me so thanks @alfaproject , @itonics-tbeauvais for the info.

Hopefully we can have this issues fixed in future releases...

**Comment by atul221282** [comment]
Can't believe issues from Nov 2018 are still open

**Comment by kmaid** [comment]
This is also a problem for me. Using @XaeroDegreaz solutioin

**Comment by dcs3spp** [comment]
Also experienced this problem. Would be useful to document and include a *full* sample webpack.config.js.

**Comment by nvs2394** [comment]
> Has there been any movement on this issue? I'm using the Serverless Framework for my AWS Lambda functions, and they are using Webpack. I've scoured around and have landed here, and several other issues on this repo that seem to point to Webpack and TypeORM not playing well together.
> 
> **Update:** I was able to resolve this issue by taking @alfaproject suggestion of setting an environment variable of `APP_ROOT_PATH` to `.` and now it works. However, TypeORM is unable to find the `ormconfig.json` file to create connections options, so I have to create the `ConnectionOptions` object manually (something I can live with for now), and pass them into the connection for it to work.

Hi @XaeroDegreaz  could you share your code.

**Comment by eltonio450** [comment]
you have to include your ormconfig in your bundle manually (beucause it's not imported by any file). Alternatively, use the .js config file and import it

**Comment by k0l0r3k99** [comment]
I wasted 3 hours to look for what's wrong. Firstly I had "UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded", now I've:
```
Error: Cannot find module '/home/ubuntu/xyz/node_modules/dotenv'
    at webpackEmptyContext (webpack:///./node_modules/typeorm/platform_sync?:2:10)
    at Function.PlatformTools.load (webpack:///./node_modules/typeorm/platform/PlatformTools.js?:119:93)
    at ConnectionOptionsReader.eval (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:107:68)
    at step (webpack:///./node_modules/tslib/tslib.es6.js?:124:23)
    at Object.eval [as next] (webpack:///./node_modules/tslib/tslib.es6.js?:105:53)
    at eval (webpack:///./node_modules/tslib/tslib.es6.js?:98:71)
    at new Promise (<anonymous>)
    at Module.__awaiter (webpack:///./node_modules/tslib/tslib.es6.js?:94:12)
    at ConnectionOptionsReader.load (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:88:24)
    at ConnectionOptionsReader.eval (webpack:///./node_modules/typeorm/connection/ConnectionOptionsReader.js?:30:55) code: 'MODULE_NOT_FOUND' 

$ ls -l /home/ubuntu/xyz/node_modules/dotenv
total 40
-rw-rw-r-- 1 ubuntu ubuntu 4600 Oct 26  1985 CHANGELOG.md
-rw-rw-r-- 1 ubuntu ubuntu 1294 Oct 26  1985 LICENSE
-rw-rw-r-- 1 ubuntu ubuntu 9718 Oct 26  1985 README.md
-rw-rw-r-- 1 ubuntu ubuntu  189 Oct 26  1985 config.js
drwxrwxr-x 2 ubuntu ubuntu 4096 Jul 15 08:46 lib
-rw-rw-r-- 1 ubuntu ubuntu 1916 Jul 15 08:46 package.json
drwxrwxr-x 2 ubuntu ubuntu 4096 Jul 15 08:46 types
```

Why does typeorm lie that the module does not exist as clearly exists?

**Comment by shiro** [comment]
Also scratched my head for 2 hours to find out why there is a `dotenv` error when I use typeorm...
Exactly the same issue as above.

**Comment by imnotjames** [comment]
New release, we should be good. If there are other issues you're seeing, please open a new issue.
