### ISSUE TITLE
Use CASE statement inside queryBuilder

### ISSUE THREAD

**Issue by focux** [typeorm/typeorm#3167]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `5.2.2` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I was looking for a function to use CASE statement through the documentation and I didn't find anything, so I was wondering if there is a implementation of this and if not, what would be the work around I could use?

I'm trying to do something like this e.g.
```
SELECT CustomerName, City, Country
FROM Customers
ORDER BY
(CASE
    WHEN City IS NULL THEN Country
    ELSE City
END);
```

**Comment by vlapo** [comment]
Hi @focux,

You can provide any SQL to `orderBy` method. So your case is something like this
```typescript
connection.getRepository(Customer).createQueryBuilder("customer")
            .select(["customer.CustomerName", "customer.City", "customer.Country"])
            .orderBy("(CASE WHEN customer.City IS NULL THEN customer.Country ELSE customer.City END)")
            .getMany();
```

Let me know if this help.

**Comment by hieutle2011** [comment]
I found no documentation about CASE operator. Could you help me how to do this with query builder @vlapo ? Thanks.
`SELECT OrderID, Quantity,
CASE WHEN Quantity > 30 THEN "The quantity is greater than 30"
WHEN Quantity = 30 THEN "The quantity is 30"
ELSE "The quantity is under 30"
END AS QuantityText
FROM OrderDetails;`

**Comment by vlapo** [comment]
Do not know your entity definition but try something like this:
```typescript
connection.getRepository(OrderDetails).createQueryBuilder("order_details")
            .select(["order_details.OrderId", "order_details.Quantity"])
            .addSelect(`CASE
                        WHEN "order_details"."Quantity" > 30 THEN "The quantity is greater than 30"
                        WHEN "order_details"."Quantity" = 30 THEN "The quantity is 30"
                        ELSE "The quantity is under 30"
                    END`, "QuantityText")
            .getRawMany();
```

**Comment by hieutle2011** [comment]
Thank you very much for your response! It works!

**Comment by hieutle2011** [comment]
> Do not know your entity definition but try something like this:
> 
> ```ts
> connection.getRepository(OrderDetails).createQueryBuilder("order_details")
>             .select(["order_details.OrderId", "order_details.Quantity"])
>             .addSelect(`CASE
>                         WHEN "order_details"."Quantity" > 30 THEN "The quantity is greater than 30"
>                         WHEN "order_details"."Quantity" = 30 THEN "The quantity is 30"
>                         ELSE "The quantity is under 30"
>                     END`, "QuantityText")
>             .getRawMany();
> ```

With getRawMany() i can get the "QuantityText" but also the raw data, which is undesirable. But when i use getMany() to get the real entity,  "QuantityText" disappers. How can i get the real entity with getMany() together with raw row of  "QuantityText"?

Thank you @vlapo .

**Comment by vlapo** [comment]
Use `getRawAndEntities()` instead of `getMany()`. It will return raw data and entities.

**Comment by Kononnable** [comment]
Looks like issue was resolved.

**Comment by noteasybutclear** [comment]
Hello, I have same issue.
in my case, still not work.


```
result = await getConnection()
          .getRepository(Post)
          .createQueryBuilder("post")
          .orderBy(_sortField, _sortOrder)
          .skip(_offset)
          .take(_limit)
          .leftJoinAndSelect("post.user", "user")
          .leftJoinAndSelect("post.products", "product")
          .leftJoinAndSelect("product.brand", "brand")
          .orderBy(`CASE WHEN product.category='SOMETHING' THEN 1 END`, "DESC") // not work!
          .getMany();
```


my error message is 
`Error: "CASE WHEN product" alias was not found. Maybe you forgot to join it?`

version info 
"typeorm": "^0.2.16"

Please help me.

**Comment by codingotaku** [comment]
I think it would be better if we can append a raw query to the query builder
the given solution is just a workaround and if I want to add something like PIVOT, the only way I can use it is by the query() method and I have to write the **whole query** there, which is ugly.

**Comment by vlapo** [comment]
@codingotaku I am sorry I am not familiar with `PIVOT` but you can still use `getQueryAndParameters` method of query builder and append some raw query in builded SQL.

But I think this is out of scope this issue.

**Comment by codingotaku** [comment]
@vlapo thanks, I ended up just adding a new prototype though.

and about the original issue, there is no CASE statement supported by typeorm (even though we could add any query as a string).

I understand that some of these are depending on what database system is being used (PIVOT for example was from mssql), a suggestion would be to allow adding raw queries with a dedicated method.

but looking at the `SelectQueryBuilder.getQuery()`, I can understand why it is absurd to add `addRaw()` as a feature.
```js
    SelectQueryBuilder.prototype.getQuery = function () {
      var sql = this.createSelectExpression();
      sql += this.createJoinExpression();
      sql += this.createWhereExpression();
      sql += this.createGroupByExpression();
      sql += this.createHavingExpression();
      sql += this.createOrderByExpression();
      sql += this.createLimitOffsetExpression();
      sql += this.createLockExpression();
      sql = sql.trim();
      if (this.expressionMap.subQuery)
        sql = "(" + sql + ")";
      return sql;
    }
  }
```

**Comment by simplenotezy** [comment]
> Hello, I have same issue. in my case, still not work.
> 
> ```
> result = await getConnection()
>           .getRepository(Post)
>           .createQueryBuilder("post")
>           .orderBy(_sortField, _sortOrder)
>           .skip(_offset)
>           .take(_limit)
>           .leftJoinAndSelect("post.user", "user")
>           .leftJoinAndSelect("post.products", "product")
>           .leftJoinAndSelect("product.brand", "brand")
>           .orderBy(`CASE WHEN product.category='SOMETHING' THEN 1 END`, "DESC") // test code, not work!
>           .getMany();
> ```
> 
> my error message is `Error: "CASE WHEN product" alias was not found. Maybe you forgot to join it?`
> 
> version info "typeorm": "^0.2.16"
> 
> Please help me.

Did you ever find a solution?

**Comment by manjari09** [comment]
> > Do not know your entity definition but try something like this:
> > ```ts
> > connection.getRepository(OrderDetails).createQueryBuilder("order_details")
> >             .select(["order_details.OrderId", "order_details.Quantity"])
> >             .addSelect(`CASE
> >                         WHEN "order_details"."Quantity" > 30 THEN "The quantity is greater than 30"
> >                         WHEN "order_details"."Quantity" = 30 THEN "The quantity is 30"
> >                         ELSE "The quantity is under 30"
> >                     END`, "QuantityText")
> >             .getRawMany();
> > ```
> 
> With getRawMany() i can get the "QuantityText" but also the raw data (order_id, quantity), which is undesirable. But when i use getMany() to get the real entity, "QuantityText" disappers. How can i get the real entity (OrderID, Quantity) with getMany() together with raw row of "QuantityText"?
> 
> Thank you @vlapo .
> 
> Entity example:
> 
> ```
> @Entity('order_details')
> export class Order {
>   @PrimaryColumn({
>     name: 'order_id',
>   })
>   public OrderID!: number
> 
>   @Column({
>     name: 'quantity',
>   })
>   public Quantity!: string
> ```

Can we add conditions on "QuantityText" here. I have a situation where I want to check if it is not null or something passed from Frontend to add conditions on this alias. I tried adding andHaving and andWhere, both complains that column is not found. NOTE - in my case this is a virtual column as well.

**Comment by DutchJelly** [comment]
Update: another workaround i found is to use the generated column ID with is basically the repository names split with `_`. This way TypeORM will not detect it. This worked for me in SQLite.
```ts
query.orderBy(CASE WHEN user_accountStatus = 'inactive' THEN 0 ELSE 1 END)
```
