### ISSUE TITLE
@CreateDateColumn and @UpdateDateColumn should use value if provided.

### ISSUE THREAD

**Issue by wederer** [typeorm/typeorm#3271]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Entity User:
```
    @PrimaryColumn({
        nullable: false,
        primary: true,
    })
    id: number;

     @CreateDateColumn({
        nullable: false,
        name: "dt_create"
    })
    createdOn: Date;

    @UpdateDateColumn({
        nullable: false,
        name: "dt_modified"
    })
    modifiedOn: Date;
```
And then run:
```typescript
    const date = new Date(2017, 11, 24, 12);
    const user = new User();
    user.id = 1;
    user.modifiedOn = date;
    user.createdOn= date;

    getRepository(User).insert(user);
    getRepository(User).update(user);
```

The behaviour of `save`, `update` and `insert` are pretty strange when it comes the the `@CreateDateColumn` and `@UpdateDateColumn` decorators.

When running the above code and a user with the same id is already present following error is thrown:
```
multiple assignments to same column "dt_modified"
```

TypeORM is probably adding any `@UpdateDateColumn` property to `update` queries which causes this error. I would expect to be able to override the value if needed.

`save` just ignores the value instead. Values passed in the `insert` however are used and the outcome is as expected.

Is this behaviour expected/intended or is this a bug?

**Comment by feather-jmalone** [comment]
i agree with @wederer, there are times when it would be nice to manually override the value of an `@UpdateDateColumn`.

**Comment by pleerock** [comment]
its not supposed for it, just write create a regular date column column and set date you need when you need

**Comment by wederer** [comment]
@pleerock this should be better documented then. I will open up a PR for documentation changes. Please leave the issue open until then.

**Comment by isotopeee** [comment]
Use `repository.update()` to override column values with `@CreateDateColumn` and `@UpdateDateColumn` programatically in automated tests.

**Comment by tinaroh** [comment]
It would be a nice option to be able to override the values for generating fake test data.

**Comment by jwhitmarsh** [comment]
@tinaroh did you ever find a work around for this?

**Comment by wederer** [comment]
@jwhitmarsh We just used this:
```
    @Column({
        default: () => "NOW()"
    })
    createdOn: Date;

    @Column({
        default: () => "NOW()"
    })
    modifiedOn: Date;
```

Not optimal, but worked for our case.

**Comment by jwhitmarsh** [comment]
Beautifully simple! Thank you!!

**Comment by thecatontheflat** [comment]
Another use case — data migration from on DB to another, while trying to preserve these values from the source database

**Comment by pleerock** [comment]
Since this feature is highly requested, we will land it in `0.2.25`. It's going to be closed by #5867

**Comment by nikhilkhurana1** [comment]
@pleerock when is release date of 0.2.25

**Comment by AlashaHonore** [comment]
+1 Really need this :)

**Comment by charmpitz** [comment]
I'm trying to generate some fixtures in MongoDB and it seems to not be working still with the new version..

**Comment by Malbeth81** [comment]
Although supporting this was a neat idea, this change now requires that I delete the version from any entity I loaded from the database before saving it. 

Which by itself isn't that big of a deal, except in the case where I'm saving an entity without having updated any other fields (from a client request), save() skips the update as it should, which is fine except the same entity with no longer any the version gets returned.

This can lead to all sort of issues since you expect the entity returned by save() to always represent the information that's in the database.

So now I practically have to re-implement the same mechanism as save() and check if the object was modified before deleting the version from the object and calling save()...

**Comment by ivanveselin** [comment]
Although a nice feature, it has caused us many problems because we used spread of old entity in many places which now breaks the timeline of updatedAt/createdAt in new entities. Maybe consider moving this behind some switch so you can opt in or out of this feature?

**Comment by stefan030** [comment]
> @jwhitmarsh We just did this:
> 
> ```
>     @Column({
>         default: () => "NOW()"
>     })
>     createdOn: Date;
> 
>     @Column({
>         default: () => "NOW()"
>     })
>     modifiedOn: Date;
> ```
> 
> Not optimal, but worked for our case.

Thank you, this also fixes "UnhandledPromiseRejectionWarning: QueryFailedError: ER_NO_DEFAULT_FOR_FIELD: Field 'createdAt' doesn't have a default value"

**Comment by chorsnell** [comment]
@pleerock was https://github.com/typeorm/typeorm/pull/5867 only implemented for `CreateDateColumn` and `UpdateDateColumn`? `DeleteDateColumn` seems to not allow manual override :'(

**Comment by nebkat** [comment]
I believe `DeleteDateColumns` doesn't have any kind of forced default value during insertion, and in fact I can't see any default value defined at all, so it should be working. Can you paste your column definition for it?

**Comment by xtrinch** [comment]
For anyone trying to just set the previous stored value, this should work (it needs to differ by something to be recognized as a manual change):
```
      entity.updatedAt.setMilliseconds(entity.updatedAt.getMilliseconds() + (1 % 1000));
      await repo.save(notes);
```

**Comment by arnabrahman** [comment]
I am still facing this issue. Though i am manually overriding created and updated date column, it is just ignoring those and setting current dates.

**Comment by silkentrance** [comment]
`@CreateDateColumn` and `@UpdateDateColumn` will automatically assign `*.now()` to the field. It must never be overwritten.

**Comment by dsmabulage** [comment]
Can we block the manual override in `@CreateDateColumn` and `@UpdateDateColumn`

**Comment by petrosschilling** [comment]
6 years and no solution to the problem.

The whole purpose of `UpdateDateColumn` is to update the date when saving. This ticket should have never been implemented.

@pleerock I'm looking at you. This PR should never have been submitted. Can we roll back to the previous behaviour please?
https://github.com/typeorm/typeorm/pull/5867
