### ISSUE TITLE
Entity subscriber beforeUpdate issue

### ISSUE THREAD

**Issue by yulric** [typeorm/typeorm#397]
Hi there,
I'm having issues when updating fields within a EntitySubscriber. In the below code,

```
@EventSubscriber()
export class TimestampSubscriber implements EntitySubscriberInterface<BaseEntity> {
    beforeInsert(event: InsertEvent<BaseEntity>) {
        event.entity.createdAt = new Date();
        event.entity.updatedAt = null;
    }

    beforeUpdate(event: UpdateEvent<BaseEntity>) {
        event.entity.updatedAt = new Date();
        console.log('breakpoint');
    }
}
```

The above code runs as is obvious and I know that beforeUpdate is called because of the breakpoint. But the updatedAt field change isn't being persisted to the db. Any thoughts?

**Comment by pleerock** [comment]
are you using latest typeorm version? We had such issue before and [it](https://github.com/typeorm/typeorm/blob/abf62fe753b8a2978865e1f836e28c37a1e24b99/src/persistence/SubjectOperationExecutor.ts#L116-L116) was fixed

**Comment by yulric** [comment]
Hmm, updated to version 0.0.11 and the problem still persists.

**Comment by pleerock** [comment]
yes it should be there. I'll need to take a look more closely on it then.

**Comment by yulric** [comment]
I'll take a look on my side to make sure I'm not making a mistake.

**Comment by yulric** [comment]
Yeah I don't see any problems on my side. Let me know if there is anything I can do to help debug the issue.

**Comment by yulric** [comment]
I think this is a problem when updating a date field to a new date object using the code,
````
new Date();
````
For some reason typeorm does not see this as an update and so it's not reflected in the database. I have noticed this issue in another part of the app where when I update a Date field to a new Date object and persist it, the field in the table isn't being updated

**Comment by yulric** [comment]
Please ignore this issue. I had put a CreateDateColumn on the updatedAt field assuming that meant that it create a date column without reading the docs. So of course typeorm wasn't updating it since you should not be able to do that. Closing this issue, sorry for wasting your time.
