### ISSUE TITLE
Views generating broken Migrations

### ISSUE THREAD

**Issue by jeanfortheweb** [typeorm/typeorm#4123]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When working with views, in migrations a line like the following is generated:

```ts
  await queryRunner.query("INSERT INTO `development`.`typeorm_metadata`(`type`, `schema`, `name`, `value`) VALUES (?, ?, ?, ?)");
```

As you can see, the placeholders are never filled, neither does a table named "typeorm_metadata" exist.

When I delete those lines, everything is working.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by jeanfortheweb** [comment]
I just noticed that `schema:sync` would at least create the `typeorm_metadata` table, which migrations do not

**Comment by jakubste** [comment]
Just noticed the same thing in postgres. After bumping version of typeorm to 0.2.17 and adding a view, migrations fail on 
`INSERT INTO "typeorm_metadata"("type", "schema", "name", "value") VALUES ($1, $2, $3, $4)`
because of `error: relation "typeorm_metadata" does not exist`

From migrations logs it also looks like parameters are not set properly:
```
  query: 'INSERT INTO "typeorm_metadata"("type", "schema", "name", "value") VALUES ($1, $2, $3, $4)',
  parameters: []
```

**Comment by RobRoseKnows** [comment]
Does anyone know if the typeorm_metadata migrations are safe to delete or if that will cause problems elsewhere?

**Comment by jakubste** [comment]
It'll generate problems if you'll try to create new migrations.

Basically, it looks like typeorm checks if views exist in the database looking into this table. If it will not exist it will generate migrations for creating views every time you'll create new migrations.

I think there are 2 solutions:
1) Create and fill `typeorm_metadata` by hand.
or
2) Remove views creation from new migrations in every new migration file (which is kinda dumb).

This bug is really a pain in the ass for using views in typeorm, it's really weird that nobody noticed it.

**Comment by pleerock** [comment]
Views functionality is new, that's why its not bug-free. Views functionality was implemented by @AlexMesser not sure if he will be able to fix all those problems soon, so feel free to investigate and submit a PR.

**Comment by mccolljr** [comment]
I'm currently running into this as well. I went ahead and manually created the table, and once I did that I got `error: there is no parameter $1` when it tried to create the view. Is that related, or a brand new issue? I can open a new issue if so.

**Comment by evgeniytar** [comment]
@Kononnable @pleerock I have prepared fix for this issue, please take a look on it

**Comment by pleerock** [comment]
fixed by #4726

**Comment by tairosonloa** [comment]
I'm still having this issue with `postgres 11.7` and `12.2` and typeorm `0.2.25`

**Comment by xtrinch** [comment]
Doesn't look fixed to me. Still happening in 2021.

**Comment by davidfilat** [comment]
Yes, I have the same problem. Please reopen the issue.
![CleanShot 2021-07-19 at 09 47 21@2x](https://user-images.githubusercontent.com/1475163/126115197-2931944d-f1d8-43c5-a898-23fe474e747c.png)

**Comment by imnotjames** [comment]
> Yes, I have the same problem. Please reopen the issue.
> ![CleanShot 2021-07-19 at 09 47 21@2x](https://user-images.githubusercontent.com/1475163/126115197-2931944d-f1d8-43c5-a898-23fe474e747c.png)

That seems very different from the issue reported here.

I will not be re-opening this issue.

**Comment by imnotjames** [comment]
> Doesn't look fixed to me. Still happening in 2021.

Cannot replicate.

**Comment by imnotjames** [comment]
If you feel you have seen this problem again please open a new issue with more information on how to replicate the problem.
