### ISSUE TITLE
@ManyToMany relation does not work if the keys are of type Buffer

### ISSUE THREAD

**Issue by peteryangnw** [typeorm/typeorm#4235]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

************************************************************
**Issue:** Many-to-Many relations do not appear to work when the keys derive from type Object (such as Buffer)

**Repository to produce error:** https://github.com/peteryangnw/typeorm_many2many.git

**Steps to reproduce:**
1) Create the following classes:
```
import {Entity, PrimaryColumn} from "typeorm";
import * as uuid  from "uuid";

@Entity()
export class Category {

    @PrimaryColumn({ type: "binary", length: 16, nullable: false })
    private id: Buffer = Buffer.from(uuid.v4().replace(/-/g, ""), "hex");
    
}

```
```
import {Entity, Column, ManyToMany, JoinTable, PrimaryColumn} from "typeorm";
import {Category} from "./Category";
import * as uuid  from "uuid";

@Entity()
export class Question {

    @PrimaryColumn({ type: "binary", length: 16, nullable: false })
    private id: Buffer = Buffer.from(uuid.v4().replace(/-/g, ""), "hex");

    @Column()
    title: string = "Title";

    @Column()
    text: string = "Question";

    @ManyToMany(type => Category)
    @JoinTable()
    categories: Category[] | undefined;

}
```

2) Run: 
```
import "reflect-metadata";
import {createConnection} from "typeorm";
import { Category } from "./entity/Category";
import { Question } from "./entity/Question";

createConnection().then(async connection => {

    let category = new Category();
    let question = new Question();

    await connection.manager.save(category);

    question.categories = [category];
    await connection.manager.save(question);
    
}).catch(error => console.log(error));

```

```
The following is the log output:
query: START TRANSACTION
query: SELECT DATABASE() AS `db_name`
query: SELECT * FROM `INFORMATION_SCHEMA`.`TABLES` WHERE (`TABLE_SCHEMA` = 'eq_catalog' AND `TABLE_NAME` = 'category') OR (`TABLE_SCHEMA` = 'eq_catalog' AND `TABLE_NAME` = 'question') OR (`TABLE_SCHEMA` = 'eq_catalog' AND `TABLE_NAME` = 'question_categories_category')
query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE (`TABLE_SCHEMA` = 'eq_catalog' AND `TABLE_NAME` = 'category') OR (`TABLE_SCHEMA` = 'eq_catalog' AND `TABLE_NAME` = 'question') OR (`TABLE_SCHEMA` = 'eq_catalog' AND `TABLE_NAME` = 'question_categories_category')
query: SELECT * FROM `INFORMATION_SCHEMA`.`KEY_COLUMN_USAGE` WHERE `CONSTRAINT_NAME` = 'PRIMARY' AND ((`TABLE_SCHEMA` = 'eq_catalog' AND `TABLE_NAME` = 'category') OR (`TABLE_SCHEMA` = 'eq_catalog' AND `TABLE_NAME` = 'question') OR (`TABLE_SCHEMA` = 'eq_catalog' AND `TABLE_NAME` = 'question_categories_category'))
query: SELECT `SCHEMA_NAME`, `DEFAULT_CHARACTER_SET_NAME` as `CHARSET`, `DEFAULT_COLLATION_NAME` AS `COLLATION` FROM `INFORMATION_SCHEMA`.`SCHEMATA`
query: SELECT `s`.* FROM `INFORMATION_SCHEMA`.`STATISTICS` `s` LEFT JOIN `INFORMATION_SCHEMA`.`REFERENTIAL_CONSTRAINTS` `rc` ON `s`.`INDEX_NAME` = `rc`.`CONSTRAINT_NAME` WHERE ((`s`.`TABLE_SCHEMA` = 'eq_catalog' AND `s`.`TABLE_NAME`
= 'category') OR (`s`.`TABLE_SCHEMA` = 'eq_catalog' AND `s`.`TABLE_NAME` = 'question') OR (`s`.`TABLE_SCHEMA` = 'eq_catalog' AND `s`.`TABLE_NAME` = 'question_categories_category')) AND `s`.`INDEX_NAME` != 'PRIMARY' AND `rc`.`CONSTRAINT_NAME` IS NULL
query: SELECT `kcu`.`TABLE_SCHEMA`, `kcu`.`TABLE_NAME`, `kcu`.`CONSTRAINT_NAME`, `kcu`.`COLUMN_NAME`, `kcu`.`REFERENCED_TABLE_SCHEMA`, `kcu`.`REFERENCED_TABLE_NAME`, `kcu`.`REFERENCED_COLUMN_NAME`, `rc`.`DELETE_RULE` `ON_DELETE`, `rc`.`UPDATE_RULE` `ON_UPDATE` FROM `INFORMATION_SCHEMA`.`KEY_COLUMN_USAGE` `kcu` INNER JOIN `INFORMATION_SCHEMA`.`REFERENTIAL_CONSTRAINTS` `rc` ON `rc`.`constraint_name` = `kcu`.`constraint_name` WHERE (`kcu`.`TABLE_SCHEMA` = 'eq_catalog' AND `kcu`.`TABLE_NAME` = 'category') OR (`kcu`.`TABLE_SCHEMA` = 'eq_catalog' AND `kcu`.`TABLE_NAME` = 'question') OR (`kcu`.`TABLE_SCHEMA` = 'eq_catalog' AND `kcu`.`TABLE_NAME` = 'question_categories_category')
query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'eq_catalog' AND `TABLE_NAME` = 'typeorm_metadata'
query: COMMIT
query: SELECT `Category`.`id` AS `Category_id` FROM `category` `Category` WHERE `Category`.`id` IN (?) -- PARAMETERS: [{"type":"Buffer","data":[249,16,173,140,70,71,79,55,186,85,89,128,234,46,235,144]}]
query: START TRANSACTION
query: INSERT INTO `category`(`id`) VALUES (?) -- PARAMETERS: [{"type":"Buffer","data":[249,16,173,140,70,71,79,55,186,85,89,128,234,46,235,144]}]
query: COMMIT
query: SELECT `Question`.`id` AS `Question_id`, `Question`.`title` AS `Question_title`, `Question`.`text` AS `Question_text` FROM `question` `Question` WHERE `Question`.`id` IN (?) -- PARAMETERS: [{"type":"Buffer","data":[91,223,170,156,163,88,67,117,139,167,214,42,42,231,32,5]}]
query: START TRANSACTION
query: INSERT INTO `question`(`id`, `title`, `text`) VALUES (?, ?, ?) -- PARAMETERS: [{"type":"Buffer","data":[91,223,170,156,163,88,67,117,139,167,214,42,42,231,32,5]},"Title","Question"]
query: INSERT INTO `question_categories_category`(`questionId`, `categoryId`) VALUES (DEFAULT, DEFAULT)
query failed: INSERT INTO `question_categories_category`(`questionId`, `categoryId`) VALUES (DEFAULT, DEFAULT)
error: { Error: ER_NO_DEFAULT_FOR_FIELD: Field 'questionId' doesn't have a default value
    at Query.Sequence._packetToError (D:\Development\thirdparty\typeorm_many2many\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\Development\thirdparty\typeorm_many2many\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\Development\thirdparty\typeorm_many2many\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\Development\thirdparty\typeorm_many2many\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\Development\thirdparty\typeorm_many2many\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\Development\thirdparty\typeorm_many2many\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\Development\thirdparty\typeorm_many2many\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (D:\Development\thirdparty\typeorm_many2many\node_modules\mysql\lib\Connection.js:525:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    --------------------
    at Protocol._enqueue (D:\Development\thirdparty\typeorm_many2many\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at PoolConnection.query (D:\Development\thirdparty\typeorm_many2many\node_modules\mysql\lib\Connection.js:201:25)
    at MysqlQueryRunner.<anonymous> (D:\Development\thirdparty\typeorm_many2many\src\driver\mysql\MysqlQueryRunner.ts:155:36)
    at step (D:\Development\thirdparty\typeorm_many2many\node_modules\tslib\tslib.js:133:27)
    at Object.next (D:\Development\thirdparty\typeorm_many2many\node_modules\tslib\tslib.js:114:57)
    at fulfilled (D:\Development\thirdparty\typeorm_many2many\node_modules\tslib\tslib.js:104:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlMessage: 'Field \'questionId\' doesn\'t have a default value',
  sqlState: 'HY000',
  index: 0,
  sql:
   'INSERT INTO `question_categories_category`(`questionId`, `categoryId`) VALUES (DEFAULT, DEFAULT)' }
query: ROLLBACK
{ QueryFailedError: ER_NO_DEFAULT_FOR_FIELD: Field 'questionId' doesn't have a default value
    at new QueryFailedError (D:\Development\thirdparty\typeorm_many2many\src\error\QueryFailedError.ts:9:9)
    at Query.<anonymous> (D:\Development\thirdparty\typeorm_many2many\src\driver\mysql\MysqlQueryRunner.ts:166:37)
    at Query.<anonymous> (D:\Development\thirdparty\typeorm_many2many\node_modules\mysql\lib\Connection.js:525:10)
    at Query._callback (D:\Development\thirdparty\typeorm_many2many\node_modules\mysql\lib\Connection.js:491:16)
    at Query.Sequence.end (D:\Development\thirdparty\typeorm_many2many\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query.ErrorPacket (D:\Development\thirdparty\typeorm_many2many\node_modules\mysql\lib\protocol\sequences\Query.js:90:8)
    at Protocol._parsePacket (D:\Development\thirdparty\typeorm_many2many\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\Development\thirdparty\typeorm_many2many\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\Development\thirdparty\typeorm_many2many\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\Development\thirdparty\typeorm_many2many\node_modules\mysql\lib\protocol\Protocol.js:38:16)
  message:
   'ER_NO_DEFAULT_FOR_FIELD: Field \'questionId\' doesn\'t have a default value',
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlMessage: 'Field \'questionId\' doesn\'t have a default value',
  sqlState: 'HY000',
  index: 0,
  sql:
   'INSERT INTO `question_categories_category`(`questionId`, `categoryId`) VALUES (DEFAULT, DEFAULT)',
  name: 'QueryFailedError',
  query:
   'INSERT INTO `question_categories_category`(`questionId`, `categoryId`) VALUES (DEFAULT, DEFAULT)',
  parameters: [] }
```

I believe the problem may be in this part of ColumnMetadata.ts:
```
getEntityValue(entity: ObjectLiteral, transform: boolean = false): any|undefined{
...
        } else { // no embeds - no problems. Simply return column name by property name of the entity
            if (this.relationMetadata && this.referencedColumn) {
                const relatedEntity = this.relationMetadata.getEntityValue(entity);
                if (relatedEntity && relatedEntity instanceof Object && !(relatedEntity instanceof FindOperator) && !(relatedEntity instanceof Function)) {
                    value = this.referencedColumn.getEntityValue(PromiseUtils.extractValue(relatedEntity));

                } else if (entity[this.propertyName] && entity[this.propertyName] instanceof Object && !(entity[this.propertyName] instanceof FindOperator) && !(entity[this.propertyName] instanceof Function)) {
                    value = this.referencedColumn.getEntityValue(PromiseUtils.extractValue(entity[this.propertyName]));

                } else {
                    value = entity[this.propertyName];
                }
...
}
```
it passes the else if condition: entity[this.propertyName] instanceof Object, and so value gets set to undefined, and eventually gets inserted as DEFAULT, instead of falling through to the last condition where the value can be set to entity[this.propertyName].

I hope this helps.

**Comment by haschu** [comment]
I think your problem is related to #4220, which was already fixed via a PR. You'll have to wait for the next TypeORM release :)

**Comment by peteryangnw** [comment]
I pulled the latest set of code which included the PR I believe, but it does not appear to fix the issue. I think this issue may be different.

If it helps, I made a very narrow patch on my machine by adding `&& !(entity[this.propertyName] instanceof Buffer)`  to the the following conditional as such:

```
} else if (entity[this.propertyName] && entity[this.propertyName] instanceof Object && !(entity[this.propertyName] instanceof Buffer) && !(entity[this.propertyName] instanceof FindOperator) && !(entity[this.propertyName] instanceof Function)) {
                    value = this.referencedColumn.getEntityValue(PromiseUtils.extractValue(entity[this.propertyName]));

                }
```
, and things seem to be working. Not sure if such a patch would break anything for the broader audience.

**Comment by tmtung144** [comment]
Is this in any form of official support yet, I'm going to go the same way, it doesn't seem to be production-appropriate.
