### ISSUE TITLE
Skip and take doesn't work with join

### ISSUE THREAD

**Issue by salehmontazeran** [typeorm/typeorm#4742]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.18` (or put your version here)

Hi

I have 7 row in my table and it's my first query.
#### First Query
```typescript
Organization.find({
                relations,
                order: {
                    createdAt: "DESC"
                },
                skip: pagination.skip,
                take: pagination.take
            });
```
### First test for First query
It's my query log for just one request (my resolver dosn't have any additional middleware)
with skip: 1 and take: 2

```bash
query: SELECT DISTINCT "distinctAlias"."Organization_id" as "ids_Organization_id", "distinctAlias"."Organization_createdAt" FROM (SELECT "Organization"."id" AS "Organization_id", "Organization"."createdAt" AS "Organization_createdAt", "Organization"."updatedAt" AS "Organization_updatedAt", "Organization"."name" AS "Organization_name", "Organization"."address" AS "Organization_address", "Organization"."location" AS "Organization_location", "Organization"."contact" AS "Organization_contact", "Organization"."universityId" AS "Organization_universityId", "Organization"."type" AS "Organization_type", "Organization__university"."id" AS "Organization__university_id", "Organization__university"."createdAt" AS "Organization__university_createdAt", "Organization__university"."updatedAt" AS "Organization__university_updatedAt", "Organization__university"."name" AS "Organization__university_name", "Organization__university"."address" AS "Organization__university_address", "Organization__university"."location" AS "Organization__university_location", "Organization__university"."contact" AS "Organization__university_contact", "Organization__university"."type" AS "Organization__university_type", "Organization__units"."id" AS "Organization__units_id", "Organization__units"."createdAt" AS "Organization__units_createdAt", "Organization__units"."updatedAt" AS "Organization__units_updatedAt", "Organization__units"."name" AS "Organization__units_name", "Organization__units"."address" AS "Organization__units_address", "Organization__units"."location" AS "Organization__units_location", "Organization__units"."contact" AS "Organization__units_contact", "Organization__units"."allowedWareGroupsIds" AS "Organization__units_allowedWareGroupsIds", "Organization__units"."organizationId" AS "Organization__units_organizationId", "Organization__units"."type" AS "Organization__units_type" FROM "site" "Organization" LEFT JOIN "site" "Organization__university" ON "Organization__university"."id"="Organization"."universityId"  LEFT JOIN "site" "Organization__units" ON "Organization__units"."organizationId"="Organization"."id" WHERE  "Organization"."type" IN ($1)) "distinctAlias" ORDER BY "distinctAlias"."Organization_createdAt" DESC, "Organization_id" ASC LIMIT 2 OFFSET 1 -- PARAMETERS: ["Organization"]
query: SELECT "Organization"."id" AS "Organization_id", "Organization"."createdAt" AS "Organization_createdAt", "Organization"."updatedAt" AS "Organization_updatedAt", "Organization"."name" AS "Organization_name", "Organization"."address" AS "Organization_address", "Organization"."location" AS "Organization_location", "Organization"."contact" AS "Organization_contact", "Organization"."universityId" AS "Organization_universityId", "Organization"."type" AS "Organization_type", "Organization__university"."id" AS "Organization__university_id", "Organization__university"."createdAt" AS "Organization__university_createdAt", "Organization__university"."updatedAt" AS "Organization__university_updatedAt", "Organization__university"."name" AS "Organization__university_name", "Organization__university"."address" AS "Organization__university_address", "Organization__university"."location" AS "Organization__university_location", "Organization__university"."contact" AS "Organization__university_contact", "Organization__university"."type" AS "Organization__university_type", "Organization__units"."id" AS "Organization__units_id", "Organization__units"."createdAt" AS "Organization__units_createdAt", "Organization__units"."updatedAt" AS "Organization__units_updatedAt", "Organization__units"."name" AS "Organization__units_name", "Organization__units"."address" AS "Organization__units_address", "Organization__units"."location" AS "Organization__units_location", "Organization__units"."contact" AS "Organization__units_contact", "Organization__units"."allowedWareGroupsIds" AS "Organization__units_allowedWareGroupsIds", "Organization__units"."organizationId" AS "Organization__units_organizationId", "Organization__units"."type" AS "Organization__units_type" FROM "site" "Organization" LEFT JOIN "site" "Organization__university" ON "Organization__university"."id"="Organization"."universityId"  LEFT JOIN "site" "Organization__units" ON "Organization__units"."organizationId"="Organization"."id" WHERE  "Organization"."type" IN ($1) ORDER BY "Organization"."createdAt" DESC -- PARAMETERS: ["Organization"]
```
but i got my whole 7 rows and it seem two query executed!!! 
In above query log, in first log LIMIT and OFFSET clause exist but in the second query they don't exist.

### Second test for First query
It's my second log for skip: 7 and take: 2

```bash
query: SELECT DISTINCT "distinctAlias"."Organization_id" as "ids_Organization_id", "distinctAlias"."Organization_createdAt" FROM (SELECT "Organization"."id" AS "Organization_id", "Organization"."createdAt" AS "Organization_createdAt", "Organization"."updatedAt" AS "Organization_updatedAt", "Organization"."name" AS "Organization_name", "Organization"."address" AS "Organization_address", "Organization"."location" AS "Organization_location", "Organization"."contact" AS "Organization_contact", "Organization"."universityId" AS "Organization_universityId", "Organization"."type" AS "Organization_type", "Organization__university"."id" AS "Organization__university_id", "Organization__university"."createdAt" AS "Organization__university_createdAt", "Organization__university"."updatedAt" AS "Organization__university_updatedAt", "Organization__university"."name" AS "Organization__university_name", "Organization__university"."address" AS "Organization__university_address", "Organization__university"."location" AS "Organization__university_location", "Organization__university"."contact" AS "Organization__university_contact", "Organization__university"."type" AS "Organization__university_type", "Organization__units"."id" AS "Organization__units_id", "Organization__units"."createdAt" AS "Organization__units_createdAt", "Organization__units"."updatedAt" AS "Organization__units_updatedAt", "Organization__units"."name" AS "Organization__units_name", "Organization__units"."address" AS "Organization__units_address", "Organization__units"."location" AS "Organization__units_location", "Organization__units"."contact" AS "Organization__units_contact", "Organization__units"."allowedWareGroupsIds" AS "Organization__units_allowedWareGroupsIds", "Organization__units"."organizationId" AS "Organization__units_organizationId", "Organization__units"."type" AS "Organization__units_type" FROM "site" "Organization" LEFT JOIN "site" "Organization__university" ON "Organization__university"."id"="Organization"."universityId"  LEFT JOIN "site" "Organization__units" ON "Organization__units"."organizationId"="Organization"."id" WHERE  "Organization"."type" IN ($1)) "distinctAlias" ORDER BY "distinctAlias"."Organization_createdAt" DESC, "Organization_id" ASC LIMIT 2 OFFSET 7 -- PARAMETERS: ["Organization"]
```
As i expected, result was empty and just one query executed (i have just 7 row in my table)
LIMIT and OFFSET clause exist in query log.

### Second Query
I changed my query to just retrieve rows without any join (relations).
```typescript
Organization.find({
                order: {
                    createdAt: "DESC"
                },
                skip: pagination.skip,
                take: pagination.take
            });
```
### First test for Second query
It's my log with skip: 1 and take: 2
```bash
query: SELECT "Organization"."id" AS "Organization_id", "Organization"."createdAt" AS "Organization_createdAt", "Organization"."updatedAt" AS "Organization_updatedAt", "Organization"."name" AS "Organization_name", "Organization"."address" AS "Organization_address", "Organization"."location" AS "Organization_location", "Organization"."contact" AS "Organization_contact", "Organization"."universityId" AS "Organization_universityId", "Organization"."type" AS "Organization_type" FROM "site" "Organization" WHERE  "Organization"."type" IN ($1) ORDER BY "Organization"."createdAt" DESC LIMIT 2 OFFSET 1 -- PARAMETERS: ["Organization"]
```
Everything works properly and i got expected rows.

### Conclusion
I can only say it's strange behavior.

**Comment by skytask** [comment]
@AlexMesser @pleerock  Any idea?

**Comment by swim** [comment]
Could you please share what the "relations" object looks like in your first query?

**Comment by skytask** [comment]
It's just an array of string like the example in find-option document.
[https://github.com/typeorm/typeorm/blob/master/docs/find-options.md#basic-options](https://github.com/typeorm/typeorm/blob/master/docs/find-options.md#basic-options)

**Comment by swim** [comment]
Sadly I can't replicate the described issue with relations or sub relations

**Comment by skytask** [comment]
Unfortunately i can't provide anything. I don't access to the code anymore because this issue was related to my previous job.
Thank you for your attention to this matter.

**Comment by swim** [comment]
No worries at all, I saw a similar issue with incorrect select aliases - although your code omitted this I was curious what a getRawMany would return.

@pleerock this can be closed?

**Comment by ladislas14** [comment]
Hi ! I think I'm facing a problem when I'm trying to use multiple joins and then use pagination. 

The schema is like : a post is linked to an user and can have several comments and likes. So I'm trying to get the "trending posts", I mean I retrieve my post, count the comments and likes, and then I sort them using the average of the number of comments and likes. Then, I want to use pagination with take() and skip(), but it seems that TypeORM does not want to add the take and the skip to the request... 

### My query builder 
``` typescript
const posts = await this._postRepository
        .createQueryBuilder('post')
        .select(['post.*', 'users.pseudo'])
        .leftJoin('post.comments', 'comments')
        .leftJoin('post.likes', 'likes')
        .leftJoin('post.user', 'users')
        .where("post.created_at > current_date - interval '5' day")
        .groupBy('post.id')
        .addGroupBy('users.id')
        .addGroupBy('users.pseudo')
        .addSelect('COUNT(DISTINCT (comments.id)) as comments')
        .addSelect('COUNT(DISTINCT (likes.id)) as likes')
        .orderBy(
          '(COUNT(distinct likes.id) + COUNT(distinct comments.id))/2',
          'DESC',
        )
        .take(getOldestTrendingPostRequestDto.take)
        .skip(getOldestTrendingPostRequestDto.skip)
        .getRawMany();
```

### The generated SQL 
```sql
SELECT
   "users"."pseudo" AS "users_pseudo",
   post.*,
   COUNT(DISTINCT ("comments"."id")) AS comments,
   COUNT(DISTINCT ("likes"."id")) AS likes 
FROM
   "post" "post" 
   LEFT JOIN
      "comment" "comments" 
      ON "comments"."post_id" = "post"."id" 
   LEFT JOIN
      "LIKE" "likes" 
      ON "likes"."post_id" = "post"."id" 
   LEFT JOIN
      "users" "users" 
      ON "users"."id" = "post"."user_id" 
WHERE
   post.created_at > CURRENT_DATE - INTERVAL '5' DAY 
GROUP BY
   "post"."id",
   "users"."id",
   "users"."pseudo" 
ORDER BY
(COUNT(DISTINCT "likes"."id") + COUNT(DISTINCT "comments"."id")) / 2 DESC
```

**Comment by thomasgauvin** [comment]
I had this issue as well, take and skip are typeorm level operations that use limit and offset. However, limit and offset do not work well because they limit all rows being returned after the join, which is not the behavior intended (at least not in my case). The solution in my case was to fetch first my base objects with skip and take (or limit and offset), and then do the next query with a whereInIds based off of the ids of my base objects.

**Comment by Menci** [comment]
I think I'm facing this issue too. My query is a little complex so I have no idea why this happens.

```typescript
class ... {
  async queryProblemsAndCount(
    user: UserEntity,
    hasPrivilege: boolean,
    keyword: string,
    tagIds: number[],
    ownerId: number,
    nonpublic: boolean,
    skipCount: number,
    takeCount: number
  ): Promise<[problems: ProblemEntity[], count: number]> {
    const queryBuilder = this.problemRepository.createQueryBuilder("problem").select("problem.id", "id");
    let groupByAdded = false;

    if (tagIds && tagIds.length > 0) {
      queryBuilder
        .innerJoin(ProblemTagMapEntity, "map", "problem.id = map.problemId")
        .andWhere("map.problemTagId IN (:...tagIds)", { tagIds })
        .groupBy("problem.id");
      groupByAdded = true;
      if (tagIds.length > 1) queryBuilder.having("COUNT(DISTINCT map.problemTagId) = :count", { count: tagIds.length });
    }

    if (keyword) {
      queryBuilder
        .innerJoin(
          LocalizedContentEntity,
          "localizedContent",
          'localizedContent.type = :type AND problem.id = localizedContent.objectId',
          { type: LocalizedContentType.PROBLEM_TITLE }
        )
        .andWhere("localizedContent.data LIKE :like", { like: `%${escapeLike(keyword)}%` });

      if (!groupByAdded)
        queryBuilder.groupBy("problem.id");
    }

    if (!hasPrivilege && !(user && ownerId === user.id)) {
      if (user)
        queryBuilder.andWhere(
          new Brackets(brackets =>
            brackets.where("problem.isPublic = 1").orWhere("problem.ownerId = :ownerId", { ownerId: user.id })
          )
        );
      else queryBuilder.andWhere("problem.isPublic = 1");
    } else if (nonpublic) {
      queryBuilder.andWhere("problem.isPublic = 0");
    }
    if (ownerId) {
      queryBuilder.andWhere("problem.ownerId = :ownerId", { ownerId });
    }

    // QueryBuilder.getManyAndCount() has bug with GROUP BY
    const count = Number(
      (
        await this.connection
          .createQueryBuilder()
          .select("COUNT(*)", "count")
          .from(`(${queryBuilder.getQuery()})`, "temp")
          .setParameters(queryBuilder.expressionMap.parameters)
          .getRawOne()
      ).count
    );

    queryBuilder
      .orderBy("problem.displayId IS NOT NULL", "DESC")
      .addOrderBy("problem.displayId", "ASC")
      .addOrderBy("problem.id", "ASC");
    const result = await queryBuilder.skip(skipCount).take(takeCount).getRawMany();
    return [await this.findProblemsByExistingIds(result.map(row => row.id)), count];
  }
}
```

The generated SQL is:

```sql
query: SELECT `problem`.`id` AS `id` FROM `problem` `problem` INNER JOIN `localized_content` `localizedContent` ON `localizedContent`.`type` = ? AND `problem`.`id` = `localizedContent`.`objectId` WHERE `localizedContent`.`data` LIKE ? GROUP BY `problem`.`id` ORDER BY `problem`.`displayId` IS NOT NULL DESC, `problem`.`displayId` ASC, `problem`.`id` ASC -- PARAMETERS: ["PROBLEM_TITLE","%a%"]
```

**Comment by Menci** [comment]
`skip` and `take` doesn't work but `limit` and `offset` works.

**Comment by Menci** [comment]
@imnotjames not only postres, but the driver mariadb also has this bug.

**Comment by BogdanStanciu** [comment]
I have the same issue using `skip` and `take`, with a non-trivial query. The problem is that a distinct clause is added (don't know why) to the query, causing it to fail.

**Comment by kkoomen** [comment]
> `skip` and `take` doesn't work but `limit` and `offset` works.

But the problem with this is that it does give you incorrect results. See #4073 and #3967

**Comment by mikews93** [comment]
This happens to me with both `skip`, `take` and `limit`, `offset` I'm using postgres, when I use `getQuery`, see what the query really looks like, with `skip` and `take` it does not write `Limit` and `Offset` to the actual SQL query but it does with `limit` and `offset`, however when I get the result from the database using `getMany` something happens that it does not bring the right amount of results.

**Comment by jannomeister** [comment]
I'm experiencing this issue also, using `.leftJoinAndSelect` and `.leftJoinAndMapOne`. When I use `skip + take` the data is not returning correctly. Same goes with `offset + limit`

**Comment by jannomeister** [comment]
I think I already have a solution for my problem. Might share it here. Based on this https://github.com/typeorm/typeorm/issues/2912#issuecomment-603209413, when you add the third argument which is the condition for the join it will work now as expected

**Comment by kkoomen** [comment]
So, according to my debugging (using NestJS + MySQL) this is what I've found:
- `limit` and `offset` should only be used when your query has _no_ joins. As soon as you have joins, you will end up with "duplicate" rows, something like this:

```
| id  | first_name | hobbies     |
| --- | ---        | ---         |
| 1   | Bob        | Sports      |
| 1   | Bob        | Drawing     |
| 1   | Bob        | Programming |
| 2   | Alice      | Drawing     |
| 2   | Alice      | Singing     |
```

If you would do `.limit(2)` then this would use `LIMIT 2` in the query itself, thus resulting in only the first 2 records:

```
| id  | first_name | hobbies     |
| --- | ---        | ---         |
| 1   | Bob        | Sports      |
| 1   | Bob        | Drawing     |
```

but actually, these are just 2 results of 2 users where `hobbies` is an array of hobbies and can only result in 2 result if you let TypeORM handle these. See the next point for further explanation.
- `skip` and `take` should be used as soon as you're using and kind of join. Basically what it does is  get all the results, merge them together into entities and then apply skip / take, which performance-wise a bit slower, but there's no other way to handle this. **If you have no joins in your query, it is recommended to use `offset` and `limit` for faster queries.**
- Something worth mentioning as well is the issue of using `.orderBy()` with `.skip()` and `.take()` which is also partially related to #747. When you use `.offset()` and `.limit()` you should use `.orderBy('entity.created_at', 'DESC')` where `created_at` is the raw field name. When you decide to use `.orderBy()` with `.skip()` and `.take()` you should use `.orderBy('entity.createdAt', 'DESC')` where `createdAt` refers to the entity field name like so:

```ts
@Entity('posts')
export class Post {
  @PrimaryGeneratedColumn({ unsigned: true })
  id: number;

  @CreateDateColumn({ name: 'created_at' }) // <--- use `.orderBy('entity.creatd_at', 'DESC')` with `.offset()` and `.limit()`
  createdAt: Date; // <--- use `.orderBy('entity.creatdAt', 'DESC')` with `.skip()` and `.take()`
}
```


NOTE: The above examples I mentioned are always assumed to use `getMany()` or `getOne()`. Try to avoid `getRawMany()` with big and advanced queries.

**Comment by yossely** [comment]
I have a query with **joins** and I'm using `skip` and `take` but they're not being applied to entities so my result ends up with fewer entities than expected because of the duplicates that @kkoomen just explained (I could verify that by comparing the SQL query result and the entities returned with `getMany()`). Even though the SQL query doesn't contain any `LIMIT`. I'm also using `.orderBy()` with entity and fieldname.

**Comment by madipta** [comment]
> I have a query with **joins** and I'm using `skip` and `take` but they're not being applied to entities so my result ends up with fewer entities than expected because of the duplicates that @kkoomen just explained (I could verify that by comparing the SQL query result and the entities returned with `getMany()`). Even though the SQL query doesn't contain any `LIMIT`. I'm also using `.orderBy()` with entity and fieldname.

i have same problem too,, if i remove the join skip and take working just fine

**Comment by madipta** [comment]
> > I have a query with **joins** and I'm using `skip` and `take` but they're not being applied to entities so my result ends up with fewer entities than expected because of the duplicates that @kkoomen just explained (I could verify that by comparing the SQL query result and the entities returned with `getMany()`). Even though the SQL query doesn't contain any `LIMIT`. I'm also using `.orderBy()` with entity and fieldname.
> 
> i have same problem too,, if i remove the join skip and take working just fine

ups.. it work using limit and offset

**Comment by alexweltman** [comment]
> So, according to my debugging (using NestJS + MySQL) this is what I've found:
> 
> * `limit` and `offset` should only be used when your query has _no_ joins. As soon as you have joins, you will end up with "duplicate" rows, something like this:
> 
> ```
> | id  | first_name | hobbies     |
> | --- | ---        | ---         |
> | 1   | Bob        | Sports      |
> | 1   | Bob        | Drawing     |
> | 1   | Bob        | Programming |
> | 2   | Alice      | Drawing     |
> | 2   | Alice      | Singing     |
> ```
> 
> If you would do `.limit(2)` then this would use `LIMIT 2` in the query itself, thus resulting in only the first 2 records:
> 
> ```
> | id  | first_name | hobbies     |
> | --- | ---        | ---         |
> | 1   | Bob        | Sports      |
> | 1   | Bob        | Drawing     |
> ```
> 
> but actually, these are just 2 results of 2 users where `hobbies` is an array of hobbies and can only result in 2 result if you let TypeORM handle these. See the next point for further explanation.
> 
> * `skip` and `take` should be used as soon as you're using and kind of join. Basically what it does is  get all the results, merge them together into entities and then apply skip / take, which performance-wise a bit slower, but there's no other way to handle this. **If you have no joins in your query, it is recommended to use `offset` and `limit` for faster queries.**
> * Something worth mentioning as well is the issue of using `.orderBy()` with `.skip()` and `.take()` which is also partially related to #747. When you use `.offset()` and `.limit()` you should use `.orderBy('entity.created_at', 'DESC')` where `created_at` is the raw field name. When you decide to use `.orderBy()` with `.skip()` and `.take()` you should use `.orderBy('entity.createdAt', 'DESC')` where `createdAt` refers to the entity field name like so:
> 
> ```ts
> @Entity('posts')
> export class Post {
>   @PrimaryGeneratedColumn({ unsigned: true })
>   id: number;
> 
>   @CreateDateColumn({ name: 'created_at' }) // <--- use `.orderBy('entity.creatd_at', 'DESC')` with `.offset()` and `.limit()`
>   createdAt: Date; // <--- use `.orderBy('entity.creatdAt', 'DESC')` with `.skip()` and `.take()`
> }
> ```
> 
> NOTE: The above examples I mentioned are always assumed to use `getMany()` or `getOne()`. Try to avoid `getRawMany()` with big and advanced queries.

Yep that fixed it for me. Very interesting.

**Comment by vthanghq1** [comment]
> > So, according to my debugging (using NestJS + MySQL) this is what I've found:
> > 
> > * `limit` and `offset` should only be used when your query has _no_ joins. As soon as you have joins, you will end up with "duplicate" rows, something like this:
> > 
> > ```
> > | id  | first_name | hobbies     |
> > | --- | ---        | ---         |
> > | 1   | Bob        | Sports      |
> > | 1   | Bob        | Drawing     |
> > | 1   | Bob        | Programming |
> > | 2   | Alice      | Drawing     |
> > | 2   | Alice      | Singing     |
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you would do `.limit(2)` then this would use `LIMIT 2` in the query itself, thus resulting in only the first 2 records:
> > ```
> > | id  | first_name | hobbies     |
> > | --- | ---        | ---         |
> > | 1   | Bob        | Sports      |
> > | 1   | Bob        | Drawing     |
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but actually, these are just 2 results of 2 users where `hobbies` is an array of hobbies and can only result in 2 result if you let TypeORM handle these. See the next point for further explanation.
> > 
> > * `skip` and `take` should be used as soon as you're using and kind of join. Basically what it does is  get all the results, merge them together into entities and then apply skip / take, which performance-wise a bit slower, but there's no other way to handle this. **If you have no joins in your query, it is recommended to use `offset` and `limit` for faster queries.**
> > * Something worth mentioning as well is the issue of using `.orderBy()` with `.skip()` and `.take()` which is also partially related to #747. When you use `.offset()` and `.limit()` you should use `.orderBy('entity.created_at', 'DESC')` where `created_at` is the raw field name. When you decide to use `.orderBy()` with `.skip()` and `.take()` you should use `.orderBy('entity.createdAt', 'DESC')` where `createdAt` refers to the entity field name like so:
> > 
> > ```ts
> > @Entity('posts')
> > export class Post {
> >   @PrimaryGeneratedColumn({ unsigned: true })
> >   id: number;
> > 
> >   @CreateDateColumn({ name: 'created_at' }) // <--- use `.orderBy('entity.creatd_at', 'DESC')` with `.offset()` and `.limit()`
> >   createdAt: Date; // <--- use `.orderBy('entity.creatdAt', 'DESC')` with `.skip()` and `.take()`
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > NOTE: The above examples I mentioned are always assumed to use `getMany()` or `getOne()`. Try to avoid `getRawMany()` with big and advanced queries.
> 
> Yep that fixed it for me. Very interesting.

thanks. it works like a charm.

**Comment by benjamin658** [comment]
> So, according to my debugging (using NestJS + MySQL) this is what I've found:
> 
> * `limit` and `offset` should only be used when your query has _no_ joins. As soon as you have joins, you will end up with "duplicate" rows, something like this:
> 
> ```
> | id  | first_name | hobbies     |
> | --- | ---        | ---         |
> | 1   | Bob        | Sports      |
> | 1   | Bob        | Drawing     |
> | 1   | Bob        | Programming |
> | 2   | Alice      | Drawing     |
> | 2   | Alice      | Singing     |
> ```
> 
> If you would do `.limit(2)` then this would use `LIMIT 2` in the query itself, thus resulting in only the first 2 records:
> 
> ```
> | id  | first_name | hobbies     |
> | --- | ---        | ---         |
> | 1   | Bob        | Sports      |
> | 1   | Bob        | Drawing     |
> ```
> 
> but actually, these are just 2 results of 2 users where `hobbies` is an array of hobbies and can only result in 2 result if you let TypeORM handle these. See the next point for further explanation.
> 
> * `skip` and `take` should be used as soon as you're using and kind of join. Basically what it does is  get all the results, merge them together into entities and then apply skip / take, which performance-wise a bit slower, but there's no other way to handle this. **If you have no joins in your query, it is recommended to use `offset` and `limit` for faster queries.**
> * Something worth mentioning as well is the issue of using `.orderBy()` with `.skip()` and `.take()` which is also partially related to [[Question] QueryBuilder - Issues with executing a query builder. #747](https://github.com/typeorm/typeorm/issues/747). When you use `.offset()` and `.limit()` you should use `.orderBy('entity.created_at', 'DESC')` where `created_at` is the raw field name. When you decide to use `.orderBy()` with `.skip()` and `.take()` you should use `.orderBy('entity.createdAt', 'DESC')` where `createdAt` refers to the entity field name like so:
> 
> ```ts
> @Entity('posts')
> export class Post {
>   @PrimaryGeneratedColumn({ unsigned: true })
>   id: number;
> 
>   @CreateDateColumn({ name: 'created_at' }) // <--- use `.orderBy('entity.creatd_at', 'DESC')` with `.offset()` and `.limit()`
>   createdAt: Date; // <--- use `.orderBy('entity.creatdAt', 'DESC')` with `.skip()` and `.take()`
> }
> ```
> 
> NOTE: The above examples I mentioned are always assumed to use `getMany()` or `getOne()`. Try to avoid `getRawMany()` with big and advanced queries.

What if I want to order by joined table's column? I use the `take` and `addOrderBy`, the behavior is really confusing.

**Comment by Azamatjon** [comment]
This problem was fixed in the last version of current date `0.2.40`

**Comment by DrEhsan** [comment]
For me when the relation between base entity and the relation entity is `OneToMany` this happens and `limit = 2` will result 2 records of relation entity. in this situation the `take + skip` will work correct.

But when the relation between base entity and the relation entity is `ManyToOne` the `limit + offset` are working as expected.

**Comment by hastalavistababy** [comment]
> `skip` and `take` doesn't work but `limit` and `offset` works.

Worked for me

**Comment by Gleb-Gaiduk** [comment]
> I have the same issue using `skip` and `take`, with a non-trivial query. The problem is that a distinct clause is added (don't know why) to the query, causing it to fail.

Yes, I have a problem with DISTINCT too which is added to query by .take() method.
Issue: https://github.com/typeorm/typeorm/issues/8605

**Comment by MoSattler** [comment]
> Something worth mentioning as well is the issue of using .orderBy() with .skip() and .take() which is also partially related to https://github.com/typeorm/typeorm/issues/747

Is there any way around this? Right now skip and take give me wrong values, and I guess it's because of an orderBy

**Comment by netojose** [comment]
2022 and I having the same issue on postgres. I solved replacing `skip()` and `take()` by `limit()` and `offset()`

**Comment by longto** [comment]
Awaiting for 6 month and it still haven't fixed yet. I will give a try on Prisma

**Comment by veeresh-dg** [comment]
Facing same issue for mysql also, it's working for limit and offfset.

**Comment by LuckyArd110** [comment]
> Facing same issue for mysql also, it's working for limit and offfset.

Same with postgres, works using limit and offset.

**Comment by yearsalary** [comment]
Same with mariadb, works using limit.
It should be fixed!

**Comment by pablo-padua** [comment]
I ran into the same issue with mssql, I had a pagination middleware that used the `.find()` method and `skip` and `take` worked fine, however I was forced to use the `.createQueryBuilder()` and `getRawMany()` methods when I needed some specific fields that were part of the entity's relationship... Using `.offset()` instead of `skip` and `limit` instead of `take` worked out great for me. Thanks for the suggestion @Menci

**Comment by chemic** [comment]
3 years and still not fixed? I though TypeORM was a serious ORM :(

**Comment by LuckyArd110** [comment]
> 3 years and still not fixed? I though TypeORM was a serious ORM :(

This is just Open Source ORM, maybe the owner have no time, and its depend on the community too btw.

**Comment by cdbattags** [comment]
Any new updates here? We're facing the same today.

**Comment by marhako** [comment]
> > So, according to my debugging (using NestJS + MySQL) this is what I've found:
> > 
> > * `limit` and `offset` should only be used when your query has _no_ joins. As soon as you have joins, you will end up with "duplicate" rows, something like this:
> > 
> > ```
> > | id  | first_name | hobbies     |
> > | --- | ---        | ---         |
> > | 1   | Bob        | Sports      |
> > | 1   | Bob        | Drawing     |
> > | 1   | Bob        | Programming |
> > | 2   | Alice      | Drawing     |
> > | 2   | Alice      | Singing     |
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you would do `.limit(2)` then this would use `LIMIT 2` in the query itself, thus resulting in only the first 2 records:
> > ```
> > | id  | first_name | hobbies     |
> > | --- | ---        | ---         |
> > | 1   | Bob        | Sports      |
> > | 1   | Bob        | Drawing     |
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but actually, these are just 2 results of 2 users where `hobbies` is an array of hobbies and can only result in 2 result if you let TypeORM handle these. See the next point for further explanation.
> > 
> > * `skip` and `take` should be used as soon as you're using and kind of join. Basically what it does is  get all the results, merge them together into entities and then apply skip / take, which performance-wise a bit slower, but there's no other way to handle this. **If you have no joins in your query, it is recommended to use `offset` and `limit` for faster queries.**
> > * Something worth mentioning as well is the issue of using `.orderBy()` with `.skip()` and `.take()` which is also partially related to [[Question] QueryBuilder - Issues with executing a query builder. #747](https://github.com/typeorm/typeorm/issues/747). When you use `.offset()` and `.limit()` you should use `.orderBy('entity.created_at', 'DESC')` where `created_at` is the raw field name. When you decide to use `.orderBy()` with `.skip()` and `.take()` you should use `.orderBy('entity.createdAt', 'DESC')` where `createdAt` refers to the entity field name like so:
> > 
> > ```ts
> > @Entity('posts')
> > export class Post {
> >   @PrimaryGeneratedColumn({ unsigned: true })
> >   id: number;
> > 
> >   @CreateDateColumn({ name: 'created_at' }) // <--- use `.orderBy('entity.creatd_at', 'DESC')` with `.offset()` and `.limit()`
> >   createdAt: Date; // <--- use `.orderBy('entity.creatdAt', 'DESC')` with `.skip()` and `.take()`
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > NOTE: The above examples I mentioned are always assumed to use `getMany()` or `getOne()`. Try to avoid `getRawMany()` with big and advanced queries.
> 
> What if I want to order by joined table's column? I use the `take` and `addOrderBy`, the behavior is really confusing.

in my case naming .createQueryBuilder('entityShortName') was a bad decision, I tried renaming it to the original entity's name that we usually use in SQL scripts (let's say it was 'entitys_log_long_name'), that fixed the .orderBy() and .take() funtions's errors, they are not compatible otherwise.

**Comment by hastalavistababy** [comment]
> Any new updates here? We're facing the same today.

Same, As I know not fixed yet

**Comment by dimartiro** [comment]
4 years and still not fixed? really? I cannot use `skip` and `take` to paginate through 100k records. Common

**Comment by dev1pavlo** [comment]
Instead of writing skip/take (that creates outer subquery with DISTINCT)
```
const [users, count] = await query
      .skip(10)
      .take(10)
      .orderBy('createdAt', 'ASC')
      .getManyAndCount();
```

I managed to do it like this:
```
const [users, count] = await query
      .distinct()
      .offset(10)
      .limit(10)
      .orderBy('createdAt', 'ASC')
      .getManyAndCount();
```

So basically I gave limit/offset an opportunity to fetch dublicates, but erased them using distinct.
To increase performance you can try using `distinctOn`

**Comment by netojose** [comment]
Me too, since 2022 replacing `skip()` and `take()` by `limit()` and `offset()`

**Comment by dimartiro** [comment]
I've been trying the use of `skip` & `take` and they end up translated to `limit` and `offset` in SQL for `find` like queries (not using query builder)

**Comment by falyoun** [comment]
Same here, any update on this?

**Comment by Arsenalist** [comment]
Neither of these work if you try to sort by a joined column.

**Comment by dimartiro** [comment]
Based on my experience this is solved in postgres, I'm using multiple complex find queries with `skip` and `take` and they are correctly translated into limit and offset as I expected.

Can you bring more examples with all the related entities or an example repo to reproduce?

**Comment by royalrover** [comment]
not work in mysql, 4 years later....

**Comment by santimakci** [comment]
Same problem here. When I add take and limit I have this error:

`Unknown column 'distinctAlias.car_updatedAt' in 'field list'`

WIthout pagination, It works fine.

**Comment by lolicrafter** [comment]
ohh, now 2023, near 2024. still a problem.  i spent 2 hours to resolve this problem. finally,use limit()&offset(), not take()&skip()

**Comment by IslamGoher** [comment]
use `offset` and `limit` instead.

**Comment by hansruebenichs** [comment]
Still the same problem. I was trying to order by name using COALESCE 
```typescript
// WRONG
.addSelect(`COALESCE(x.name, y.name) AS combinedName`)
.skip()
.take()

query.orderBy(`combinedName`, sort ?? 'DESC', 'NULLS LAST')
``` 

without success receiving this message `"for SELECT DISTINCT, ORDER BY expressions must appear in select list",`
Then I changed to limit()&offset() as suggested and it's **working**

```typescript
// RIGHT
.addSelect(`COALESCE(x.name, y.name) AS combinedName`)
.limit()
.offset();

query.orderBy(`combinedName`, sort ?? 'DESC', 'NULLS LAST')
```

**Comment by shapovalovand** [comment]
Same problem https://github.com/typeorm/typeorm/issues/9342

**Comment by Samandar02** [comment]
In my situation also it didn't work but with using queryBuilder solved my problem
```diff
// ...
  let qb = await this.ds.getRepository(ServiceEntity).createQueryBuilder('svc')
  qb.innerJoinAndSelect( ...
  qb.innerJoinAndSelect( ...
//...
+ qb.limit(dto.take).offset(dto.skip) 
//...
```

**Comment by notophir** [comment]
> `skip` and `take` doesn't work but `limit` and `offset` works.

Savior !

**Comment by henriquensco** [comment]
In my case, to solve this, I used:

```
const { limit, offset } = paginationDto;

    const skip = parseInt(offset);
    const take = parseInt(limit);

    const products = await this.productRepository
      .findAndCount({
        where: { tenancy: { uuid: headers.tenancy } },
        select: ['uuid', 'title', 'barCode', 'description', 'createdAt'],
        order: {
          createdAt: 'DESC'
        },
        loadEagerRelations: false,
        skip: (skip) * (take),
        take: take
      })
```

I tried the solutions in the comments above, it's worked, but not the way I expected.

**Comment by NicolasGorga** [comment]
Any updates on this? I am trying to use pagination for getRawMany(), since i am creating a reportings API

**Comment by yigithanbalciacc** [comment]
> Any updates on this? I am trying to use pagination for getRawMany(), since i am creating a reportings API
@NicolasGorga 

I have used the solution @Menci  provided, it solves the problem in my case. I guess this issue will stay open for a long time. I will just use this solution: 

> `skip` and `take` doesn't work but `limit` and `offset` works.

**Comment by gioboa** [comment]
I created this test to verify the issue.
```
@Entity()
export class University {
    @PrimaryGeneratedColumn()
    id: number

    @Column()
    name: string

    @OneToMany("Organization", "university")
    organizations: any[]
}

@Entity()
export class Unit {
    @PrimaryGeneratedColumn()
    id: number

    @Column()
    name: string

    @ManyToOne("Organization", "units")
    organization: any
}

@Entity()
export class Organization {
    @PrimaryGeneratedColumn()
    id: number

    @Column()
    name: string

    @CreateDateColumn()
    createdAt: Date

    @ManyToOne(() => University, (university) => university.organizations)
    university: University

    @OneToMany(() => Unit, (unit) => unit.organization)
    units: Unit[]
}

describe("github issues > #4742 Skip and take doesn't work with join", () => {
    let dataSources: DataSource[]
    before(async () => {
        dataSources = await createTestingConnections({
            entities: [Organization, University, Unit],
            schemaCreate: true,
            dropSchema: true,
        })
    })
    beforeEach(() => reloadTestingDatabases(dataSources))
    after(() => closeTestingConnections(dataSources))

    it("should return correct number of records when using skip and take with relations", async () => {
        await Promise.all(
            dataSources.map(async (dataSource) => {
                const university = new University()
                university.name = "Test University"
                await dataSource.manager.save(university)

                const organizations: Organization[] = []
                for (let i = 0; i < 7; i++) {
                    const organization = new Organization()
                    organization.name = "Organization " + i
                    organization.university = university
                    organizations.push(organization)
                }
                await dataSource.manager.save(organizations)

                for (const org of organizations) {
                    for (let j = 0; j < 3; j++) {
                        const unit = new Unit()
                        unit.name = "Unit " + j + " for " + org.name
                        unit.organization = org
                        await dataSource.manager.save(unit)
                    }
                }

                const queryOptions = {
                    relations: ["university", "units"],
                    order: {
                        createdAt: "DESC" as const,
                    },
                    skip: 1,
                    take: 2,
                }

                const result = await dataSource.getRepository(Organization).find(queryOptions)
                expect(result.length).to.equal(2)
            })
        )
    })
})
```

It works correctly so I'm closing this issue for now, feel free to re-open it if it's still an issue for you. Thanks 👍
