### ISSUE TITLE
Unable to set multi-column indices with 0.1.0-alpha.2

### ISSUE THREAD

**Issue by stonecold123** [typeorm/typeorm#495]
I'm getting this error on starting the server after updating to  `0.1.0-alpha.2` from `0.0.9`

Error: Index "table_index_userId_mid" contains columns that are missing in the entity: userId, mid
````
@Entity()
@Index("table_index_userId_mid", (post: Item) => [post.userId, post.mid])
export class Item {
    @PrimaryGeneratedColumn()
    postId: number;

    @OneToOne(type => UserData, users=>users.userId)
    @JoinColumn({ name: "userId" })
    userData: UserData;

    @Column({ type: "int"})
    userId: number;

    @Column({type:'int'})
    mid:number;
}
````

**Comment by pleerock** [comment]
this is fixed and will be released in `0.1.0-alpha.3`

**Comment by stonecold123** [comment]
@pleerock , I'm still getting the error from this table `RelatedItem` in `0.1.0-alpha.3`. Can you spot the problem? I'm joinning separately the `relatedModelId` and `modelId` on the `modelId` column from ItemInfo, but then I can't create a multi-column index `idx_related_items`.

````
Error: Index "idx_related_items" contains columns that are missing in the entity: modelId, relatedModelId
````

````
@Entity()
@Index("idx_related_items", (post: RelatedItems) => [post.modelId,post.relatedModelId])
export class RelatedItems{

    @PrimaryGeneratedColumn()
    postId: number;

    @OneToOne(type=>ItemInfo,entity=>entity.modelId)
    @JoinColumn({name:'modelId'})
    itemInfo:ItemInfo;

    @Column({type:'int'})
    modelId:number;

    @OneToOne(type=>ItemInfo,entity=>entity.modelId)
    @JoinColumn({name:'relatedModelId',referencedColumnName:'modelId'})
    relatedItemInfo:ItemInfo;

    @Column({type:'int',nullable:true})
    relatedModelId:number;

    @Column({type:'text',nullable:true})
    comment:string;
}
````

ItemInfo:

````
@Entity()
export class ItemInfo {

    @PrimaryGeneratedColumn()
    mid: number;

    @Column({type: 'int', nullable: true})
    modelId: number;

    @Column({type: 'text'})
    overviews: string;
}


````
