### ISSUE TITLE
createConnection throws UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by jayarjo** [typeorm/typeorm#5019]
**Issue type:**

[x] bug report

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[x] `0.2.20`

If for whatever reason connection cannot be established (wrong port lets say), `createConnection` throws unhandled rejection error, although I have a proper `catch` clause attached to it.

```
(node:5708) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT x.x.x.x:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
(node:5708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by silentroach** [comment]
can you provide your try..catch code?

**Comment by PtrBld** [comment]
I have the same issue. My code looks like this:

`const connection = await createConnection().catch(err => { console.log("Error"); });`

**Comment by silentroach** [comment]
strange mix of async/await and promises, but I tried it and it work fine 🤷‍♂

**Comment by Porisey** [comment]
Probably problem in node-postgres package. Got same with pg:7.18.2 and postgres db v12. Fixed by update to pg:8

**Comment by brian-pinwheel** [comment]
I am using pg 8.5.1 and experiencing the issue still, so upgrading for version 8 didn't resolve it for me.  Totally makes sense that this could be a problem with the node-postgres package

**Comment by imnotjames** [comment]
I cannot replicate this.

**Comment by imnotjames** [comment]
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
