### ISSUE TITLE
Migrations failing on timestamp validation

### ISSUE THREAD

**Issue by DavidPMacNeil** [typeorm/typeorm#528]
Version 0.1.0-alpha4

After connecting to a DB, running 
`await connection.runMigrations();`

gives the following error:

`0 migrations are already loaded in the database.
[3] 1 migrations were found in the source code.
[3] 1 migrations are new migrations that needs to be executed.
[3] query failed: INSERT INTO "migrations"("timestamp", "name") VALUES (@0,@1) -- PARAMETERS: [1496951117999,"CatChanges1496951117999"]
[3] (node:18936) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RequestError: Validation failed for parameter '0'. Value must be between -2147483648 and 2147
483647.`

**Comment by pleerock** [comment]
@Spoki4 didn't you had such problem?

**Comment by pleerock** [comment]
just checked it works fine on mysql, @DavidPMacNeil what database are you using?

**Comment by Spoki4** [comment]
I didn't have this problem. Maybe because I execute migrations like this:
```typescript
class MigrationsExecutor extends MigrationExecutor {

    async getPendingMigrations() {
        const allMigrations = this.getMigrations()
        const executedMigrations = await this.loadExecutedMigrations()

        return allMigrations.filter(migration => {
            const executedMigration = executedMigrations.find(executedMigration => {
                return executedMigration.name === migration.name
            })
            return !executedMigration
        })
    }
}

try {
    const migrationsExecutor = new MigrationsExecutor(connection)
    const pendingMigrations = (await migrationsExecutor.getPendingMigrations())
                            .map(item => {
                                return [item.name, item.timestamp]
                           })

     await migrationsExecutor.executePendingMigrations()
     console.log(pendingMigrations)
} catch (e) {
     console.log(e)
 }
```

It code not good, but it's work to me fine

**Comment by DavidPMacNeil** [comment]
@Spoki4 I may try that executor shortly early next week. @pleerock I am using SQL Server

**Comment by artaommahe** [comment]
Same issue on adding new (first) migration via cli
```
executing query: INSERT INTO `migrations`(`timestamp`, `name`) VALUES (?,?) -- PARAMETERS: [1497730906301,"ThirdpartyOauthVkInit1497730906301"]
query failed: INSERT INTO `migrations`(`timestamp`, `name`) VALUES (?,?) -- PARAMETERS: [1497730906301,"ThirdpartyOauthVkInit1497730906301"]
executing query: ROLLBACK
{ Error: Incorrect datetime value: '1497730906301' for column 'timestamp' at row 1
    at Packet.asError (/vagrant/backend/node_modules/mysql2/lib/packets/packet.js:701:13)
    at Query.Command.execute (/vagrant/backend/node_modules/mysql2/lib/commands/command.js:28:22)
    at PoolConnection.Connection.handlePacket (/vagrant/backend/node_modules/mysql2/lib/connection.js:500:28)
    at PacketParser.onPacket (/vagrant/backend/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (/vagrant/backend/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/vagrant/backend/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
  code: 'ER_TRUNCATED_WRONG_VALUE',
  errno: 1292,
  sqlState: '#22007' }
```
MySQL db

**Comment by pleerock** [comment]
fixed in `0.1.0-alpha.12`

**Comment by DavidPMacNeil** [comment]
I'm actually still getting this issue in MSSQL, I just tried now again.

`
query failed: INSERT INTO "migrations"("timestamp", "name") VALUES (@0,@1) -- PARAMETERS: [1499351118180,"test1499351118180"]
[2] (node:16608) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RequestError: Validation failed for parameter '0'. Value must be between -2147483648 and 21
47483647.
`

Do we know where this validation failure could be coming from?

**Comment by pleerock** [comment]
looks like another bug. fixed in `0.1.0-alpha.31`

**Comment by DavidPMacNeil** [comment]
Awesome thanks.
