### ISSUE TITLE
Cannot read property 'connect' of undefined

### ISSUE THREAD

**Issue by stephanoparaskeva** [typeorm/typeorm#5733]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
#### Configuration Options
```JavaScript
export const test: Pool = {
  default: {
    name: 'default',
    type: 'postgres',
    host: 'localhost',
    port: 5432,
    username: 'test',
    password: '',
    database: 'main_test',
    logging: false,
    synchronize: true,
    migrations: ['db/migration/**/*{.ts,.js}'],
    subscribers: ['db/subscriber/**/*{.ts,.js}'],
    entities: ['dist/**/*.entity{.ts,.js}', 'app/**/*.entity{.ts,.js}'],
    cli: {
      migrationsDir: 'db/migration',
      subscribersDir: 'db/subscriber',
      entitiesDir: '',
    },
  },
};
```

#### Code
```JavaScript
import supertest from 'supertest';
import { createServer } from 'http';
import { createConnection, getConnection } from 'typeorm';
import { test } from '../../config/connections';
import app from '../../app';

describe('Category - Testing', () => {
  beforeEach(async () => createConnection(test.default));
  afterEach(async () => getConnection('default').close());

  const testServer = supertest(createServer(app));

  it('responds with status code 200', async () => {
    const x = async () => {
      try {
        await testServer.get('/categories');
      } catch (err) {
        console.log(err);
      }
    };
    expect(x).toThrow();
  });
});

```

#### Error
```JavaScript
TypeError: Cannot read property 'connect' of undefined
        at /Users/Stephano/Development/code-basket/application_6374/src/driver/postgres/PostgresDriver.ts:774:25
        at new Promise (<anonymous>)
        at PostgresDriver.Object.<anonymous>.PostgresDriver.obtainMasterConnection (/Users/Stephano/Development/code-basket/application_6374/src/driver/postgres/PostgresDriver.ts:773:16)
        at PostgresQueryRunner.Object.<anonymous>.PostgresQueryRunner.connect (/Users/Stephano/Development/code-basket/application_6374/src/driver/postgres/PostgresQueryRunner.ts:90:58)
        at PostgresQueryRunner.<anonymous> (/Users/Stephano/Development/code-basket/application_6374/src/driver/postgres/PostgresQueryRunner.ts:163:55)

```

**Comment by tarcisiobruni** [comment]
Im having the same error when running test step in CI/CD from Gitlab.

**Comment by michaeldever** [comment]
Same error when running test step in Github actions.

**Comment by tarcisiobruni** [comment]
I think It may be an error caused by 'pg' lib package. Some days ago was made an new release. I'll try a downgrade with 7.x.x version

**Comment by michaeldever** [comment]
@tarcisiobruni Was this working previously in your project? I've just setup a new project, so unsure if it's something in that or something has changed for existing project.

**Comment by michaeldever** [comment]
I downgraded to`7.18.2` and I still see the error.

**Comment by tarcisiobruni** [comment]
@michaeldever Yes, was working perfectly 5 days ago. Any positive behavior I'll report here.

**Comment by michaeldever** [comment]
@tarcisiobruni Thanks for letting me know, I can hold off digging through my code until I know if it's an issue or not so. FWIW, I tried `7.14.0` as well and see the same issue.

**Comment by tarcisiobruni** [comment]
@michaeldever , what version of NodeJs is running while tests has been executed?

**Comment by michaeldever** [comment]
@tarcisiobruni if we ever cross paths IRL, drinks are on me.

Changed to `node:13-alpine` and the tests run as expected. I had been on `node:alpine` which was pulling version node 14.

**Comment by rebolyte** [comment]
Same problem here, running Node 12.8.1.

**Comment by ctrlplusb** [comment]
I had the same issue and then managed to debug it down to the fact that I had some code that was disposing my connection prior to another TypeORM operation occurring. Worth looking at your code if this may be the culprit for some of you.  The error message isn't exactly helpful in this regard.

**Comment by imnotjames** [comment]
Are y'all still have this issue in Typeorm 0.2.27?

**Comment by Sun1ive** [comment]
0.2.29 typeorm
8.5.1 pg

Same issue in runtime.
But i have the db connection established. queries continue to works

**Comment by LeoInCode** [comment]
I have was the same problem, and the reason is local path in the migrations. I fix trying change the local path.

**Comment by dev-juju** [comment]
I had same problem. Turns out my connection was not even being established. Just added some logging and saw why the connection was failing. Turns out I was using wrong postgresql array syntax in  one of my entities.
Fixed the syntax error, connection established successfully and connection error disappeared. 

Verify your connection is actually successful or catch and fix possible errors 

```javascript
    try {
      await createConnection();
      console.log('Database connection established!');
    }
    catch (err) {
      console.error(err);
    }
```

**Comment by Ovyerus** [comment]
Getting this with `typeorm@0.2.35`, `pg@8.7.1` and on both Node `14.17.3` and `12.22.3` (making sure it wasn't just a 14 error), and using Jest.

First couple of tests run fine, and then one errors with this, and then all the following tests run fine, but Jest doesn't exit because a `TCPWRAP` keeps it open, presumably from the failed connection. Been tearing my hair out trying to figure this out and I'm completely stuck.

**Comment by manisha-11-dev** [comment]
> Are y'all still have this issue in Typeorm 0.2.27? & with using pg 8.0.3?

am still facing issue  - 'TypeError: Cannot read property 'connect' of undefined'

versions am using ::

node - v12.20.1
npm - 6.14.10
pg - 8.7.1
typeorm - 0.2.16

please help as its really urgent. I am fixing a high priority issue by researching around whether typeorm support dynamic connection via fetching db creds from aws secrets manager. I have successfully fetched it but now am looking into how we can retry the connection in case of newly fetched values.

**Comment by imnotjames** [comment]
You're probably not connected.  `0.2.16` is pretty old.

https://github.com/typeorm/typeorm/pull/7995 Might help
