### ISSUE TITLE
Wrong ordering of fields in composite index.

### ISSUE THREAD

**Issue by bartlomiej-korpus** [typeorm/typeorm#587]
When creating a composite index, the ordering of fields isn't maintained, instead, ordering of the columns returned by metadata is used.
The bug is in file
[https://github.com/typeorm/typeorm/blob/0.1.0/src/metadata/IndexMetadata.ts](IndexMetadata.ts)

in lines 78-100, the filtering used to detect inexistent fields changes the order.

I would like to make a PR against 0.0.x branch first, as thats what I am using at the moment.

**Comment by pleerock** [comment]
if you want to create PR against 0.0.x feel free to do that, but be aware that in 0.0.x composite primary keys were not working correctly (especially in relations). Correct composite primary keys support is one of the major change in 0.1.0.

Also link you sent is wrong, there is no 0.1.0 branch in typeorm repo.

**Comment by bartlomiej-korpus** [comment]
Wow, I have no idea where I got that link, though I copy-pasted it from the browser.
Yes I've read the composite primary keys don't work correctly, these indices I am using for indexing for faster searches.

This is the correct [https://github.com/typeorm/typeorm/blob/0.0.x-version/src/metadata/IndexMetadata.ts#L97](link)

Also I can see 0.1.0 branch in TypeORM repo.

**Comment by pleerock** [comment]
Okay, send a PR. Why are you using `0.0.x`. I strongly recommend you to switch to 0.1.0 because it has lot of important fixes.

**Comment by bartlomiej-korpus** [comment]
I thought that -alpha postfix meant it shouldn't be used in production yet. Should it?

**Comment by pleerock** [comment]
theoretically everything under 1.0.0 should not be used in production 😆 I recommend you to use it, but I constantly make changes, so be ready to change your code and table schema if needed. Also probably incremental changes will be easier for you then migrate from 0.0.x to 0.1.0 then.

**Comment by bartlomiej-korpus** [comment]
Okay, I will migrate! How many versions do you expect between now and 0.1.0?

**Comment by pleerock** [comment]
many, hundreds probably 😆

**Comment by bartlomiej-korpus** [comment]
Do you document changes between alphas? Or is there some place with docs for 0.1.0? typeorm.github.io is for 0.0.11 right?

**Comment by pleerock** [comment]
right `typeorm.github.io` is for 0.0.11 at the moment, I simply don't have time to maintain that too. I don't document changes between alphas, but I do document all major changes between 0.0.11 and 0.1.0 in a changelog. But I have to say there are not so much changes between versions, but the exist. If you won't like it you can fix your version.

**Comment by bartlomiej-korpus** [comment]
Thanks! I am starting migration right now, I will also send a PR with if the problem still occurs.

**Comment by pleerock** [comment]
fix is released in latest version.

**Comment by bartlomiej-korpus** [comment]
There is still more to come in this matter. The fix that I've PR'd fixed the bug for simple fields, but this is still present for relation fields(ManyToOne), as they are being replaced with their respective *Id fields.
I am looking into it.
