### ISSUE TITLE
Foreign keys dropped and re-created in migration:generate

### ISSUE THREAD

**Issue by davidlizeng** [typeorm/typeorm#5960]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[x] `0.2.24`

**Steps to reproduce or a small repository showing the problem:**

1. specify `schema` name in the ormconfig for a Postgres DB.
2. generate initial schema using migration:generate
3. run migration:run to sync schema onto DB.
4. re-run migration:generate. Rather than saying no changes, it will generate a migration with all foreign keys dropped and re-created.

Did some poking around in the codebase, and I think this is a result of https://github.com/typeorm/typeorm/blob/0.2.24/src/schema-builder/RdbmsSchemaBuilder.ts#L791

If I have a table `my_table` in schema `my_schema`:
`tableForeignKey.referencedTableName` will be `my_table`
`metadataForeignKey.referencedTablePath` will be `my_schema.my_table`

This then fails the equality check that the foreign keys already exist.

**Comment by toniopelo** [comment]
I got the same problem with "mariadb".
Did you solve your problem @davidlizeng ?

**Comment by davidlizeng** [comment]
I ended up just not bothering to specify the `schema` name. For postgres this defaults to `public` schema, which was good enough for my use case.

Don't have a real fix though.

**Comment by imnotjames** [comment]
This should be fixed in the next release.  This can be confirmed in the latest dev build - `0.2.38-dev.22676a0`

**Comment by nicgordon** [comment]
Sorry @imnotjames, I am running `0.2.41` and this issue is still happening.

**Comment by imnotjames** [comment]
This seems to be newly happening and is a new issue.

**Comment by nicgordon** [comment]
Would you like me to create a new issue to track it @imnotjames?

**Comment by thomazmz** [comment]
Just to point out that I am also having this problem on multiple projects running TypeORM (v 0.2.45) and MySQL. Is there any other issue  created on behalf of this problem?

**Comment by ertl** [comment]
Not sure if some still has the problem.. I just had the problem with oracle.

The problem was that I had a onUpdate: 'RESTRICT' defined. This seems to be not a valid option for Oracle.. the initial migration was generated and executed without errors. But when I generated a new migration all FK with this invalid option where dropped and recreated...

The reason is simple. the RdbmsSchemaBuilder compared the foreign keys from the .ts files with the foreign keys from the database. With no suprise they didn't match onUpdate: 'RESTRICT' was compared to 'NO ACTION'.

**Comment by andrew310** [comment]
I am now having this issue with postgres. Just upgraded to newest version of Typeorm.

**Comment by TyrionFront** [comment]
Issue still persist - currently tried to update to ^0.317 hoping that at has a fix, but it didn't help. Reverted back to the last synchronized with NestJS - ^0.3.0

**Comment by ertl** [comment]
Hi @TyrionFront:

- Can you provide more information?
- What driver do you use?
- How are your entities configured?
- Can you provide a minimal runnable example?

I had a few of such recreation situations in my codebase... all could be resolved by changing my configuration, as I mentioned in the comment above, where I used the wrong onUpdate type.
