### ISSUE TITLE
Working with Entities (In Subscribers?)

### ISSUE THREAD

**Issue by DavidPMacNeil** [typeorm/typeorm#681]
Hello, 

I'd like to be able to work with an Entity that is sent to my server, whether the full object is sent, or only part of it. 

i.e.
Say we have two tables, `Meal`, and `MealHistory`. If someone ordered a meal, it is in the `Meal` table, when it is complete it gets moved to the `MealHistory` table.

The full meal object is ` { id: int, name: string, quantity: int, complete: boolean }`
Which belongs to the Meal table, the `MealHistory` table has the exact same structure.

When a meal is completed, it is moved to the `MealHistory` table.
I want to be able to move the Meal object by only passing the PK, and complete field like:
`{ id: 1, complete: true }`

However, to do this, we need to pass the whole object to add the complete record into `MealHistory`, additionally, I am not able to remove the original record from the `Meal` table.

My questions are
1. How can I get the whole object at this point? 
2. How can I remove the original object after it has been saved in history?

Right now I am trying to get around this with subscribers.
I am on alpha 31.

Thanks

**Comment by pleerock** [comment]
Please provide a minimal code sample with what you have, what you are doing to resolve your issue and what you want it to be

**Comment by DavidPMacNeil** [comment]
OK, So I found out that I can access the whole entity object using `event.databaseEntity`. in the afterUpdate subscriber.

So, to copy over I can do
```
afterUpdate(event: UpdateEvent <Meal>) {
    ...
    mealHistory = new MealHistory();
    mealHistory.id = event.databaseEntity.id; 
    mealHistory.name = event.databaseEntity.name;
    mealHistory.quantity = event.databaseEntity.quantity;
    mealHistory.complete = event.databaseEntity.complete;

    mealHistoryRepo.save(mealHistory);
}
```

But then, since the meal is complete and I have it moved to history, I don't want the meal to be in the non-history table anymore. However, trying to add `mealRepo.remove(event.databaseEntity)`, or creating a new Meal object and calling remove on it `mealRepo.remove(meal)`, or trying to work on removing the original entity from an `afterInsert` subscriber in `MealHistory` fails, all with the same error.

The error is: 
```
query failed: SELECT "subject" . "id" AS "subject_id", "subject" . "name" AS "subject_name", 
"subject" . "quantity" AS "subject_quantity", "subject" . "complete" AS "subject_complete" 
FROM "Meal" WHERE "id"=@0 -- PARAMETERS [1]
{ 
    RequestError: Timeout: Request failed to complete in 1500ms 
    ... 
}
```

It seems like this is failing because the record is still locked, and it won't allow the original record to be removed, even in the `afterInsert` of `MealHistory`. Am I doing this wrong? Or how should I approach this?

**Comment by DavidPMacNeil** [comment]
OK the issue is solved. To fix it, had to await the connection, and not the removal. It will also not work if both are awaited. 

i.e.
```
async afterUpdate(event: UpdateEvent <Meal>) {
    ...
    const mealRepo = await getEntityManager().getRepository(Meal);
    ...
    mealRepo.remove(event.databaseEntity);
}
```

**Comment by DavidPMacNeil** [comment]
So I found out what is really happening here, or at least what is happening for MSSQL.

In a subscriber event, you can `insert`, `remove`, and `select`, on a different table.
If, however, you are working with the table that the subscriber is listening to, you can only `insert`, and `remove`. Selection is not working and is causing a timeout error.

Say we have entities in our database of:

```
Meal, Dog
```

Now we have a MealSubscriber
```
@EventSubscriber()
export class MealSubscriber implements EntitySubsciberInterface < Meal > {
    listenTo() {
        return Meal;
    }

    async afterUpdate(event: UpdateEvent < Meal >) {
        if (event.databaseEntity.complete) {
            const mealRepo = await getEntityManager().getRepository(Meal);
            const dogRepo = await getEntityManager().getRepository(Dog);

            const meal = new Meal();
            meal.name= 'Ratatouille';
            meal.complete = false;

            // This works
            await mealRepo.save(meal);

            // This also works
            mealRepo.remove(meal);

            // This does not work
            const results = await mealRepo.createQueryBuilder('Meal')
                                                               .where('complete = 1')
                                                               .getMany();
            // This works
            const dogResults = await dogRepo.createQueryBuilder('Dog')
                                                              .where('id > 1')
                                                              .getMany();
        }
    }
}
```

**Comment by pleerock** [comment]
again you forgot to await `remove` in your code. Please don't forget to await your promises or you'll end up creating lot of issues in this repo, I don't have a time to answer them each time.

But your problem here is different. If you want to perform database operations use `event.manager` and only it to do that. Don't use `getEntityManager()` or `getRepository()` or any other global function.

This is due to a transaction. Save is running in a transaction and your data is saved in a transaction which is not committed yet. But global functions you use are running out of transaction.

**Comment by DavidPMacNeil** [comment]
is `event.manager` tied to the specific DB the subscriber is listening to?

**Comment by pleerock** [comment]
event.manager is `EntityManager` which has all method to access any table, or even get a repository for entity you need, e.g. `event.manager.getRepository(Post)`
