### ISSUE TITLE
Appear ERR: "identifier is too long", with Oracle

### ISSUE THREAD

**Issue by destLonY** [typeorm/typeorm#693]
when i use orm to connect oracle database, it's OK.
but when i use "connection.manager.find(Photo)" this function, oracle throw an ERR : "identifier is too long"!
i get a result afer i seek this problem all afternoon, the result is oracle is not allow the tablename'length and the cloumname'length overlimit the oracle‘s restraint, which is 30!
my photo'name is "t_tds_emer_event", and my colum'name is like "emer_event_id","emer_event_type", so i console the sql is "SELECT "t_tds_emer_event", "emer_event_type" AS "t_tds_emer_event_emer_event_type"...", t_tds_emer_event_emer_event_type causes this error!

**Comment by pleerock** [comment]
this is a known and very very annoying issue with oracle. I dind't find a good solution for this problem, for now I suggest to shorten column and alias names

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.23`. You can try it via `npm i typeorm@next`.

**Comment by JaffParker** [comment]
I have installed TypeORM 0.2.11 and I still have this error. Here's the generated query:

```sql
SELECT "StudyRandomizationCriteria"."id" AS "StudyRandomizationCriteria_id",
       "StudyRandomizationCriteria"."studyId" AS "StudyRandomizationCriteria_stId", 
       "StudyRandomizationCriteria"."variableId" AS "StudyRandomizationCriteria_vaId", 
       "StudyRandomizationCriteria"."value" AS "StudyRandomizationCriteria_va", 
       "StudyRandomizationCriteria"."stratum" AS "StudyRandomizationCriteria_st"
   FROM "studyRandomizationCriteria" "StudyRandomizationCriteria"
   WHERE "StudyRandomizationCriteria"."studyId" = :where_0_0_0 -- PARAMETERS: [2]
```

**Comment by derSoerrn95** [comment]
I also run into this issue. Is it possible to add an alias option for `EntityOptions` or better an alias option for `RelationOptions`

**Comment by havsar** [comment]
This issue is still occurring in `typeorm@latest`

**Comment by PQMISSCMP** [comment]
> arreglado y lanzado en `typeorm@0.2.0-alpha.23`. Puedes probarlo a través de `npm i typeorm@next`.

Does that beta version correct only that problem? Does not affect the overall stability of the library?

**Comment by wfpena** [comment]
In case it helps anyone and for future reference.

I was having this same problem with oracle while doing an update using `typeorm@0.2.25`. The update was done like so:

```
const repo = getRepository(Client);
const result = await repo.update(
  { id: client.id },
  updatedClient
);
```

this threw the exception: `ORA-00972: Identifier is too long`

By logging the resulting query/DML I realised the parameters names where based on the `databaseName` property for the OracleDriver.

In the files `OracleDriver.ts` (more precisely in the method `createParameter()`) and `UpdateQueryBuilder.ts` (in the method `createUpdateExpression`) you can see the parameter name is based on `column.databaseName` for Oracle.

**My (hopefully temporary) solution:**

Was to override the `createParameter` method to use a different naming strategy for the parameters like so:

```
const connection = await createConnection({...});
connection.driver.createParameter = (_parameterName: string, index: number): string => {
  return ":" + (index + 1);
}
```

It worked for now but I expect to come up with a different, more elegant and less error prone, solution in the future.
