### ISSUE TITLE
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle

### ISSUE THREAD

**Issue by hengkx** [typeorm/typeorm#7601]
### Expected Behavior

no warn

### Actual Behavior

```
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/listeners/AfterUpdate.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/listeners/BeforeInsert.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/listeners/BeforeRemove.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/listeners/BeforeUpdate.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/listeners/EventSubscriber.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/relations/JoinColumn.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/relations/JoinTable.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/relations/ManyToMany.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/relations/ManyToOne.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/relations/OneToMany.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/relations/OneToOne.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/relations/RelationCount.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/relations/RelationId.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/entity/Entity.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/entity/ChildEntity.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/entity/TableInheritance.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/entity-view/ViewEntity.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/transaction/Transaction.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/transaction/TransactionManager.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/transaction/TransactionRepository.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/tree/TreeLevelColumn.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/tree/TreeParent.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/tree/TreeChildren.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/tree/Tree.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/Index.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/Unique.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/Check.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/Exclusion.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/Generated.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/decorator/EntityRepository.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/repository/BaseEntity.js -> node_modules/typeorm/browser/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/query-builder/DeleteQueryBuilder.js -> node_modules/typeorm/browser/index.js
```

### Steps to Reproduce

1.
2.

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | vX.Y.ZZZ | 
| Typescript version  | vX.Y.ZZZ | 
| TypeORM version     | vX.Y.ZZZ | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [x] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
Might have cleaned some of these up

**Comment by imnotjames** [comment]
Next release this should be fixed - see #7800

**Comment by ahmedsmae** [comment]
"react-native": "0.70.5"
"typeorm": "^0.3.11"

same issue still exists even while using Relation<> Wrapper
