### ISSUE TITLE
Wrong behavior w/ the same table names in different schema

### ISSUE THREAD

**Issue by bettafish15** [typeorm/typeorm#7737]
Hi guys, I am having a problem when I have a single connection to the postgresql and same table name in different schemas.

Example:

file postgres/entities/tableSameName.ts
```js
@Entity('tableSameName', { schema: 'public' })
class TableSameName {
    @PrimaryGeneratedColumn()
    id: number;
}
```

file postgres/entities/public/tableSameName.ts
```js
@Entity('tableSameName', { schema: 'message' })
class TableSameName {
    @PrimaryGeneratedColumn()
    userid: number;

    @Column()
    username: string;
}

```

when i query the 'tableSameName' from public schema the query generated using createQueryBuilder to something like this:
```
select t.userid, t.username from message.tableSameName t;
```

after i debug i found out that when file Connection.js run the findMetadata function, the entityMetadatas array doesnt compare schema when there is two entity with the same name inside the array, and my case is a unlucky one when the entity from message schema is in front of public schema in array order so when findMetadata is run, the entity from message is returned first. leading to wrong query (wrong schema in query). 

Can you guys confirm for me about this or i am just misunderstanding at something? thanks

**Comment by PythonCreator27** [comment]
@bettafish15 Could you post the query code? That would really help. Thanks!

**Comment by bettafish15** [comment]
> @bettafish15 Could you post the query code (along with the imports)? That would really help. Thanks!

``
import { EntityRepository, createQueryBuilder, Repository, getCustomRepository } from 'typeorm';
import { TouchpointContact } from '../postgres/entities/public/TouchpointContact';
import { Template } from '../postgres/entities/public/Template';

@EntityRepository(TouchpointContact)
export default class TouchpointContactRepository extends Repository<TouchpointContact> {
  public async getUnsuccessfulStat(){
    const queryUnsuccessfulStat = createQueryBuilder(Template, 't');
   

    const unsuccessfulStats = await queryUnsuccessfulStat.getMany();
    console.log(unsuccessfulStats);
  }
``

Template is 'tableSameName' in this case

**Comment by imnotjames** [comment]
I think this isn't the same table name that's the problem but the same entity class name - am I reading this correctly?

**Comment by PythonCreator27** [comment]
It seems so, @bettafish15, could you give the imports of the files the you originally created for a repro? Asking with the original names (TableSameName)? Rename them in the imports using as, but don't rename then entirely.

**Comment by bettafish15** [comment]
> I think this isn't the same table name that's the problem but the same entity class name - am I reading this correctly?

@imnotjames yes i had same entity class name, but that is because i have same table name. Is it in typeorm you have to have different entity class name?

**Comment by bettafish15** [comment]
> It seems so, @bettafish15, could you give the imports of the files the you originally created for a repro? Asking with the original names (TableSameName)? Rename them in the imports using as, but don't rename then entirely.

@PythonCreator27 I dont understand what u meant. My origin table name is Template, and it's in two different schema: public and message. I imported it and used it in TouchpointContactRepository like the code i referenced above. Do you want to see the entity code? I generated it using typeorm-codegen of swagger-codegen so i dont think it's wrong

**Comment by PythonCreator27** [comment]
Could I see the entity and query code (full, along with import statements), together? Maybe the generated code is wrong, and is importing the wrong model (or maybe something similar)? Again, just a thought.

**Comment by imnotjames** [comment]
> > I think this isn't the same table name that's the problem but the same entity class name - am I reading this correctly?
> 
> @imnotjames yes i had same entity class name, but that is because i have same table name. I also think the problem it's in the same entity class name. When i debugging the code the function findMetadata behaved wrongly. Is it in typeorm you have to have different entity class name?

I'm actually not sure!  I was just tossing it out there as it came to mind when I was reading it.  Could be wrong. :)

**Comment by imnotjames** [comment]
This should be fixed in the next release.  This can be confirmed in the latest dev build - `0.2.38-dev.22676a0`

**Comment by forrestwilkins** [comment]
@imnotjames I'm still experiencing this issue on `v0.3.14`. It's not very convenient for local development, where you might have multiple schemas in the same database for convenience, like one for dev, migration testing, etc. that all have a User table.
