### ISSUE TITLE
Cannot find alias for relation at ...

### ISSUE THREAD

**Issue by lucas-labs** [typeorm/typeorm#8310]
## Issue Description
Using `BaseEntity.find` method and trying to filter by a property inside a related entity it throws the following error (this doesn't happen if the property is the PK of the related entity):

```
Error: Cannot find alias for relation at currency
    at _loop_3 (C:\...\node_modules\.pnpm\typeorm@0.2.38_ioredis@4.28.0+pg@8.7.1\src\query-builder\QueryBuilder.ts:954:27)
    at SelectQueryBuilder.QueryBuilder.findColumnsForPropertyPath (C:\...\node_modules\.pnpm\typeorm@0.2.38_ioredis@4.28.0+pg@8.7.1\node_modules\typeorm\query-builder\QueryBuilder.js:827:27)
    at SelectQueryBuilder.<anonymous> (C:\...\node_modules\.pnpm\typeorm@0.2.38_ioredis@4.28.0+pg@8.7.1\src\query-builder\QueryBuilder.ts:1069:68)
    at step (C:\...\node_modules\.pnpm\tslib@2.3.1\node_modules\tslib\tslib.js:143:27)
    at Object.next (C:\...\node_modules\.pnpm\tslib@2.3.1\node_modules\tslib\tslib.js:124:57)
    at SelectQueryBuilder.QueryBuilder.getWhereCondition (C:\...\node_modules\.pnpm\typeorm@0.2.38_ioredis@4.28.0+pg@8.7.1\src\query-builder\QueryBuilder.ts:1208:80)
    at SelectQueryBuilder.where (C:\...\node_modules\.pnpm\typeorm@0.2.38_ioredis@4.28.0+pg@8.7.1\src\query-builder\SelectQueryBuilder.ts:721:32)
    at Function.FindOptionsUtils.applyOptionsToQueryBuilder (C:\...\node_modules\.pnpm\typeorm@0.2.38_ioredis@4.28.0+pg@8.7.1\src\find-options\FindOptionsUtils.ts:184:16)
    at Function.FindOptionsUtils.applyFindManyOptionsOrConditionsToQueryBuilder (C:\...\node_modules\.pnpm\typeorm@0.2.38_ioredis@4.28.0+pg@8.7.1\src\find-options\FindOptionsUtils.ts:72:25)
    at EntityManager.<anonymous> (C:\...\node_modules\.pnpm\typeorm@0.2.38_ioredis@4.28.0+pg@8.7.1\src\entity-manager\EntityManager.ts:677:26)
```

### Expected Behavior

I expect it's possible to find rows filtering by the value of any property of a related entity and not only by its PK.

### Actual Behavior
It throws `Error: Cannot find alias for relation at ...`. See above for the complete stacktrace.

### Steps to Reproduce
Example:

#### Entity
```typescript
@Entity('countries')
export class CountryEntity extends BaseEntity {
    @PrimaryColumn({length: 2})
    id: string;

    ...

    @ManyToOne(() => CurrencyEntity, { nullable: true, eager: true })
    currency: CurrencyEntity;
}
```

```typescript
@Entity('currencies')
export class CurrencyEntity extends BaseEntity {
    @PrimaryColumn()
    id: string;

    ...

    @Column()
    fullName: string;
}
```

Lets say we want to find every single country which official currency's `fullName` is `United States dollar`

```typescript
const markets = await CountryEntity.find({
    where: {
        currency:  {
            fullName: 'United States dollar'
        }
    }
});
```

Result: `Error: Cannot find alias for relation at currency`.

If you search by PK `currency.id` instead of `fullName`, it would work: 
```typescript
const markets = await CountryEntity.find({
    where: {
        currency:  {
            id: 'USD'
        }
    }
});
```

Using `QueryBuilder` also works.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Windows 10  |
| Node.js version     | 16.3.0 | 
| Typescript version  | 4.4.4 | 
| TypeORM version     | 0.2.38 | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by leosuncin** [comment]
I got the same error, I fixed by specifying `relations` in the condition  
  
Try with:

```typescript
const markets = await CountryEntity.find({
    relations: ['currency'],
    where: {
        currency:  {
            fullName: 'United States dollar'
        }
    }
});
```

Note: the downside is that the currency entity with by pulled also, it means, country's currency will be populated.

**Comment by wangdahoo** [comment]
any updates?

**Comment by lucas-labs** [comment]
@wangdahoo not really, I ended up using `QueryBuilder` even though I prefer the `find` API. This is still an issue afaik

**Comment by mikeilabs** [comment]
This used to work, seems to got broken after 0.2.34

**Comment by paulhobbel** [comment]
Probably introduced in #7805

**Comment by andyslack** [comment]
I have the same problem, when trying to use:

```
let options = {
			take: <number>query.limit ?? 20,
			skip: <number>query.offset ?? 0,
			where: {
				brand_id: { $in: user_brand_ids }
			}
		}
		```
		
`brand_id` in this instance refers to a `@ManyToOne` relationship:

```
@Column()
	@ManyToOne(() => Brand, (brand) => brand.id, {
		onDelete: 'CASCADE',
	})
	@JoinColumn({ name: 'brand_id' })
	readonly brand_id: number
```

 Error:  ERROR [ExceptionsHandler] Cannot find alias for relation at brand_id

**Comment by LuisDev99** [comment]
Can confirm that the 'cannot find alias' issue was not a problem before.

**Comment by NenadJovicic** [comment]
Do we have any updates on this issue? because it would be nice not to be forced to populate extra objects if not needed

**Comment by warstrolo** [comment]
Hi I can confirm this was broken after 0.2.34

**Comment by player-9595** [comment]
Can we open PR for this @lucas-labs.  I can submit the fix if needed

**Comment by Ahmad-RW** [comment]
> Can we open PR for this @lucas-labs. I can submit the fix if needed

I can help also if needed. This needs to be fixed asap

**Comment by wassef911** [comment]
updates ?

**Comment by viliamsevela** [comment]
Same problem here, even on version 0.2.45

**Comment by vasabigreencolor** [comment]
const markets = await CountryEntity.find({
    where: {
        currency:  {
            fullName: 'United States dollar'
        }
    },
    relations: ['currency'],
});

**Comment by Hifounder** [comment]
want update
can use `queryBuilder.update()` in `0.2.45` can fix Cannot find alias.

```
let repository = getRepository(Entity);
let queryBuilder: SelectQueryBuilder<Entity>;
queryBuilder = this.repository.createQueryBuilder('entity');

queryBuilder
      .leftJoinAndSelect('entity.relation', 'relation')
      .update<Entity>({ ... } as unknown as EntityTarget<Entity>, { ... })
      .where('relation.id = :id', { id: id })
      .updateEntity(true)
      .execute();
```

**Comment by anhcao142** [comment]
I having this error with delete method. It works normally for finding, but I notice that when generating the query, it generates a random string as an alias for the related table:

```
SELECT CountryEntity.id from country_entity CountryEntity  LEFT JOIN currency "cef765fb0a58526dc35bebe4f53" ON "cef765fb0a58526dc35bebe4f53".id = CountryEntity.currency_id;
```

**Comment by TracyLDavidson** [comment]
I also seem to have this issue with delete method

**Comment by Vtchoo** [comment]
@TracyLDavidson I'm having this issue with the delete method right now, I was trying to delete a related entity using a non-primary column. My workaround was passing `id: Not(IsNull())`

It would be something like this:
```js
await countryEntitiesRepository.delete({
    currency: {
        id: Not(IsNull()),
        fullName: 'United States dollar'
    }
})
```

**Comment by lebesnec** [comment]
@Vtchoo that remove the error but the condition on the non-primary column is totally ignored in my case…

**Comment by aubcel** [comment]
> @Vtchoo that remove the error but the condition on the non-primary column is totally ignored in my case…

I can confirm that. We had similar code like 
```ts
await appointment.delete({
    date: MoreThanOrEqual(dateInput),
    period: { // this is a relation of appointment
        id: Not(IsNull()),
        paricipantId // this is a foreign key
    }
})
```

This results in the following SQL

```SQL
DELETE FROM "appointment" WHERE ("date" >= $1 AND NOT("periodId" IS NULL))
```

So you see, the additional part about the very important `participantId` is missing completely.


Also first adding the relation, like you do e.g. in `find` (see code below) does not work, as `delete` doesn't offer the opportunity as far as I know (only `FindOptionsWhere<T> is possible, but not `FindManyOptions<T>`)
```ts
const appointments = await appointmentRepository.find({
        where: {
          date: MoreThanOrEqual(dateInput),
          period: {
            participantId,
          },
        },
        relations: {
          period: true,
        },
      })
```

Our workaround here was to first fetch all periods, and then map over the Ids. Not the most efficient way, but readable and bullet proof.

```ts
const periods = await periodRepository.find({
      where: {
        participantId,
        to: MoreThanOrEqual(dateInput),
      },
})
// Delete all visitationAppointments
await appointmentRepository.delete({
      date: MoreThanOrEqual(dateInput),
      period: {
        id: In(periods.map(p => p.id)),
      },
})
```

It took us sooo long to find this minor difference, as the IDE also does not show anything, that this might not be possible...
I'd consider this inconsistency a bug and would be happy if `delete` could also handle `FindManyOptions<T>`.
