### ISSUE TITLE
ConnectionNotFound exception with MSSQL

### ISSUE THREAD

**Issue by alessandrojcm** [typeorm/typeorm#898]
Hello, I'm trying out TypeORM for my project; but I can't seem to get it to work. I've followed the instructions in the docs, and adapted my code. Here's the relevant files.
```typescript
import { Column, CreateDateColumn, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm'
import { Entity } from 'typeorm/decorator/entity/Entity'

export enum ProductType {
  Botellon = 'Botellón', Tapa = 'Tapa', Precinto = 'Precinto'
}

@Entity()
export class ProductEntity {

  @PrimaryGeneratedColumn('uuid')
  id: string

  @Column('string')
  type: ProductType

  @Column('text')
  description: string

  @Column('int')
  capacity: number

  @Column('float')
  price: number

  @Column('float')
  upkeepPrice: number

  @Column('int')
  quantity: number

  @CreateDateColumn()
  created: Date

  @UpdateDateColumn()
  updated: Date

  @Column('boolean', {default: false})
  usedInSale: boolean
}
```

I'm loading the config from `ormconfig.json` as follows: 
```
[
  {
    "type": "mssql",
    "logging": "all",
    "dropSchema": "false",
    "synchronize": "true",
    "host": "localhost",
    "port": 50344,
    "username": "SA",
    "password": "password",
    "database": "AquasoftDev",
    "schema": "dbo"
  }
]
```

And my `app.ts`:

```typescript
import { createConnection, getConnection, getConnectionOptions } from 'typeorm'
import 'reflect-metadata'
import { ProductEntity } from './entities/product.entity'

const Winston = require('winston')

Winston.add(Winston.transports.File, {filename: 'info.log'})

getConnectionOptions().then(connectionOptions => {
  return createConnection(Object.assign(connectionOptions, {
    logger: Winston, // Overriding default logger
    entities: [__dirname + '/entities/*.js'] // Setting entities folder
  }))
})

Winston.info(getConnection().isConnected)
Winston.info(getConnection().name)

let product = new ProductEntity()

product.description = 'Probando'

getConnection().getRepository(ProductEntity)
  .persist(product)
  .then((success) => {
    Winston.info('Correcto')
  })
```

The file structure is this:

```
root\
------src\
------src\entities\ProductEntity.ts
------src\app.ts
---ormconfig.json
```

I use a `gulp` script to compile my `.ts` files to JavaScript in an `app` folder, so the file structure for compiled code it's pretty much the same, just change `src` for `app`.

So, when `getConnection()` first gets called, I get a `ConnectionNotFound` exception, not even the table gets created. What am I doing wrong?

**Comment by alessandrojcm** [comment]
So, I tried passing the connection arguments directly; like so:
```typescript
createConnection({
  type: 'mssql',
  host: 'localhost',
  port: 50344,
  username: 'SA',
  password: 'password',
  schema: 'dbo',
  logging: 'all',
  logger: Winston,
  synchronize: true,
  entities: [ProductEntity]
})
```

And the connection works (the connection only, because it throws a `RepositoryNotFound` exception). So it has to do with typeorm not finding the `ormconfig.json` file. And now also it has to do with my entity.

**Comment by pleerock** [comment]
You have `ConnectionNotFound` error because you are calling `getConnection` method before connection is established. First you need to create a connection, await it, then get a connection:

```ts
getConnectionOptions().then(connectionOptions => {
  return createConnection(Object.assign(connectionOptions, {
    logger: Winston, // Overriding default logger
    entities: [__dirname + '/entities/*.js'] // Setting entities folder
  })).then(connection => {
      // here you have a connection and you can call getConnection from anywhere in your app,
      // but only when your core reach this block and connection is really initialized.
  });
})
```

> So it has to do with typeorm not finding the ormconfig.json file. 

Where is your `ormconfig.json` file ? Is it near node_modules directory in root of your project?

**Comment by alessandrojcm** [comment]
> Where is your ormconfig.json file ? Is it near node_modules directory in root of your project?
Yes, it is at the root of the project; next to `node_modules`, `src` and `app`.

> ```typescript
> getConnectionOptions().then(connectionOptions => {
>   return createConnection(Object.assign(connectionOptions, {
>     logger: Winston, // Overriding default logger
>     entities: [__dirname + '/entities/*.js'] // Setting entities folder
>   })).then(connection => {
>       // here you have a connection and you can call getConnection from anywhere in your app,
>       // but only when your core reach this block and connection is really initialized.
>   });
> })
> ```
Ok, I see. So, let me see if I got it right: in that file, if I need to use the connection, I must use it inside the `onFulfilled` callback; and, if I need to get the connection from anywhere else in the app, I must call `getConnection()`. Is that right?

**Comment by pleerock** [comment]
No, its not depend on a single file. You can call `getConnection` anywhere - in this file or any other. Simply make sure to call it once CONNECTION IS ESTABLISHED. Connection is established when `createConnection`'s promise is resolved.

For your issue with ormconfig I would ask you to push a minimal reproduction git repo where I can find this issue. Also check https://github.com/typeorm/typescript-example Its a bit outdated however ormconfig must work properly there as it works in everywhere on me.

**Comment by alessandrojcm** [comment]
> For your issue with ormconfig I would ask you to push a minimal reproduction git repo where I can find this issue. Also check https://github.com/typeorm/typescript-example Its a bit outdated however ormconfig must work properly there as it works in everywhere on me.

I'll check that example out first before pushing a repo, thanks a lot for your help.

**Comment by alessandrojcm** [comment]
So I tried setting `ormconfig` as the example, and it did not work. It doesn't throw the exception anymore; but it doesn't write to the database either.

(Here)[https://github.com/alessandrojcm/minimalexample] is the repo, just add the `ormconfig` and run `gulp compile` to generate the JavaScript files.

**Comment by pleerock** [comment]
Are you new in javascript/nodejs platform? To see error you need to catch it:

```ts
  connection.getRepository(ProductEntity)
    .persist(product)
    .then((success) => {
      Winston.info('Correcto')
    }) // todo: catch here
```

Im sure your entity is not being inserted because of error. Most probably error is that you have non nullable columns and you didn't fill model's properties.

Can you push "ormconfig" in your repo as well? I'll just edit it

**Comment by alessandrojcm** [comment]
> Are you new in javascript/nodejs platform?

Sort of, I've used Express for a little project; but nothing too complicated. Sorry for the noob mistakes.

> Can you push "ormconfig" in your repo as well? I'll just edit it

Done.

**Comment by alessandrojcm** [comment]
> Im sure your entity is not being inserted because of error. Most probably error is that you have non nullable columns and you didn't fill model's properties.

Yes, you are right. I added `catch` to the promise returned by `createConnection` and turns out the problem was 1) `bool` not being supported by MSSQL and 2) non nullable colums. Now it works correctly.

Thanks a lot and sorry for bothering!

**Comment by pleerock** [comment]
No problem. What about ormconfig? Still not working for you?

**Comment by alessandrojcm** [comment]
Yes, it works now. The problem was the exception throw by the Entity.
